packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/split/split.vue
packages/web-vue/components/time-picker/time-picker.vue
packages/web-vue/components/tree-select/interface.ts
packages/web-vue/components/tree-select/tree-select.vue
packages/web-vue/components/tree/tree.vue
packages/web-vue/components/typography/base.tsx
packages/web-vue/components/typography/operations.vue

feat(emits): update components emits

---

packages/arco-vue-docs/docs/start.en-US.md
packages/arco-vue-docs/docs/start.zh-CN.md

按需加载模版ArcoResolver，无法自动引入style，需要打开sideEffect选项

fix: 文档更新，style样式引入需要打开sideEffect

---

packages/arco-vue-docs/docs/pro/npm-scripts.en-US.md
packages/arco-vue-docs/docs/pro/npm-scripts.zh-CN.md
packages/arco-vue-docs/docs/pro/permission.en-US.md
packages/arco-vue-docs/docs/pro/permission.zh-CN.md
packages/arco-vue-docs/docs/pro/routes-and-menu.en-US.md
packages/arco-vue-docs/docs/pro/routes-and-menu.zh-CN.md

docs: update vue pro docs

---

packages/web-vue/components/date-picker/panels/date/index.vue

|     date-picker      |      `选择时间`没有国际化         |        `select time` is not internationalized       |        close #1152         |

fix(date-picker): `select time` is not internationalized

---

packages/web-vue/components/rate/rate.tsx

enhance(rate): ARIA improvement

---

packages/web-vue/components/switch/switch.vue

enhance(switch): ARIA improvement

---

packages/web-vue/components/breadcrumb/breadcrumb-item.tsx
packages/web-vue/components/breadcrumb/breadcrumb.tsx

enhance(breadcrumb): ARIA improvement

---

packages/web-vue/components/input-number/input-number.tsx

enhance(input-number): ARIA improvement

---

packages/web-vue/components/alert/alert.vue
packages/web-vue/components/message/message.vue
packages/web-vue/components/notification/notification.vue
packages/web-vue/components/tooltip/tooltip.vue

enhance: ARIA improvement

---

packages/web-vue/components/progress/circle.vue
packages/web-vue/components/progress/line.vue
packages/web-vue/components/progress/steps.vue

enhance(progress): ARIA improvement

---

packages/web-vue/components/textarea/style/index.less

|  textarea  |  修复设置高度样式后，文本框的显示问题  |  Fix the display problem of the text box after setting the height style   |                |

fix(textarea): fix style problem

---

packages/web-vue/components/cascader/cascader-option.tsx
packages/web-vue/components/cascader/cascader-panel.vue
packages/web-vue/components/cascader/utils.ts

|   cascader  |  修复懒加载情况下，多选状态显示错误的问题  |  Fix the problem that the multi-selection state is displayed incorrectly in the case of lazy loading   |                |
|   cascader  |  修复点击选择框时，多次调用懒加载函数的问题  |  Fix the problem that the lazy loading function is called multiple times when the selection box is clicked   |     #1172           |

fix(cascader): fix lazy load problem

---

packages/web-vue/components/statistic/statistic.vue

|   statistic   |  增加 `placeholder` 属性，用于无值时显示 |  Add the `placeholder` attribute to display when there is no value  |   Close #1004       |

feat(statistic): add placeholder prop

---

packages/web-vue/components/date-picker/README.en-US.md
packages/web-vue/components/date-picker/README.zh-CN.md
packages/web-vue/components/date-picker/interface.ts
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker.vue

… when the mouse leave shortcut
| New feature |      date-picker     |    新增属性 `preview-shortcut` 用于自定义是否要预览快捷选项的结果    |     Added property `preview-shortcur` to customize whether to preview the result of shortcut options          |      close #1127           |
| Enhancement | date-picker | 移出 `shortcut` 的时候重置回已选值 | Reset back to selected value when moving out of `shortcut` |  |

feat(date-picker): Improve the behavior of `shortcut`

---

packages/web-vue/components/tree/__test__/check-utils.test.ts
packages/web-vue/components/tree/__test__/tree-data.ts
packages/web-vue/components/tree/hooks/use-checked-state.ts
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/tree.vue
packages/web-vue/components/tree/utils/check-utils.ts
packages/web-vue/components/tree/utils/index.ts

enhance(tree): improve the calculation logic of check

---

packages/web-vue/components/descriptions/README.en-US.md
packages/web-vue/components/descriptions/README.zh-CN.md

The definition of `DescData` is not present in README of component `a-descriptions`, so it's unclear.
Add definition of `DescData` to README.
Modifications in docs will not bring breaking changes.
|    descriptions       |       README 中添加`DescData`定义        |     Add definition of `DescData` in README          |                |
In fact, the unit test is broken. so I did not pass the test when run `npm run test`. The output is 
Test suite failed to run
Cannot find module '../icon/icon-close' from 'components/alert/alert.vue'
Require stack:
components/alert/alert.vue
components/alert/index.ts
components/arco-vue.ts …

docs: add definition of DescData

---

packages/arco-vue-docs/components/cell-code/index.vue
packages/arco-vue-docs/locale/en-us.js
packages/arco-vue-docs/locale/zh-cn.js
packages/arco-vue-docs/package.json
packages/arco-vue-docs/utils/code-sandbox.ts
packages/arco-vue-docs/utils/code-stackblitz.ts
packages/arco-vue-docs/utils/code-template.ts
yarn.lock

|    docs       |       演示代码支持在 Stackblitz 打开        |       demo code support open in Stackblitz        |       -         |
❗️使用 vite 环境，更易还原 vite 开发下的情况（但在初始化 web container 时，需要安装依赖，有些慢😶‍🌫️）

docs: demo code open in stackblitz

---

packages/web-vue-storybook/stories/components/date-picker.vue
packages/web-vue-storybook/stories/index.stories.ts
packages/web-vue/components/checkbox/checkbox-group.tsx
packages/web-vue/components/date-picker/README.en-US.md
packages/web-vue/components/date-picker/README.zh-CN.md
packages/web-vue/components/date-picker/interface.ts
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/pickers/date-picker.tsx
packages/web-vue/components/date-picker/pickers/month-picker.tsx
packages/web-vue/components/date-picker/pickers/quarter-picker.tsx
packages/web-vue/components/date-picker/pickers/week-picker.tsx
packages/web-vue/components/date-picker/pickers/year-picker.tsx
packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/components/link/link.vue

|   date-picker        |   新增属性 `show-confirm-btn` 用于自定义是否显示确认按钮           |      Added property `show-confirm-btn` to customize whether to show the confirmation button         |       close  #1195         |

feat(date-picker): add property `show-confirm-btn`

---

packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/utils/index.ts

|    date-picker       |    拼接时间的时候只更新日期           |       only update the date when splicing the time        |         close #1094        |

fix(date-picker): only update the date when splicing the time

---

packages/web-vue/components/_hooks/use-pure-prop.ts
packages/web-vue/components/_utils/array.ts
packages/web-vue/components/_utils/is-equal.ts
packages/web-vue/components/_utils/is.ts
packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/__demo__/subtree.md
packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/table/context.ts
packages/web-vue/components/table/hooks/use-row-selection.ts
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table-column.tsx
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table-operation-th.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table-th.tsx
packages/web-vue/components/table/table.tsx
packages/web-vue/components/table/utils.ts

|   table   |   行选择器增加非严格模式支持（级联控制）       |    Line selectors add non-strict mode support (cascading control)   |                |
|   table   |   列属性增加 headerCellStyle 和 bodyCellStyle       |    Column properties add headerCellStyle and bodyCellStyle   |                |

feat(table): add checkStrictly support

---

packages/web-vue/components/tree/tree.vue

|    tree-select       |       修复设置了 field-names 后拖拽失效的问题       |     fixed the problem that drag and drop fails after setting fieldNames        |        close #1200         |

fix(tree-select): drag and drop fails when setting fieldNames

---

packages/arco-vue-docs/docs/pro/faq.en-US.md
packages/arco-vue-docs/docs/pro/faq.zh-CN.md
packages/arco-vue-docs/docs/pro/routes-and-menu.en-US.md
packages/arco-vue-docs/docs/pro/routes-and-menu.zh-CN.md
packages/arco-vue-docs/locale/en-us.js
packages/arco-vue-docs/locale/zh-cn.js
packages/arco-vue-docs/router.ts

docs: add pro faq page

---

packages/web-vue/components/dropdown/__demo__/basic.md
packages/web-vue/components/dropdown/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/dropdown/context.ts
packages/web-vue/components/dropdown/dropdown-button.vue
packages/web-vue/components/dropdown/dropdown-panel.vue
packages/web-vue/components/dropdown/dropdown-submenu.vue
packages/web-vue/components/dropdown/dropdown.vue

|  dropdown  |  增加 `popup-max-height` 属性  |   Added `popup-max-height` property   |                |
|  dropdown  |  子菜单增加 `option-props` 和 icon 插槽  |   Added icon slot to submenu   |   Close #1093    |

feat(dropdown): add max height support

---

packages/web-vue/components/_hooks/use-input.ts
packages/web-vue/components/back-top/back-top.vue
packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/textarea/textarea.vue

|   mention  |  修复 textarea 模式下输入后光标移动的问题             |   Fixed the cursor movement problem after typing in textarea mode    |                |
|   input-number  |  修复 clear 没有触发 form 校验的问题             |     Fixed the issue that clear did not trigger form validation    |                |
|   select  |  修复 inputValue 受控失效的问题      |   Fix the problem of controlled invalidation of inputValue    |                |

fix: input problem

---

packages/web-vue/components/space/space.tsx

|  space  |    修复子组件使用 key 失效的问题   |   Fix the problem that the child component uses the key to fail   |   Close #1220    |

fix(space): fix key problem

---

packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input-number/style/index.less

|  input-number   |   增加键盘事件，聚焦时显示步进按钮   |    Add keyboard event, show step button when focused    |   Close #1194       |

enhance(input-number): add keyboard event

---

packages/web-vue/components/button/style/index.less
packages/web-vue/components/button/style/token.less
packages/web-vue/components/style/theme/css-variables.less
packages/web-vue/components/style/theme/global.less

|    button   |   增加 focus 样式   |   Add focus style   |                |

enhance(button): add focus style

---

packages/web-vue/components/cascader/cascader-panel.vue
packages/web-vue/components/cascader/utils.ts

| Component | Component | Changelog(CN) | Changelog(EN) | Related issues |
|  Enhancement  |  cascader  |   cascader-panel 增加键盘事件       |   cascader-panel adds keyboard events   |                |
|  Bug fix  |  cascader  |   修复使用 number 类型的 value 匹配失败的问题      |   Fix the problem that the value of the number type fails to match   |   Close #1212    |

enhance(cascader): add event

---

packages/web-vue/components/trigger/trigger.tsx

|   trigger   |   不再默认阻止右键默认事件   |   No longer blocks right-click default events by default   |     Close #1109           |

enhance(trigger): not preventDefault when not Contextmenu

---

packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/select/select.tsx
packages/web-vue/components/tree-select/tree-select.vue

|  tree-select  |   搜索模式下组件失焦后会默认清空输入值   |  When the component is out of focus in search mode, the input value will be cleared by default  |                |
|  input-tag  |   失焦时会默认清空输入值   |  When out of focus, the input value will be cleared by default  |                |

enhance(tree-select): clear input value when blur

---

packages/web-vue/components/mention/style/index.ts

|   mention   |  修复按需加载时丢失 textarea 样式的问题  |   Fix missing textarea styles when loading on demand   |   Close #1222     |

fix(mention): fix style problem

---

packages/web-vue/components/_components/virtual-list/filler.vue
packages/web-vue/components/config-provider/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/list/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/TEMPLATE.md
packages/web-vue/components/table/__demo__/fixed-group.md
packages/web-vue/components/table/__demo__/resize.md
packages/web-vue/components/table/__demo__/sticky.md
packages/web-vue/components/table/__demo__/summary.md
packages/web-vue/components/table/__demo__/virtual-list.md
packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/table/hooks/use-drag.ts
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/style/index.less
packages/web-vue/components/table/table-column.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table-th.tsx
packages/web-vue/components/table/table-tr.tsx
packages/web-vue/components/table/table.tsx
packages/web-vue/components/table/utils.ts
packages/web-vue/components/tree/__test__/__snapshots__/demo.test.ts.snap

|  New feature  | Table |   增加 `sticky-header` 表头吸顶功能   |    Added `sticky-header` header ceiling function   |   Close #1006     |
|  New feature  |  Table  |  表格列配置增加 `summaryCellStyle` 属性   |   Added `summaryCellStyle` property to table column configuration  |                |
|  Enhancement  |  Table  |  支持虚拟列表和固定列同时使用   |   Supports the simultaneous use of virtual lists and fixed columns  |                |
|   Bug fix  |  Table   |   修复树型数据时文字省略错误的问题    |   Fixed the problem of incorrect text omission in tree data   | Close #1073         |
|   Bug fix  |  Table   |   修复分组表头与固定列同时使用出现的问题    |   Fix the problem of using grouped headers and …

feat(table): add sticky header

---

packages/web-vue/components/modal/modal.vue

|   modal   |  在组件卸载时重置 overflow 设置  |   Reset overflow setting on component unmount   |                |

fix(modal): reset overflow when unmount

---

packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/input/style/index.less

|   input  |  修复在输入法后不会触发 form 校验的问题  |   Fix the problem that form validation will not be triggered after input method    |                |
|   input  |  修复在 Drawe 中使用带前后置标签产生的高度问题  |   Fixed height issue when using front and back labels in Drawe    |  Close #1261   |

fix(input): fix form validate problem

---

packages/web-vue/components/tabs/style/index.less
packages/web-vue/components/tabs/tabs-tab.vue

|  tabs   |   增加 focus 样式和键盘事件    |   Add focus styles and keyboard events   |                |

enhance(tabs): add focus style and keyboard event

---

packages/web-vue/components/select/select.tsx
packages/web-vue/components/style/animation/zoom.less

|  select  |  修复远程搜索与 fieldNames 同时使用，没有显示选项的问题  |  Fixed remote search and fieldNames used at the same time, no options displayed   |                |

fix(select): fix fieldNames problem

---

packages/web-vue/components/space/style/index.less

|   space  |   space-item 修改为 flex 布局，解决行内元素垂直居中问题       |   space-item is modified to flex layout to solve the problem of vertical centering of inline elements  |    Close #492       |

fix(space): use flex item

---

packages/web-vue/components/_components/input-label/style/input-label.less

|  select   |   修复在选项 label 为空时，选择框塌陷的问题  |  Fixed the issue that the selection box collapsed when the option label was empty  |   Close #1236     |

fix(select): fix empty value style problem

---

packages/arco-vue-docs/locale/en-us.js
packages/arco-vue-docs/locale/zh-cn.js
packages/arco-vue-docs/router.ts
packages/web-vue/components/_hooks/use-component-ref.ts
packages/web-vue/components/arco-vue.ts
packages/web-vue/components/index.less
packages/web-vue/components/index.ts
packages/web-vue/components/list/list.tsx
packages/web-vue/components/scrollbar/README.en-US.md
packages/web-vue/components/scrollbar/README.zh-CN.md
packages/web-vue/components/scrollbar/TEMPLATE.md
packages/web-vue/components/scrollbar/__demo__/basic.md
packages/web-vue/components/scrollbar/__demo__/type.md
packages/web-vue/components/scrollbar/index.ts
packages/web-vue/components/scrollbar/interface.ts
packages/web-vue/components/scrollbar/scrollbar.vue
packages/web-vue/components/scrollbar/style/index.less
packages/web-vue/components/scrollbar/style/index.ts
packages/web-vue/components/scrollbar/style/token.less
packages/web-vue/components/scrollbar/thumb.vue
packages/web-vue/components/select/select-dropdown.vue
packages/web-vue/components/table/table.tsx

|   scrollbar    |   增加虚拟滚动条组件    |   Add virtual scrollbar component   |   Close #23 , Close #913 , Close #243              |
|   scrollbar    |   table、select、list 组件替换虚拟滚动条    |   Table, select, list components replace virtual scroll bars   |             |

feat(scrollbar): add scrollbar component

---

packages/web-vue/components/space/style/index.less
packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md

|  space  |  仅在横向模式使用 flex 布局的 item   |    Items that use flex layout only in landscape mode  |                |

fix(space): fix vertical problem

---

packages/web-vue/components/table/table-th.tsx
packages/web-vue/components/table/table.tsx

|  Bug fix  |  table  |    修复 align='left' 时表头居中的问题  |   Fix the problem that the header is centered when align='left'   |                |
|  Enhancement  |  table  |    无展开按钮时不再显示缩进  |    Indent no longer shows when there is no expand button    |   Close #1268     |

fix(table): fix align problem

---

packages/web-vue/components/modal/modal.vue

|   modal  |   增加 bodyClass 和 bodyStyle   |   Add bodyClass and bodyStyle   |                |

feat(modal): add class and style

---

packages/web-vue-storybook/stories/components/custom-sub-menu.vue
packages/web-vue-storybook/stories/components/menu.vue
packages/web-vue/components/menu/overflow-wrap.tsx

|       menu    |  修复横向菜单收起后无法展开的问题             |  the horizontal menu cannot be expanded after being collapsed             |         close #1292       |

fix(menu): the horizontal menu cannot be expanded after being collapsed

---

packages/web-vue/components/table/hooks/use-expand.ts
packages/web-vue/components/table/hooks/use-filter.ts
packages/web-vue/components/table/hooks/use-row-selection.ts
packages/web-vue/components/table/hooks/use-sorter.ts
packages/web-vue/components/table/table-th.tsx
packages/web-vue/components/table/table.tsx

|   table  |   增加新的组件方法，详情可见文档   |    Add new component methods, see the documentation for details  |                |
|   table  |   titleSlotName 定义的插槽增加 column 参数   |    The slot defined by titleSlotName adds the column parameter  |                |

feat(table): add methods

---

packages/web-vue/components/form/form.vue

|   form   |  resetFields 和  clearValidate 方法增加参数支持         |    Added parameter support for resetFields and clearValidate methods   |                |

feat(form): support param

---

packages/web-vue/components/tag/style/index.less

|     tag      |   火狐浏览器溢出样式兼容  |  Firefox overflow style compatibility  |                |

fix(tag): fix display style

---

packages/web-vue/components/statistic/README.en-US.md
packages/web-vue/components/statistic/README.zh-CN.md
packages/web-vue/components/statistic/__demo__/countdown.md
packages/web-vue/components/statistic/__demo__/prefix.md
packages/web-vue/components/statistic/countdown.vue
packages/web-vue/components/statistic/statistic.vue

|     New feature     |     statistic      |       支持自定义显示值样式        |    support custom value style prop           |        -        |
|     New feature     |     countdown      |       支持自定义显示值样式        |    support custom value style prop           |        -        |
|     Documentation change     |     countdown      |       文档用法更新       |        doc demo usage  update      |        #1314         |

docs(statistic): countdown usage demo

---

packages/arco-vue-docs/docs/start.en-US.md
packages/arco-vue-docs/docs/start.zh-CN.md

docs(start): Update docs

---

packages/web-vue/components/input-number/input-number.tsx

`InputNumber` 组件不在表单中使用时，用 clear 一键清除出错。
重现地址：https://codesandbox.io/s/quirky-leaf-zt1qy2?file=/src/App.vue
| input-number | 修复在表单以外清除时的错误 | fix clear error outside of form |                |

fix(input-number): fix clear error outside of form

---

packages/arco-vue-docs/docs/start.en-US.md
packages/arco-vue-docs/docs/start.zh-CN.md

I was used with vite-plugin-style-import to automatically load component styles from Arco Document, but i get one error
Arco Document config
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport from 'vite-plugin-style-import'
export default defineConfig({
plugins: [
vue(),
styleImport({
libs: [
{
libraryName: '@arco-design/web-vue',
esModule: true,
resolveStyle: (name) => {
// css
return `@arco-design/web-vue/es/${name}/style/css.js`
// less
return `@arco-design/web-vue/es/${name}/style/index.js`
},
}
]
})
]
})
```
when used "pnpm run dev"
```
ERROR  error when starting dev server:
TypeError: (0 , import_vite_plugin_style_import.default) is not a function
```
I read the vite-plugin-style-import document and found that it should be like this …

docs(start): fix way of automatically load component styles

---

packages/web-vue/components/tree/utils/check-utils.ts

…result
|     tree      |    修复点击半选状态的节点显示错误的问题         |     check on the node in the half-selected state have a wrong result          |                |

fix(tree): check on the node in the half-selected state have a wrong result

---

packages/web-vue/components/trigger/trigger.tsx

|  trigger  |     弹出层动画期间不再可以触发事件   |   Events can no longer be fired during popover animations   |  Close #1318 , Close #1310                |

fix(trigger): fix animation problem

---

packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input-tag/input-tag.tsx

|   input-tag   |   修复中文输入法时报错问题   |  Fix the problem of Chinese input method reporting an error  |                |

fix(input): fix event problem

---

packages/web-vue/components/modal/hooks/use-draggable.ts

|   modal  |   修复当模态框超出屏幕大小后，移动位置导致错位的问题             |   Fixed the problem that when the modal box exceeds the size of the screen, the position of the modal will be misaligned  |    Close #1209             |

fix(modal): fix draggable problem

---

packages/web-vue/components/trigger/trigger.tsx
packages/web-vue/components/typography/README.en-US.md
packages/web-vue/components/typography/README.zh-CN.md
packages/web-vue/components/typography/base.tsx
packages/web-vue/components/typography/operations.vue

|  typography  |  新增 `tooltip-props` 类属性  |  Added `tooltip-props` class property  |    Close #1324            |

feat(typography): add tooltip-props

---

packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/table/__demo__/row-selection.md
packages/web-vue/components/table/context.ts
packages/web-vue/components/table/hooks/use-row-selection.ts
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table-th.tsx
packages/web-vue/components/table/table.tsx

|   New feature  |   table  |  TableRowSelection 增加 onlyCurrent 属性，更改表格默认维护所有分页的选择状态   |  TableRowSelection adds the onlyCurrent property to change the default state of the table to maintain the selection state of all paging   |    Close #1016 , Close #1019 , Close #1315             |
|   Enhancement  |   table  |  cellStyle 类属性添加的样式移动到 td 元素上，解决部分场景下背景色问题   |  The style added by the cellStyle class attribute is moved to the td element to solve the background color problem in some scenes   |   Close #1014              |

enhance(table): enhance selection and style

---

packages/web-vue-storybook/stories/components/virtual-list.vue
packages/web-vue/components/_components/virtual-list/hooks/use-item-height.ts
packages/web-vue/components/_components/virtual-list/hooks/use-range-state.ts
packages/web-vue/components/_components/virtual-list/hooks/use-scroll-to.ts
packages/web-vue/components/_components/virtual-list/utils/index.ts
packages/web-vue/components/_components/virtual-list/virtual-list.vue

|   virtual-list        |      修复数据变化的时候显示错误的问题         |       fixed the problem that the list displayed incorrectly when the data changed        |         close #1270 #1239        |

fix(virtual-list): fix list error when data changed

---

packages/arco-vue-docs/docs/pro/faq.en-US.md
packages/arco-vue-docs/docs/pro/faq.zh-CN.md

docs: update pro faq

---

packages/arco-vue-docs/global.d.ts
packages/web-vue-storybook/global.d.ts
packages/web-vue/global.d.ts

fix: fix typescript type declaration

---

packages/web-vue/components/popconfirm/README.en-US.md
packages/web-vue/components/popconfirm/README.zh-CN.md
packages/web-vue/components/popconfirm/TEMPLATE.md
packages/web-vue/components/popconfirm/__demo__/type.md
packages/web-vue/components/popconfirm/style/index.less
packages/web-vue/components/popconfirm/style/token.less

|  popconfirm  |    修复不同类型下图标默认黑色的问题   |   Fix the problem that the icons under different types are black by default  |                |

fix(popconfirm): fix type color problem

---

packages/web-vue/components/input-number/input-number.tsx

|  input-number  |   修复设定精度后会省略 '0' 的问题   |   Fix the problem that '0' will be omitted after setting precision   |                |

fix(input-number): fix precision display problem

---

packages/web-vue/components/_components/input-label/style/input-label.less

|  select  |   修复在火狐浏览器下搜索模式的点击展开问题  |   Fixed click-to-expand issue in search mode in Firefox  |   Close #1086             |

fix(select): fix firefox problem

---

packages/web-vue/components/tree-select/hooks/use-selected-state.ts

|       tree-select         |   修复 `modelValue` 为 0 时, 导致状态不被选中             |     Fix the problem of selected value in case of modelValue is 0          |      #1348       |

fix: fix tree select model value bug

---

packages/web-vue/components/_components/auto-tooltip/auto-tooltip.tsx

|  table  |   修复文本提示没有跟随内容更新的问题   |   Fixed the problem that the text prompt did not follow the content update   |                |

fix(table): fix tooltip update problem

---

packages/arco-changelog/.eslintignore
packages/arco-changelog/.eslintrc.js
packages/arco-changelog/.gitignore
packages/arco-changelog/.prettierrc.js
packages/arco-changelog/README.md
packages/arco-changelog/copy-template.js
packages/arco-changelog/package.json
packages/arco-changelog/src/.github/PULL_REQUEST_TEMPLATE.md
packages/arco-changelog/src/.gitlab/merge_request_templates/CHANGELOG.md
packages/arco-changelog/src/changelog.ts
packages/arco-changelog/src/cmd.ts
packages/arco-changelog/src/config.ts
packages/arco-changelog/src/copy-github.js
packages/arco-changelog/src/default/emit-files.ts
packages/arco-changelog/src/default/template.en-US.njk
packages/arco-changelog/src/default/template.zh-CN.njk
packages/arco-changelog/src/index.ts
packages/arco-changelog/src/interface.ts
packages/arco-changelog/src/test.md
packages/arco-changelog/src/utils/config.ts
packages/arco-changelog/src/utils/convert-case.ts
packages/arco-changelog/src/utils/invert.ts
packages/arco-changelog/src/utils/version.ts
packages/arco-changelog/src/vue/emit-files.ts
packages/arco-changelog/src/vue/template.en-US.njk
packages/arco-changelog/src/vue/template.zh-CN.njk
packages/arco-changelog/src/vue/vue.config.ts
packages/arco-changelog/tsconfig.json

feat: add arco-changelog

---

packages/web-vue/components/tag/README.en-US.md
packages/web-vue/components/tag/README.zh-CN.md
packages/web-vue/components/tag/TEMPLATE.md
packages/web-vue/components/tag/__demo__/bordered.md
packages/web-vue/components/tag/__demo__/checkable.md
packages/web-vue/components/tag/__demo__/dynamically.md
packages/web-vue/components/tag/__demo__/icon.md
packages/web-vue/components/tag/style/index.less
packages/web-vue/components/tag/style/token.less
packages/web-vue/components/tag/tag.vue

|       New feature      |     tag       |        支持 `bordered` 显示边框       |    support `bordered`  show border        |     -           |
❗️Border style code from [react arco](https://github.com/arco-design/arco-design/blob/main/components/Tag/style/token.less), Maybe tag border style influential custom theme system

feat(tag): tag support border and demo update

---

packages/web-vue/components/upload/utils.tsx

|  upload  |  修复在阿里云OSS中的使用问题  |    Fixed usage issues in Alibaba Cloud OSS   |   Close #1135 , Close #1279             |
|  tree  |  修复子树展开动画中为处理过滤数据的问题  |    Fix the problem of filtering data for processing in the subtree expansion animation   |    |

fix(upload): fixed the problem when used with aliyun oss

---

packages/web-vue/components/collapse/README.en-US.md
packages/web-vue/components/collapse/README.zh-CN.md
packages/web-vue/components/collapse/TEMPLATE.md
packages/web-vue/components/collapse/__demo__/custom.md
packages/web-vue/components/collapse/__demo__/expand-icon.md
packages/web-vue/components/collapse/__demo__/extra.md
packages/web-vue/components/collapse/__demo__/icon-position.md
packages/web-vue/components/collapse/__demo__/nested.md
packages/web-vue/components/collapse/collapse-item.tsx
packages/web-vue/components/collapse/collapse.vue
packages/web-vue/components/collapse/context.ts
packages/web-vue/components/collapse/index.ts

| ---------   | --------- | ------------- | ------------- | -------------- |
|    New feature        |    collapse       |       支持自定义展开图标        |       Supports custom expand icon        |      -          |
|    Documentation change        |    collapse       |       文档用法更新        |       doc demo usage update        |      -          |

feat(collapse): support custom icon & update usage demo

---

packages/web-vue/components/modal/style/index.less

发现modal在simple模式下的footer的按钮不居中。发现是每个按钮都有有一个margin-left，但其实第一个按钮不应该有。所以要去掉。
复现：https://codesandbox.io/s/suspicious-pascal-64j53q?file=/src/App.vue
考虑到非simple模式下第一个按钮也不需要margin-left。所以modal=>footer的第一个按钮margin-left取消掉。:not(:nth-child(1))
| modal | 修复 footer 按钮不居中的问题  |     Fix the problem that the footer button is not centered       |                |

fix(modal): madal footer button not centered

---

packages/web-vue/components/tabs/style/index.less

|   tabs   |   修复聚焦时样式错误的问题   |    Fix the problem of wrong style when focusing   |     Close #1306           |

fix(tabs): fix focus style problem

---

packages/web-vue/components/drawer/drawer.vue
yarn.lock

|       drawer    |    添加 header 属性和插槽           |         add header prop and slot      |      Close #1246            |

feat: add header prop for Drawer component

---

packages/arco-changelog/README.md
packages/arco-changelog/package.json
packages/arco-changelog/src/config.ts
packages/arco-changelog/src/default/emit-files.ts
packages/arco-changelog/src/interface.ts

feat(changelog): add filename

---

packages/web-vue/components/modal/modal.vue

|   modal  |  修复默认标题类名错误的问题      |   Fix the problem that the default title class name is wrong   |    Close #1412             |

fix(modal): fix title class problem

---

packages/web-vue/components/form/style/index.less

|   form  |  修复 form-item 内容可能超出限制宽度的问题  |   Fix form-item content may exceed limit width    |   Close #1435    |

fix(form): fix min-width problem

---

packages/web-vue/components/cascader/base-cascader-panel.tsx
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/cascader/style/index.less

|   cascader   |   修复搜索下拉菜单的横向滚动条位置错误问题   |   Fixed the wrong position of the horizontal scroll bar of the search drop-down menu  |    Close #1343            |
|   cascader   |   修复搜索模式下，输入内容后不能使用光标的问题   |   Fix the problem that the cursor cannot be used after inputting content in search mode    |    Close #1433            |

fix(cascader): fix keyboard & scroll problem

---

packages/web-vue/components/table/style/index.less

|   table   |   单独设置 selected-keys 时可以显示选中行   |  Selected rows can be displayed when selected-keys are set individually   |    Close #1417            |

enhance(table): allow checked-row

---

packages/web-vue/components/input-tag/input-tag.tsx

|  input-tag  |   修复设置 max-tag-count 后，remove 事件中 value 参数错误的问题   |   Fix the problem that the value parameter in the remove event is wrong after setting max-tag-count    |     Close #1382      |

fix(input-tag): fix the problem of can't delete when set max-tag-count

---

packages/web-vue/components/typography/operations.vue

|      typography     |       后缀 icon 点击事件取消冒泡        |       cancel click propagation of suffix icon        |       Close:  #1349         |

fix(typography): operation click should not propagation

---

packages/web-vue-storybook/stories/components/virtual-list.vue
packages/web-vue/components/_components/virtual-list-v2/hooks/use-size.ts
packages/web-vue/components/_components/virtual-list-v2/index.ts
packages/web-vue/components/_components/virtual-list-v2/interface.ts
packages/web-vue/components/_components/virtual-list-v2/style/index.less
packages/web-vue/components/_components/virtual-list-v2/virtual-list-item.tsx
packages/web-vue/components/_components/virtual-list-v2/virtual-list.vue
packages/web-vue/components/_utils/vue-utils.ts
packages/web-vue/components/list/list.tsx
packages/web-vue/components/list/style/index.less
packages/web-vue/components/select/select.tsx
packages/web-vue/components/table/table.tsx
packages/web-vue/components/tree/tree.vue

|   common   |   重构虚拟列表组件  |  Refactor the virtual list component   |   Close #1357 , Close #1347 , Close #1239 , Close #1238              |

enhance(virtual-list): refactor virtual list

---

packages/web-vue/components/_utils/dom.ts
packages/web-vue/components/components.ts
packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/TEMPLATE.md
packages/web-vue/components/drawer/__demo__/function.md
packages/web-vue/components/drawer/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/drawer/index.ts
packages/web-vue/components/drawer/interface.ts
packages/web-vue/components/index.ts

| Drawer | 添加函数调用 | add function call |                |

feat(drawer): add function call

---

packages/web-vue/components/modal/README.en-US.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/index.tsx
packages/web-vue/components/modal/interface.ts

| modal | 支持在函数调用中隐藏页脚 | support hide footer in function call |                |

feat(modal): support hide footer in function call

---

packages/web-vue/components/auto-complete/README.en-US.md
packages/web-vue/components/auto-complete/README.zh-CN.md
packages/web-vue/components/auto-complete/TEMPLATE.md
packages/web-vue/components/auto-complete/__demo__/footer.md
packages/web-vue/components/auto-complete/auto-complete.tsx

| `auto-complete`          |   增加`footer`插槽            |add `footer` slot               |  Close #1439        |

feat(auto-complete): add footer slot

---

packages/web-vue/components/table/table.tsx

为Table组件增加动态的rowClassName支持
Added function based rowClassName support in the table component
当前版本的rowClass无法动态，只能给固定的，无法进行灵活业务逻辑操作。
为rowClass增加function类型的参数，同时将数据以及行索引带入function中。
```
//为Table增加row-class="testFunc"
<a-table
:row-class="testFunc"
v-bind="getBindValues"
:pagination="pagination"
page-position="br"
:hide-expand-button-on-empty="true"
@page-change="handlePageChange"
@page-size-change="handlePageSizeChange"
@select="handleSelect"
@select-all="handleSelectAll"
@row-click="clickRowData"
@cell-click="clickCellData"
@sorter-change="sorterChange"
class="basicTable"
>
</a-table>
//增加函数
const testFunc= (record, rowIndex) => {
//具体业务逻辑
}
```
|  table  | …

add function rowclass for table.tsx

---

packages/web-vue/components/pagination/pagination.tsx

|   pagination   |    增加 autoAdjust 属性   |   Add autoAdjust property |                |

feat(pagination): add autoAdjust prop

---

packages/web-vue/components/timeline/context.ts
packages/web-vue/components/timeline/index.ts
packages/web-vue/components/timeline/item.vue
packages/web-vue/components/timeline/style/index.less
packages/web-vue/components/timeline/timeline.tsx

|   timeline   |   修复时间线使用 v-if 时计算错误的问题   |   Fixed an issue where the timeline was incorrectly calculated when using v-if   |                |

fix(timeline): fix update problem

---

packages/web-vue/components/mention/index.ts
packages/web-vue/components/textarea/index.ts

fix(mention & textarea): fix the type name of component export

---

packages/web-vue/components/transfer/transfer-list-item.tsx

item slot add value param for issues #1295
|  transfer  |   item 插槽增加 value 属性   |  item slot adds value attribute |                |
- [x ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others

feat(transfer): item slot add value param for issues #1295

---

packages/web-vue/components/input-number/input-number.tsx
yarn.lock

|       input-number    |        支持`read-only`属性       |         Support `read-only` prop      |      Close: #1407           |

feat: add input number readonly support

---

packages/web-vue/components/table/table.tsx

|  table   |    columns 支持 reactive 类型的更新           |  columns support reactive type updates  |                |

enhance(table): support reactive columns

---

packages/web-vue/components/dropdown/README.en-US.md
packages/web-vue/components/dropdown/README.zh-CN.md
packages/web-vue/components/dropdown/dropdown-button.vue

`<dropdown-button />`无法根据下拉菜单的状态显示不同的icon
为`<dropdown-button />`的icon插槽加入prop: `popup-visible`
|dropdown-button           |为icon插槽加入新的porp:  `popup-visible`              |add new prop for icon slot: `popup-visible`               |                |

feat(dropdown-button): add new prop for icon slot: popup-visible

---

packages/web-vue/components/upload/utils.tsx

|     upload      |     修复设置 `accept=*` 时失效的问题          |      fix the problem of `accept=*` does not work        |                |

fix: fix accept file util

---

packages/web-vue/components/cascader/style/index.less

在下拉面板中显示`empty`会导致样式异常:https://codesandbox.io/s/black-morning-0srrr1?file=/src/App.vue
将`.arco-cascader-panel`的display设置为`inline-flex`
https://stackoverflow.com/questions/48117071/element-with-display-inline-flex-has-a-strange-top-margin
| cascader  | 修复下拉面板为空时的样式问题 | Fix style issue when dropdown panel is empty    |                |

style(cascader): fix dropdown panel style

---

packages/web-vue/components/menu/sub-menu-pop.vue
packages/web-vue/components/menu/sub-menu.tsx

|     Menu      |        `Menu`组件dom属性由popup换为aria-popup       |      change `Menu` attribute popup to aria-haspopup         |        #1486         |

fix: change sub menu attr popup to aria-haspopup

---

packages/web-vue/components/_components/virtual-list-v2/hooks/use-size.ts
packages/web-vue/components/_components/virtual-list-v2/virtual-list-item.tsx
packages/web-vue/components/_components/virtual-list-v2/virtual-list.vue
packages/web-vue/components/index.less
packages/web-vue/components/table/table.tsx

fix(virtual-list): fix some problem

---

packages/web-vue/components/upload/utils.tsx

fix: upload accept prop bug

---

packages/web-vue/components/table/style/index.less

当固定列下方有z-index>1的组件时它会显示在固定列之上，比如`badge`组件
将固定列的z-index调整为1000
不知道是否有更好的解决方案
| `table-column`          |调整固定列的 zIndex               |adjust zIndex of a fixed col               |https://github.com/arco-design/arco-design-vue/issues/1478                |

style(table-column): adjust zIndex of a fixed col

---

packages/arco-vue-docs/components/article/style.less

docs: article description lont text and changelog button overlap

---

packages/web-vue/components/divider/README.en-US.md
packages/web-vue/components/divider/README.zh-CN.md
packages/web-vue/components/divider/__demo__/basic.md
packages/web-vue/components/divider/__demo__/with-text.md
packages/web-vue/components/divider/divider.tsx

|      divider     |      分割线宽度及样式设置         |     support split line width and style         |        -        |
|      divider     |      分割线边距设置         |      support split line margin        |          -      |

feat(divider): support line style and margin

---

packages/web-vue/components/trigger/trigger.tsx

|   trigger   |   优化在 KeepAlive 下使用的问题，缓存时关闭弹出层       |   Optimize the use of KeepAlive, close the pop-up layer when caching   |                |

enhance(trigger): enhance KeepAlive

---

packages/web-vue/components/button/button.vue

|       button    |   当状态为 loading 或 disabled 时点击不会触发默认事件      |     Default event is not triggered on click when state is loading or disabled        |     Close #1511            |

fix: fix click loading button in form can trigger submit

---

packages/web-vue/components/form/__demo__/validation.md
packages/web-vue/components/time-picker/time-picker.vue

#1509
|  time-picker  |   修复 time-picker 中 size 属性的默认值问题   |   Fix default value of size property in time-picker    |      #1509           |

fix(time-picker): remove the default value of the size prop

---

packages/web-vue/components/spin/style/index.less

|   spin   |   修复 fixed-column 的 z-index 提高导致的 spin 问题   |   Fix the spin problem caused by the increase of the z-index of fixed-column    |   Close #1518 , Close #1528             |

fix(spin): fix z-index problem

---

packages/web-vue/components/date-picker/picker.vue

|      date-picker     |      修复部分模式下选择面板年月选择时单击选择事件异常         |       Fixed the click selection event exception when selecting the year and month of the selection panel in some modes    |           Close: #1536      |

fix: DatePicker quick select from month bug

---

packages/web-vue/components/_utils/responsive-observe.ts

|  common  |   组件库内部 matchMedia 方法调整兼容 Safari 13        |  Adjust the matchMedia method inside the component library to be compatible with Safari 13    |                |

enhance: matchMedia compatible with safari 13

---

packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/TEMPLATE.md
packages/web-vue/components/drawer/__demo__/basic.md
packages/web-vue/components/drawer/__demo__/custom.md
packages/web-vue/components/drawer/__demo__/function.md
packages/web-vue/components/drawer/__demo__/nested.md
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/drawer/interface.ts

| docs |     drawer      |      头部展示属性描述错误         |        Error in description of header display attribute       |      #1497           |
| docs |     drawer      |      文档案例调整及优化         |        Document case adjustment and optimization       |      -           |

docs(drawer): fix header description & add new demo

---

packages/web-vue/components/image/style/preview.less

|   image  |   修复预览模式下关闭按钮图标位置错误的问题   |   Fix the problem that the close button icon is in the wrong position in preview mode    |   Close #1543             |

fix(image): fix preview close button icon position problem

---

packages/web-vue/components/date-picker/range-picker.vue

|  date-picker  |   优化范围选择器在选择时也会修正顺序   |  Optimized range selector also corrects order when selecting  |                |

enhance(date-picker): correct order on select

---

packages/web-vue/components/pagination/style/index.less

|    pagination   |     修复显示内容被压缩的问题    |     Fix the problem that the display content is compressed    |                |

fix(pagination): fix the problem that the display content is compressed

---

packages/arco-vue-docs/docs/pro/directory.en-US.md
packages/arco-vue-docs/docs/pro/directory.zh-CN.md

docs: vue documentation link migration

---

packages/web-vue/components/input/input-password.vue

for issues https://github.com/arco-design/arco-design-vue/issues/1434
fix icon error
|  input  |   修改密码输入框图标  |  Modify password input box icon   |    Close #1434            |
- [√] Test suite passes (`npm run test`)
- [√] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [√] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others

fix(input-password): fix icon error for issues #1434

---

packages/web-vue/components/breadcrumb/README.en-US.md
packages/web-vue/components/breadcrumb/README.zh-CN.md
packages/web-vue/components/breadcrumb/TEMPLATE.md
packages/web-vue/components/breadcrumb/__demo__/dropdown.md
packages/web-vue/components/breadcrumb/__demo__/ellipsis.md
packages/web-vue/components/breadcrumb/__demo__/icon.md
packages/web-vue/components/breadcrumb/__demo__/routes.md
packages/web-vue/components/breadcrumb/__demo__/separator.md
packages/web-vue/components/breadcrumb/__demo__/size.md
packages/web-vue/components/breadcrumb/breadcrumb-item.tsx
packages/web-vue/components/breadcrumb/breadcrumb.tsx
packages/web-vue/components/breadcrumb/context.ts
packages/web-vue/components/breadcrumb/interface.ts

|      breadcrumb     |      支持 separator  属性     |     suport separator prop          |        -        |
|      breadcrumb     |      支持 routes  属性     |     suport routes prop          |        -        |
|      breadcrumb     |      支持 more-icon  插槽     |     suport more-icon slot          |        -        |
|      breadcrumb     |     `breadcrumb-item` 支持 droplist  属性和插槽     |     suport droplist prop  and slot         |        -        |
🤔 RFC（暂时不实现）

feat(breadcrumb): support routes and more props config

---

packages/web-vue/components/locale/lang/pt-pt.ts
packages/web-vue/components/locale/lang/zh-tw.ts

- Add `zh-TW` support
- Add `pt-PT` support  
|     common      |       增加`繁体中文（台湾）`支持        |       Add `zh-TW` support        |                |
|     common      |       增加`葡萄牙语（葡萄牙）`支持        |       Add `pt-PT` support        |                |

feat: add locale zhTW and ptPT

---

packages/web-vue/components/alert/README.en-US.md
packages/web-vue/components/alert/README.zh-CN.md
packages/web-vue/components/alert/TEMPLATE.md
packages/web-vue/components/alert/__demo__/action.md
packages/web-vue/components/alert/__demo__/close-element.md
packages/web-vue/components/alert/alert.vue

|    alert       |       支持自定义关闭元素        |      suport custom close element         |        -        |

feat(alert): support custom close element

---

packages/web-vue/components/image/image.vue
packages/web-vue/components/image/interface.ts

https://github.com/arco-design/arco-design-vue/issues/1523
add fit props
|     image      |    增加 fit 属性   |   Add fit prop   |                |

feat(image): add fit props

---

packages/web-vue/components/breadcrumb/__demo__/dropdown.md
packages/web-vue/components/breadcrumb/__demo__/routes.md
packages/web-vue/components/breadcrumb/breadcrumb-item.tsx
packages/web-vue/components/breadcrumb/breadcrumb.tsx
packages/web-vue/components/breadcrumb/index.ts
packages/web-vue/components/breadcrumb/interface.ts
packages/web-vue/components/dropdown/dropdown.vue
packages/web-vue/components/dropdown/index.ts
packages/web-vue/components/dropdown/interface.ts
packages/web-vue/components/index.ts

|   New feature  |   breadcrumb   |  增加 customUrl 属性  | Add customUrl property  |                |
|   Typescript definition change  |   common   |  增加 dropdown 和 breadcrumb 组件中类型的导出  | Added export of types in dropdown and breadcrumb components  |                |

feat(breadcrumb): add ts export & breadcrumb customUrl

---

packages/web-vue/components/_utils/types.ts
packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/context.ts
packages/web-vue/components/table/hooks/use-expand.ts
packages/web-vue/components/table/hooks/use-row-selection.ts
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table-col-group.vue
packages/web-vue/components/table/table-column.tsx
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table-th.tsx
packages/web-vue/components/table/table.tsx
packages/web-vue/components/table/utils.ts

| New feature | table | 新增自定义类名相关属性 | Add custom class name related prop |                |
| Enhancement | table | 扩展 key 的类型 | type of extension key | Close #1145 |

enhance(table): support custom cell class

---

packages/web-vue/components/checkbox/README.en-US.md
packages/web-vue/components/checkbox/README.zh-CN.md
packages/web-vue/components/checkbox/TEMPLATE.md
packages/web-vue/components/checkbox/__demo__/custom.md
packages/web-vue/components/checkbox/__demo__/group.md
packages/web-vue/components/checkbox/__demo__/limit.md
packages/web-vue/components/checkbox/__demo__/options.md
packages/web-vue/components/checkbox/checkbox-group.tsx
packages/web-vue/components/checkbox/checkbox.tsx
packages/web-vue/components/checkbox/context.ts

|    checkbox       |       新增 max 属性，支持设置最多可被勾选的项目数       |       Add max prop, support setting the maximum number of items that can be checked        |      #1505          |
❗️没有支持 `min`

feat(checkbox-group): support limit the maximum number of options

---

packages/web-vue/components/index.ts
packages/web-vue/components/layout/index.ts
packages/web-vue/components/layout/interface.ts

|    layout  |   增加 ts 类型导出   |   Add ts type export  |                |

feat: add layout type definition

---

packages/web-vue/components/page-header/README.en-US.md
packages/web-vue/components/page-header/README.zh-CN.md
packages/web-vue/components/page-header/__demo__/basic.md
packages/web-vue/components/page-header/__demo__/breadcrumb.md
packages/web-vue/components/page-header/__demo__/content.md
packages/web-vue/components/page-header/__demo__/transparent.md
packages/web-vue/components/page-header/page-header.vue

|      page-header     |      支持自定义返回按钮        |    support custom back icon           |          -      |

feat(page-header): custom back-icon slot

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/table.tsx

|  Type | Component | Changelog(CN) | Changelog(EN) | Related issues |
|  ----  | --------- | ------------- | ------------- | -------------- |
| Docs | Table          |       补充 `row-class` 函数支持版本       |       supplement `row-class` fucntion support version        |      #1553          |

docs(table): fix row-calss function support version #1553

---

packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/drawer/interface.ts
packages/web-vue/components/modal/README.en-US.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/__demo__/async.md
packages/web-vue/components/modal/interface.ts
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/popconfirm/README.en-US.md
packages/web-vue/components/popconfirm/README.zh-CN.md
packages/web-vue/components/popconfirm/popconfirm.vue

| modal |  on-before-ok 属性支持函数返回 Promise | The on-before-ok property supports function returning a Promise | #1552 #1581 #376 #1530 |
| drawer | on-before-ok 属性支持函数返回 Promise | The on-before-ok property supports function returning a Promise | #1552 |
| popconfirm | on-before-ok 属性支持函数返回 Promise | The on-before-ok property supports function returning a Promise | #1552 |

enhance(modal): support on-before-ok prop receive async function

---

packages/web-vue/components/breadcrumb/README.en-US.md
packages/web-vue/components/breadcrumb/README.zh-CN.md
packages/web-vue/components/dropdown/README.en-US.md
packages/web-vue/components/dropdown/README.zh-CN.md
packages/web-vue/components/dropdown/dropdown-option.vue
packages/web-vue/components/image/README.en-US.md
packages/web-vue/components/image/README.zh-CN.md

| dropdown | 选项禁用时不触发单击事件 | Don't fire click event when option is disabled |                |

enhance(dropdown): option don't trigger a click event when disabled

---

packages/web-vue/components/select/select.tsx

| select |  修复 option 插槽参数错误的问题  | Fix option slot parameter problem |                |

fix(select): fix option slot parameters

---

packages/web-vue/components/split/README.zh-CN.md
packages/web-vue/components/split/TEMPLATE.md
packages/web-vue/components/split/__demo__/basic.md
packages/web-vue/components/split/__demo__/nested.md

Fixed split component typo.
| --------- |  ---------  | ------------- | ------------- | -------------- |
|    docs       |      split     |      修复文本错误         |      fix text error         |       -         |

docs(split): fix text error

---

packages/arco-vue-docs/docs/faq.en-US.md
packages/arco-vue-docs/docs/faq.zh-CN.md
packages/web-vue/components/_components/virtual-list-v2/interface.ts
packages/web-vue/components/list/README.en-US.md
packages/web-vue/components/list/README.zh-CN.md
packages/web-vue/components/list/TEMPLATE.md
packages/web-vue/components/list/list.tsx
packages/web-vue/components/select/README.en-US.md
packages/web-vue/components/select/README.zh-CN.md
packages/web-vue/components/select/TEMPLATE.md
packages/web-vue/components/select/hooks/use-select.ts
packages/web-vue/components/select/interface.ts
packages/web-vue/components/select/select.tsx
packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/TEMPLATE.md
packages/web-vue/components/table/table.tsx
packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/TEMPLATE.md
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/tree.vue

|Type| Component | Changelog(CN) | Changelog(EN) | Related issues |
|      docs     |     virtual-v2      |       接口和使用说明        |         Interface and instructions for use      |     -           |
Select, List, Table, Tree 组件的 `virtual-list-props` 的类型
组件类型支持 2.34.1 没更新，这里更新会有类型废弃属性

docs: virtual v2 doc  & usage

---

packages/web-vue/components/switch/README.en-US.md
packages/web-vue/components/switch/README.zh-CN.md
packages/web-vue/components/switch/TEMPLATE.md
packages/web-vue/components/switch/__demo__/change-intercept.md
packages/web-vue/components/switch/switch.vue

| ----- | --------- | ------------- | ------------- | -------------- |
|  feat | switch          |      支持 `beforeChange` 切换事件拦截         |      support `beforeChange` intercept change event         |                #1592 |
|  docs | switch          |      切换拦截案例         |      switch intercept demo         |    -  |

feat(switch): add beforeChange intercept change event

---

packages/web-vue/components/link/README.en-US.md
packages/web-vue/components/link/README.zh-CN.md
packages/web-vue/components/link/TEMPLATE.md
packages/web-vue/components/link/__demo__/loading.md
packages/web-vue/components/link/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/link/link.vue
packages/web-vue/components/link/style/index.less
packages/web-vue/components/link/style/token.less

| link | 添加加载中状态属性 | add loading prop |                |

feat(link): add loading prop

---

packages/web-vue/components/list/README.en-US.md
packages/web-vue/components/list/README.zh-CN.md
packages/web-vue/components/list/TEMPLATE.md
packages/web-vue/components/list/__demo__/actions-layout.md
packages/web-vue/components/list/__demo__/actions.md
packages/web-vue/components/list/__demo__/grid.md
packages/web-vue/components/list/__demo__/responsive-grid.md
packages/web-vue/components/list/__demo__/scroll.md
packages/web-vue/components/list/__demo__/virtual-list.md
packages/web-vue/components/list/list.tsx

| ----- | --------- | ------------- | ------------- | -------------- |
|  docs |   list        |      新增使用案例         |       add usage demo        |       -         |
| feat |   list        |      支持响应式网格布局参数         |       support responsive grid props        |       -         |
🤔 响应式网格没有任何结构修改，仅算是一直使用增强

docs(list): add usage demo & enhan responsive grid

---

packages/web-vue/components/typography/__demo__/ellipsis.md
packages/web-vue/components/typography/base.tsx
packages/web-vue/components/typography/interface.ts
packages/web-vue/components/typography/style/index.less

|  typography   |   省略模式增加支持 CSS 方式（实验性）   |   Omit mode adds support for CSS mode (experimental)   |                |

feat: add css ellipsis

---

packages/web-vue/components/_hooks/use-component-ref.ts
packages/web-vue/components/cascader/style/index.ts
packages/web-vue/components/dropdown/style/index.ts
packages/web-vue/components/list/style/index.ts
packages/web-vue/components/scrollbar/scrollbar.vue
packages/web-vue/components/scrollbar/style/index.less
packages/web-vue/components/select/hooks/use-select.ts
packages/web-vue/components/select/select-dropdown.vue
packages/web-vue/components/select/style/index.ts
packages/web-vue/components/table/style/index.ts
packages/web-vue/components/table/table.tsx

|   common   |   修复内置虚拟滚动条的组件按需加载时丢失样式的问题  |   Fix the problem that the component with built-in virtual scrollbar loses its style when it is loaded on demand  |                |
|   scrollbar   |   修复在 Firefox 下的样式问题  |   Fix styling issues in Firefox  |                |
|   table   |   修复 scroll 属性中 maxHeight 导致虚拟滚动条样式错误问题  |  Fixed the virtual scroll bar style error caused by maxHeight in the scroll property    |                |
|   select   |   修复键盘交互中下拉菜单没有跟随滚动的问题  |   Fixed the problem that the drop-down menu did not follow the scrolling in keyboard interaction  |                |
|   select   |   修复内置虚拟滚动条部分情况下报错的问题  |  Fix the problem of error reporting in …

fix(scrollbar): fix some problem

---

packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/popconfirm/popconfirm.vue

| Component  | Changelog(CN)                                      | Changelog(EN)                                                | Related issues |
| ---------- | -------------------------------------------------- | ------------------------------------------------------------ | -------------- |
| common      |  组件 onBeforeOk 属性的返回值 `Promise<void>` 与 `done()`方法默认行为调整为成功 | The return value of the component's onBeforeOk property `Promise<void>` and the `done()` method default behavior adjusted to success | #1628 , Close #1633          |

fix: on-before-ok bugs

---

packages/web-vue/components/image/README.en-US.md
packages/web-vue/components/image/README.zh-CN.md
packages/web-vue/components/image/image.vue
packages/web-vue/components/typography/README.en-US.md
packages/web-vue/components/typography/README.zh-CN.md
packages/web-vue/components/typography/base.tsx

文档中有一些链接无法正确的跳转到正确的位置
将链接修改为正确的链接
| Type| Component | Changelog(CN) | Changelog(EN) | Related issues |
|Docs           |`typography`           | 修复 ellipsis-config链接错误              |fix ellipsis-config link error               |                |
|Docs           |`image`           | 修复 image-preview-props链接错误              |fix image-preview-props link error             |                |

docs: fix some link error

---

packages/web-vue/components/empty/empty.tsx

|   empty   |   优化自定义显示优先级，image 插槽高于全局 empty 插槽   |   Optimize the custom display priority, the image slot is higher than the global empty slot   |   Close #1671    |

enhance(empty): optimize custom display order

---

packages/web-vue/components/_hooks/use-cursor.ts
packages/web-vue/components/input/input.tsx
packages/web-vue/components/textarea/textarea.vue

|  input  |   优化最大限制时不再可以从中间输入内容  |   It is no longer possible to input content from the middle when optimizing the max limit  |                |

enhance(input): enhance max limit

---

packages/web-vue/components/overflow-list/README.en-US.md
packages/web-vue/components/overflow-list/README.zh-CN.md
packages/web-vue/components/overflow-list/overflow-list.tsx

|    overflow-list       |      溢出数量改变事件         |       overflow quantity changes event        |         -       |

feat(overflow-list): add overflow change event

---

packages/web-vue/components/_components/auto-tooltip/auto-tooltip.tsx

|     table      | 修复内容变化后tooltip不显示的问题 | Fix the problem that the tooltip does not display after the content changes | Close #1664 |
点击 edit 按钮后，前两行 name 溢出不显示 tooltip
https://codesandbox.io/s/zen-leftpad-xn5n0o?file=/src/App.vue

fix: fix update tooltip visible after content change

---

packages/web-vue/components/image/preview.vue

for issues https://github.com/arco-design/arco-design-vue/issues/1657
|     image      |    actionsLayout为空时不显示操作栏           |      do not display toolbar when actions layout is empty         |     Close #1657          |

fix(imagePreview): do not display toolbar when actions layout is empty

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/interface.ts

| table | 修复 TableRowSelection 类型声明 | fix TableRowSelection type definition | Close #1665 |

fix(table): fix type definition

---

packages/web-vue/components/tabs/tabs-tab.vue

|   tabs   |   修复 `card` 类型下标签内容没有居中的问题            |     Fix the problem that the content of the label under the `card` type is not centered    |                |

fix(tabs): fix style problem

---

packages/web-vue/components/input-tag/style/input-tag.less
packages/web-vue/components/tag/style/index.less

|   select   |    修复自定义标签颜色显示错误的问题    |   Fix the problem that the custom label color is displayed incorrectly   |                |

fix(select): fix custom tag color problem

---

packages/web-vue/components/button/style/index.less
packages/web-vue/components/link/style/index.less

|  button   |   使用 flex 布局方式，解决 icon 大小不一致时的居中问题   |   Use the flex layout method to solve the centering problem when the icon size is inconsistent    |                |
|  link   |   使用 flex 布局方式，解决 icon 大小不一致时的居中问题   |   Use the flex layout method to solve the centering problem when the icon size is inconsistent   |                |

enhance(button): use flex layout

---

packages/web-vue/components/drawer/index.ts
packages/web-vue/components/modal/index.tsx

| Modal | 修复对话框关闭的问题 | fix modal close problem |                |
| Drawer | 修复抽屉关闭的问题 | fix drawer close problem |                |

fix(modal): fix modal close problem

---

packages/web-vue/components/_hooks/use-popup-manager.ts

|  common    | 修复弹出层叠顺序 | fix popup stack | Close #1602 |

fix: fix popup stack

---

packages/web-vue/components/collapse/style/index.less

当展开图标在右侧时内容的padding-left应该与标题的padding-left相同
当展开图标在右侧时调整内容的padding-left
|collapse           | 当expand-icon在右侧时,调整collapse-item-content的padding              | adjust the padding of collapse-item-content when expand-icon is on the right               |                |

style(collapse): adjust the padding of collapse-item-content when expand-icon is on the right

---

packages/web-vue/components/table/__demo__/summary.md
packages/web-vue/components/table/hooks/use-filter.ts
packages/web-vue/components/table/hooks/use-sorter.ts

|   table  |   修复 default sorter&filters 在模板用法下失效的问题  |   Fix default sorter&filters not working under template usage   |                |

fix(table): fix default sorter&filters invalid in template

---

packages/web-vue/components/transfer/style/index.less

| Transfer | 修复无法滚动问题 | Fix can't scroll problem | Close #1722 , Close #1742 |

fix(transfer): fix transfer scrolling

---

packages/web-vue/components/spin/spin.tsx

fix #1716 
|   spin   |    修复 size 在失效的问题   |  Fix the problem that size is invalid    |    Close #1716            |

Fix sizing issue for spin

---

packages/web-vue/components/table/style/index.less

table 同时开启总结行 和 表格滚动时，总结行高度会被压缩
示例  [https://codesandbox.io/s/k10wxb?file=/src/App.vue](https://codesandbox.io/s/k10wxb?file=/src/App.vue)
|    table       |     修复表格同时开启总结行和滚动时，总结行高度被压缩的问题         |    Fixed the problem that summary row height was compressed when both summary row and scroll were enabled in the table     |                |

fix(table): fix summary row problem with table scrolling

---

packages/web-vue/components/modal/index.tsx

#1681 
|     modal      |      函数式调用可以设置 renderToBody 参数         |         Functional calls can set the renderToBody parameter     |       Close #1681          |

enhance(modal): Model.open can set renderToBody

---

packages/web-vue/components/descriptions/README.en-US.md
packages/web-vue/components/descriptions/README.zh-CN.md
packages/web-vue/components/descriptions/descriptions.tsx
packages/web-vue/components/descriptions/style/index.less

| Description |描述中表格样式的 `layout-fixed`，当设置成 `fixed` 时，宽度会均分 | The `layout-fixed` of the table style in the description. The width will be evenly distributed when it's set to `fixed`.|     Close #1345         |

enhance(descriptions): 新增 tableLayout属性

---

packages/web-vue/components/notification/README.en-US.md
packages/web-vue/components/notification/README.zh-CN.md
packages/web-vue/components/notification/TEMPLATE.md
packages/web-vue/components/notification/__demo__/basic.md
packages/web-vue/components/notification/__demo__/btn.md
packages/web-vue/components/notification/__demo__/custom-close.md
packages/web-vue/components/notification/__demo__/position.md
packages/web-vue/components/notification/__demo__/style.md
packages/web-vue/components/notification/__demo__/type.md
packages/web-vue/components/notification/__demo__/update_duration.md
packages/web-vue/components/notification/__demo__/update_notification.md
packages/web-vue/components/notification/index.ts
packages/web-vue/components/notification/interface.ts
packages/web-vue/components/notification/notification-list.tsx
packages/web-vue/components/notification/notification.vue
packages/web-vue/components/notification/style/index.less

|     fix      |     Notification      |      提示框和提示框列表间隔样式调整         |       notification and  notification listspace style adjustment        |      -          |
|     fix      |     Notification      |      `showIcon` 属性无效         |       `showIcon` not working        |      -          |
|     feat      |     Notification      |      支持自定义关闭按钮和元素         |       support custom close icon & close element        |      -          |
|     feat     |     Notification      |     支持自定义样式        |       support custom style       |      -          |
|     feat    |     Notification      |     删除对应 `id` 的提示框        |       temove the notification …

fix-feat-docs(notification): list style, showIcon, custom close & style

---

packages/web-vue/components/collapse/README.en-US.md
packages/web-vue/components/collapse/README.zh-CN.md
packages/web-vue/components/collapse/collapse-item.tsx

| collapse  |     修复CollapseItem类型声明    |  fix CollapseItem type definiton  |  Close #1719    |

fix(collapse): fix type definition

---

packages/web-vue/components/collapse/README.en-US.md
packages/web-vue/components/collapse/README.zh-CN.md
packages/web-vue/components/collapse/collapse-item.tsx

|`collapse-item`           |允许使用数字作为key               |allows use of number as key               |Close #1719                |

enhance(collapse-item): allows use of number as key

---

packages/web-vue/components/select/select.tsx

Relative to [https://github.com/arco-design/arco-design-vue/issues/1728](https://github.com/arco-design/arco-design-vue/issues/1728)
When using remote search, keep the previously selected option label
|   select    |  增加已选择项的缓存，优化在远程搜索时的 label 显示问题 | Increase the cache of selected items, and optimize the label display problem during remote search |  Close #1728    |

fix: selected option label in remote search

---

packages/web-vue/components/cascader/utils.ts

cascader组件在多选模式下被禁用的子节点可以被父节点选中
https://codesandbox.io/s/crazy-agnesi-kmm2s0?file=/src/App.vue
|  cascader           | 修复多选时，子菜单全部 disabled 时的显示问题       | Fix the display problem when all submenus are disabled when multiple selections are made          | Close #1715                |

fix(cascader): fix multiple select problem

---

packages/web-vue/components/_components/picker/style/index.less
packages/web-vue/components/_components/picker/style/token.less

|   date-picker    |    修复在 safari 下 disabled 样式错误的问题    |     Fix the problem of disabled style error under safari    |                |

fix(picker): fix safari style problem

---

packages/web-vue/components/cascader/cascader-option.tsx
packages/web-vue/components/cascader/interface.ts
packages/web-vue/components/cascader/utils.ts

|  cascader   |  优化多选时的子菜单全部禁用时，父级禁止选择  |    When the submenus are all disabled when optimizing multi-selection, the parent prohibits the selection    |                |

enhance(cascader): enhance multi disabled

---

packages/web-vue/components/upload/README.en-US.md
packages/web-vue/components/upload/README.zh-CN.md
packages/web-vue/components/upload/interfaces.ts
packages/web-vue/components/upload/upload.tsx

在`upload`的api文档中，很多通用api的描述是与图片绑定的，有误导性
修改有误导性的描述
| Type| Component | Changelog(CN) | Changelog(EN) | Related issues |
| ---------| --------- | ------------- | ------------- | -------------- |
| docs          |upload           | 更新文档              |update docs               |                |

docs(upload): update docs

---

packages/web-vue/components/progress/steps.vue

for issue https://github.com/arco-design/arco-design-vue/issues/1752
fix steps active error
|   progress   |  优化分割点的展示逻辑  |   Optimize the display logic of split points   |                |

fix(progress): fix steps active error

---

packages/web-vue/components/pagination/page-jumper.vue

close: #1734 
|  pagination  |   优化输入页码时的数字处理   |    Optimize number processing when entering page numbers  |    Close #1734             |

feat(pagination): Make sure to enter an integer in the input box

---

packages/web-vue/components/trigger/trigger.tsx

获取arrow样式时没有获取popup最新的位置，导致arrow位置错误
https://codesandbox.io/s/h9rr3c?file=/src/App.vue
在更新popup位置后获取arrow样式
| trigger   | 修复在 windows 中 arrow 定位错误的问题               |Fix the problem of wrong arrow positioning in windows          | Close #1475       |

fix(trigger): fix arrow position error

---

packages/web-vue/components/cascader/index.ts
packages/web-vue/components/descriptions/index.ts
packages/web-vue/components/grid/index.ts
packages/web-vue/components/index.ts
packages/web-vue/components/overflow-list/index.ts
packages/web-vue/components/table/index.ts

|  common  | 添加实例类型导出 | Add instance type export |                |

enhance: add instance types export

---

packages/web-vue/components/form/form-item.vue

| form | 不修改规则原始对象数据 | Do not modify the original object data of the rule | Close #1763 |

fix: fix form rule problem

---

packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/__test__/__snapshots__/index.test.ts.snap
packages/web-vue/components/drawer/__test__/index.test.ts
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/drawer/index.ts
packages/web-vue/components/modal/index.tsx
packages/web-vue/components/modal/modal.vue

| modal | 修复函数式调用中关闭未卸载内部组件的问题 | Fix the problem that closing does not unload internal components in function calls |                |
| drawer | 修复函数式调用中关闭未卸载内部组件的问题 | Fix the problem that closing does not unload internal components in function calls |                |

fix: fix the problem of modal memory leak

---

packages/web-vue/components/select/select.tsx

|   select  |   修复 formatLabel 在无数据时报错的问题    |    Fix formatLabel error when there is no data    |     Close #1762   |

fix(select): fix formatLabel problem

---

packages/web-vue/components/modal/modal.vue

|  modal  |   修复自定义 style 时 z-index 不能生效的问题   |  Fix the problem that z-index does not take effect when custom style   |   Close #1788           |

fix(modal): fix modal custom zIndex problem

---

packages/web-vue/components/table/style/index.less

|   table  |   修复暗黑模式下 stripe 样式问题   |   Fix stripe style issue in dark mode   |    Close #1791    |

fix(table): fix stripe style problem

---

packages/web-vue/components/checkbox/checkbox.tsx
packages/web-vue/components/radio/radio.tsx

|   radio    |  修复清除 model-value 时状态未清除的问题  |   Fix the problem that the state is not cleared when clearing model-value   |   Close #1793   |
|   checkbox    |  修复清除 model-value 时状态未清除的问题  |   Fix the problem that the state is not cleared when clearing model-value   |                |

fix(radio): fix modelValue set undefined problem

---

packages/web-vue/components/_hooks/use-cursor.ts

|  input  | 修复某些场景下组件光标报错的问题 | Fix the problem of component cursor reporting error in some scenarios |                |

fix: fix cursor hook

---

packages/web-vue/components/slider/utils.ts

close: #1816 
the percentage has negative value
the percentage should larger than 0
|       slider    |     修复滑动输入条设置最小值起始位置错误          |      fix the slider show wrong position when set min value         |    Close  #1816          |

fix(slider): the slider show wrong position when set min value

---

packages/web-vue/components/table/context.ts
packages/web-vue/components/table/table-operation-th.tsx
packages/web-vue/components/table/table.tsx

Table 在计算全选选择器的状态时，在总数量中排除了被 disabled 的行的数量。
但是在计算选中行的数量时未排除被 disabled 的行的数量（disabled 的行会被 selected-keys 选中）。
|       table    |    修复全选状态计算错误的问题         |      Fix the problem of incorrect calculation of all-selected status       |                |

fix(table): Fix the problem of all-selected status

---

packages/web-vue/components/table/table.tsx

| table | 修复rowClass为函数时的参数 | fix param when rowClass as function |                |

fix(table): fix param when rowClass as function

---

packages/web-vue/components/pagination/page-jumper.vue
yarn.lock

|  pagination  |   修复 jumper 提示警告的问题   |   Fix jumper prompt warning problem  |    Close #1814            |
close: https://github.com/arco-design/arco-design-vue/issues/1814

fix(pagination): Eliminate page jumper warnings (#1814)

---

packages/web-vue/components/_components/virtual-list-v2/virtual-list-item.tsx
packages/web-vue/components/_components/virtual-list-v2/virtual-list.vue
packages/web-vue/components/radio/radio-group.tsx

|   common   |    修复虚拟列表的一些问题    |   Fixed some issues with virtual lists   |                |

fix(virtual): fix key problem

---

packages/web-vue/components/date-picker/pickers/date-picker.tsx

| date-picker| 修复内部属性错误问题 | Fix internal property error issue |                |

fix(date-picker): fix prop error

---

packages/web-vue/components/input-tag/input-tag.tsx

|  input-tag   |   修复删除键会删除不可用选项的问题   |   Fixed delete key deleting unavailable options    |                |

fix(input-tag): fix delete problem

---

packages/web-vue/components/table/__demo__/row-selection.md
packages/web-vue/components/table/context.ts
packages/web-vue/components/table/table-operation-th.tsx
packages/web-vue/components/table/table.tsx

|  table   |   修复行选择器状态错误的问题   |   Fix row selector state error  |                |

fix(table): fix row-selection problem

---

packages/web-vue/components/space/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/space/space.tsx

| Space | 修复分隔符间距 | fix split margin |                |

fix(space): fix split margin

---

packages/web-vue/components/switch/README.en-US.md
packages/web-vue/components/switch/README.zh-CN.md
packages/web-vue/components/switch/style/token.less
packages/web-vue/components/switch/switch.vue

| Switch | 修复状态改变前钩子的值 | Fix value of hook before state change |                |
| Switch | 修复样式 token 问题 | Fix style token issue | Close #1858 |

fix(switch): fix before change value and style token

---

packages/web-vue/components/_hooks/use-scrollbar.ts
packages/web-vue/components/tree-select/panel.tsx
packages/web-vue/components/tree-select/style/index.less
packages/web-vue/components/tree-select/tree-select.vue

|  tree-select   |  替换虚拟滚动条组件，增加 scrollbar 属性  |  Replace the virtual scrollbar component and add the scrollbar property  |   Close #1839    |

enhance(tree-select): replace virtual scrollbar

---

packages/web-vue/components/transfer/README.en-US.md
packages/web-vue/components/transfer/README.zh-CN.md
packages/web-vue/components/transfer/TEMPLATE.md
packages/web-vue/components/transfer/__demo__/tree.md
packages/web-vue/components/transfer/style/index.less
packages/web-vue/components/transfer/transfer-view.vue
packages/web-vue/components/transfer/transfer.vue

|   transfer   |  新增面板插槽，允许自定义内容  |   Added panel slot to allow custom content  |                |
|   transfer   |  内部替换为虚拟滚动条  |   internally replaced with a virtual scrollbar   |                |

feat(transfer): support content slot

---

packages/web-vue/components/transfer/README.en-US.md
packages/web-vue/components/transfer/README.zh-CN.md
packages/web-vue/components/transfer/transfer-view.vue
packages/web-vue/components/transfer/transfer.vue

|transfer           |可以隐藏全选勾选框               |can hide select all checkbox               |                |

enhance(transfer): can hide select all checkbox

---

packages/web-vue/components/upload/upload-list-item.tsx

|upload           |添加一些常见的文件类型               |add some common file type               |                |

enhance(upload): add some common file type

---

packages/web-vue/components/date-picker/range-picker.vue

|   date-picker   |   修复选择年范围时无法跳转10年     |       year range can't skip by 10 year        |      close: #1760           |

fix(date-picker): year range can't skip by 10 year

---

packages/web-vue/components/locale/lang/ja-jp.ts

|   common  |  修复日文语言包确实某些属性的问题  |  Fix the problem that the Japanese language pack does not display certain properties    |                |

fix(locale): fix ja-jp problem

---

packages/arco-vue-docs-navbar/package.json
packages/arco-vue-docs-navbar/src/index.tsx
packages/arco-vue-docs-navbar/src/navbar.css
packages/arco-vue-docs-navbar/src/navbar.less
packages/arco-vue-docs-navbar/src/style/history.less
packages/arco-vue-docs-navbar/src/style/hot.less
packages/arco-vue-docs-navbar/src/style/list.less
packages/arco-vue-docs/package.json
yarn.lock

|  common   |   更新导航栏   |   update navbar   |                |

feat(navbar): update to new navbar

---

packages/web-vue/CHANGELOG.zh-CN.md

docs(changelog): typo "确实" to "缺失"

---

packages/arco-vue-docs/docs/pro/routes-and-menu.en-US.md
packages/arco-vue-docs/docs/pro/routes-and-menu.zh-CN.md

摸鱼刷知乎刷到的：[如何看待字节跳动推出前端组件库 Arco Design？ - 趣趣多的回答](https://www.zhihu.com/question/494828193/answer/2713675101)

docs: typo "local" to "locale"

---

packages/web-vue/components/divider/divider.tsx

根据 props.size 属性值生成的 style 样式错误
指定 size 属性时，会根据 direction 属性值判断返回 style 结果，但是结果不对。
|  divider  |   修复设置 size 时，样式错误的问题   |   Fix the problem that the style is wrong when setting size    |                |

fix(divider): 指定 size 属性时，style 生成的样式错误

---

packages/web-vue/components/input/input.tsx

| Input | 修复 change 事件触发问题，以及 clear 清除问题 | Fix change event triggering issue and clear clearing issue | Close #1911 |

fix(input): fix clear problem

---

packages/web-vue/components/scrollbar/scrollbar.vue
packages/web-vue/components/table/table.tsx

|   table  |  修复 thead 在某些情况下会出现纵向滚动条的问题   |   Fix the problem that thead will have a vertical scroll bar in some cases   |   Close #1894   |

fix(table): fix thead scroll problem

---

packages/web-vue/components/drawer/__demo__/async.md
packages/web-vue/components/drawer/__demo__/basic.md
packages/web-vue/components/drawer/__demo__/custom.md
packages/web-vue/components/drawer/__demo__/nested.md
packages/web-vue/components/drawer/__demo__/popup-container.md
packages/web-vue/components/modal/__demo__/async.md
packages/web-vue/components/modal/__demo__/basic.md
packages/web-vue/components/modal/__demo__/custom.md
packages/web-vue/components/modal/__demo__/draggable.md
packages/web-vue/components/modal/__demo__/fullscreen.md
packages/web-vue/components/modal/__demo__/width.md

|    modal,drawer       |        错别字更改       |        fix typo       |                |

fix(docs): typo

---

packages/web-vue/components/avatar/README.en-US.md
packages/web-vue/components/avatar/README.zh-CN.md
packages/web-vue/components/avatar/TEMPLATE.md
packages/web-vue/components/avatar/__demo__/image-url.md
packages/web-vue/components/avatar/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/avatar/avatar.vue
packages/web-vue/components/avatar/style/index.less

https://github.com/arco-design/arco-design-vue/issues/1741
add custom image url path
|   avatar    |   增加 image-url 属性，支持使用图片地址    |   Add image-url attribute to support the use of image URLs     |     Close #1741           |

feat(avatar): add custom image url path

---

packages/web-vue/components/scrollbar/README.en-US.md
packages/web-vue/components/scrollbar/README.zh-CN.md
packages/web-vue/components/scrollbar/scrollbar.vue

https://github.com/arco-design/arco-design-vue/issues/1896
add scrollbar methods

feat(scrollbar): add scrollbar methods

---

packages/web-vue/components/auto-complete/auto-complete.tsx

https://github.com/arco-design/arco-design-vue/issues/1749
add focus and blur method
|  auto-complete   |  增加 focus 和 blur 方法  | Add focus and blur methods  |     Close #1749   |

feat(auto-complete): add focus and blur method

---

packages/web-vue/components/list/__demo__/scroll.md
packages/web-vue/components/list/list.tsx
packages/web-vue/components/table/style/index.less

|   list   |  修复 scrollbar 属性传递虚拟滚动条属性时失效的问题   |  Fix the problem that the scrollbar attribute fails when passing the virtual scrollbar attribute  |   Close #1927  |

fix(list): fix scrollbar props problem

---

packages/web-vue/components/form/style/status.less

|    Form       |      修复 `Form` 组件的 `validate-status` 属性在 `date-picker` 组件不生效的 bug。         |      Fix the bug that `validate-status` attribute of `Form` component does not take effect in `date-picker` component.         |                |

fix: validateStatus not work in datepicker

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/__demo__/filter.md
packages/web-vue/components/table/__demo__/sort.md
packages/web-vue/components/table/__test__/index.test.ts
packages/web-vue/components/table/table.tsx

|   table  |   change 事件增加当前数据参数  |    The change event increases the current data parameter  |   Close #1884             |
close: #1884

feat(table): `change` event adds parameter `currentDataSource`

---

packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/cascader-panel.vue
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/select/README.zh-CN.md
packages/web-vue/components/select/select.tsx

|      cascader, select     |       修正文字描述        |        Correction of text description       |                |

docs: Correction of text description

---

packages/web-vue/components/_components/picker/input-range.vue
packages/web-vue/components/_components/picker/input.vue
packages/web-vue/components/_components/picker/style/index.less
packages/web-vue/components/avatar/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/form/__demo__/status.md
packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/form/style/status.less
packages/web-vue/components/input/style/input.less
packages/web-vue/components/time-picker/__test__/__snapshots__/demo.test.ts.snap

|    date-picker       |      修复 `Form` 组件的 `feedback` 属性在  `date-picker` 组件不生效的 bug。       |         Fix the bug that the `feedback` attribute of the `Form` component does not take effect in the `date-picker` component.      |                |

fix: feedback not work in datepicker

---

packages/web-vue/components/switch/style/index.less

|switch|  修复switch组件type为line,size为small,checked状态圆点偏移不正确             |    Fixed the switch component whose type is line, size is small, and the checked state dot offset is incorrect           |      Close #1974      |

fix(switch):switch类型为line,size为small,checked状态没有特定的样式

---

packages/web-vue/components/tabs/__demo__/type.md
packages/web-vue/components/tabs/style/index.less
packages/web-vue/components/tabs/style/token.less

|  tabs |  修复 `rounded` 和 `capsule` 类型下 `size` 不生效的问题  |  Fix the problem that `size` does not take effect under `rounded` and `capsule` types  |                |

fix(tabs): fix size problem

---

packages/web-vue/components/list/style/index.less

|    list       |          修复栅格列表模式出现滚动条的问题     |       Fix the problem that the scroll bar appears in the grid list mode        |         Close #1963      |

fix(List): grid list does not need scroll bar

---

packages/web-vue/components/date-picker/panels/week-list.vue

|     DatePicker      |       修复在国际化下面板文案显示错误的问题        |       Fix the problem that the panel text display error under internationalization       |    Close  #1962           |

fix(DatePicker): fix issues in i18n

---

packages/web-vue/components/input/input.tsx

|  input  |   修复 `change` 事件触发逻辑问题  |  Fix `change` event trigger logic problem   |   Close #1986      |

fix(input): fix change event problem

---

packages/web-vue/components/input/input.tsx

docs(input): typo

---

packages/web-vue/components/upload/upload.tsx

| upload  |  增加 `upload` 方法 |  Add `upload` method |                |

feat(upload): add upload method

---

packages/web-vue/components/typography/utils/measure.tsx

|  Typography  |  修复父容器设置`white-space: nowrap`时 ellipsis 失效  |   Fixed ellipsis invalidation with parent container setting `white-space: nowrap`   |  Close  #1961           |

fix(Typography): Fixed ellipsis prop invalidation when parent container is set to white-space: nowrap

---

.github/workflows/deploy-site-preview.yml
package.json
packages/arco-vue-scripts/package.json
packages/arco-vue-scripts/src/configs/vite.site.prod.ts
packages/arco-vue-scripts/src/index.ts
packages/arco-vue-scripts/src/scripts/test/screentshot.ts
packages/arco-vue-scripts/tsconfig.json
packages/web-vue/.gitignore
packages/web-vue/package.json
yarn.lock

chore: add preview yml

---

packages/web-vue/components/locale/lang/es-es.ts

|   common  |   增加西班牙语   |   add spanish   |                |

feat: add es locale

---

packages/web-vue/components/upload/utils.ts

|    upload       |  修复 `upload` 组件在部分场景下验证上传文件符合 `accept` 格式时，判断错误的 bug。             |   Fix the bug that the `upload` component judged wrongly when verifying that the uploaded file conforms to the `accept` format in some scenarios.            |                |

fix: upload filter files error

---

packages/web-vue/components/input/input.tsx

input组件word-length计算字符的长度不会被max-length限制
将原有判断逻辑的与逻辑运算符改为或逻辑运算符
|     input      |      修复自定义计算字符长度不会被 `max-length` 限制的问题       |     Fix the problem that the custom calculation character length will not be limited by `max-length`          |    Close #1926            |

fix(input): 修复input组件word-length计算字符的长度不会被max-length限制

---

packages/web-vue/components/mention/mention.tsx
packages/web-vue/components/select/hooks/use-select.ts

| mention  |   修复 textarea 模式下回车键失效的问题  |   Fix the problem that the Enter key is invalid in textarea mode    |                |

fix(mention): fix enter problem

---

packages/arco-vue-docs/docs/i18n.en-US.md
packages/arco-vue-docs/docs/i18n.zh-CN.md
packages/web-vue/components/config-provider/__demo__/basic.md
packages/web-vue/components/config-provider/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/locale/lang/ar-eg.ts
packages/web-vue/components/locale/lang/de-de.ts
packages/web-vue/components/locale/lang/es-es.ts
packages/web-vue/components/locale/lang/fr-fr.ts
packages/web-vue/components/locale/lang/id-id.ts
packages/web-vue/components/locale/lang/it-it.ts
packages/web-vue/components/locale/lang/ko-kr.ts
packages/web-vue/components/locale/lang/ms-my.ts
packages/web-vue/components/locale/lang/th-th.ts

|  common         |     增加 印度尼西亚语， 法语（法国）， 德语（德国）， 韩语， 意大利语(意大利)，马来语（马来西亚），泰语语言文件。                       |        Added Indonesian, French (France), German (Germany), Korean, Italian (Italy),Malay (Malaysia), Thai language files.        ||

feat: add locale

---

packages/web-vue/components/table/table.tsx

|    table       |     修复仅 `operations` 列固定的情况下没有阴影的问题     |      Fix the problem that there is no shadow when only the `operations` column is fixed   |   Close  #1937            |

fix(table): only the operation column fixed still has shadow

---

packages/web-vue/components/_components/picker/input-range.vue
packages/web-vue/components/_components/picker/input.vue
packages/web-vue/components/_components/picker/style/index.less
packages/web-vue/components/_components/picker/style/token.less
packages/web-vue/components/date-picker/README.en-US.md
packages/web-vue/components/date-picker/README.zh-CN.md
packages/web-vue/components/date-picker/__demo__/prefix.md
packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/time-picker/README.en-US.md
packages/web-vue/components/time-picker/README.zh-CN.md
packages/web-vue/components/time-picker/__demo__/prefix.md
packages/web-vue/components/time-picker/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/time-picker/time-picker.vue

|     date-picker      |    `date-picker` 支持 `prefix` 插槽。          |      `date-picker` supports prefix slots         |                |
|     time-picker      |    `time-picker` 支持 `prefix` 插槽。          |      `time-picker` supports prefix slots         |                |

feat: DatePicker and TimePicker supports prefix slots

---

packages/web-vue/components/alert/__demo__/type.md
packages/web-vue/components/alert/alert.vue
packages/web-vue/components/alert/style/index.less
packages/web-vue/components/alert/style/token.less
packages/web-vue/components/message/__demo__/type.md
packages/web-vue/components/message/index.ts
packages/web-vue/components/message/interface.ts
packages/web-vue/components/message/message.vue

|   alert   |   增加 `normal` 类型   |   Add `normal` type   |                |
|   message   |   增加 `normal` 类型   |     Add `normal` type   |                |

feat(message): add normal type

---

packages/web-vue/components/tabs/__demo__/editable.md
packages/web-vue/components/tabs/style/index.less
packages/web-vue/components/tabs/tabs-nav.tsx
packages/web-vue/components/tabs/utils.ts

|  tabs   |  修复在 `capsule` 类型下滚动异常的问题  |  Fix the problem of scrolling exception under `capsule` type   |    Close #2019    |

fix(tabs): fix capsule scroll problem

---

packages/arco-vue-scripts/src/scripts/icongen/svgo.config.ts
packages/arco-vue-scripts/src/scripts/icongen/vue-template.ts

|   icon   |   优化组件 `click` 事件，在组件中进行封装透传  |  Optimize the `click` event of the component, and perform encapsulation and transparent transmission in the component    |    Close #2015      |

enhance(icon): enhance click event

---

packages/web-vue/components/checkbox/checkbox.tsx

|  checkbox |   修复 `value` 值缺少类型的问题    |   Fix missing type for `value` values   |   Close #2025   |

fix(checkbox): fix value typescript

---

packages/web-vue/components/table/style/index.less

|   table   |  修复开启 `scroll` 时浏览器缩放后可能出现宽度错误的问题  |   Fix the problem that the width error may appear after the browser is zoomed when `scroll` is turned on  |  Close #2012   |

fix(table): fix width problem when scale

---

packages/web-vue/components/upload/upload.tsx

|  upload  |   修复上传时可能导致删除文件错误的问题   |   Fixed an issue that could cause file deletion errors when uploading   |                |

fix(upload): fix upload status

---

packages/web-vue/components/slider/README.en-US.md
packages/web-vue/components/slider/README.zh-CN.md
packages/web-vue/components/slider/slider-button.vue
packages/web-vue/components/slider/slider.vue

|   slider   |     添加show-tooltip属性    |    add show-tooltip props     |    Close #2017   |

feat(slider): add show-tooltip props

---

packages/arco-vue-docs/docs/pro/build.en-US.md
packages/arco-vue-docs/docs/pro/build.zh-CN.md
packages/arco-vue-docs/docs/pro/npm-scripts.en-US.md
packages/arco-vue-docs/docs/pro/npm-scripts.zh-CN.md

docs: 修改vite最新官网地址

---

packages/web-vue/components/upload/context.ts
packages/web-vue/components/upload/upload-picture-item.tsx
packages/web-vue/components/upload/upload.tsx

| upload |   增加 `showPreviewButton` 属性    |   Add `showPreviewButton` property  | Close #1869 |

feat(upload): add new prop

---

packages/web-vue/components/tooltip/__demo__/color.md

|     Tooltip      |        修改button的文字描述       |      Modify the text description of the button         |                |

docs(Tooltip): Correction of text description

---

packages/web-vue/components/scrollbar/scrollbar.vue

|      scrollbar     |        修复emits 的 ts 声明错误       |            fix ts declaration error for emits  |       #2076         |

fix(scrollbar):  fix ts declaration error

---

packages/web-vue/components/input-number/input-number.tsx

`input-number`在`min`或`max`变化时进步按钮无法正确的启用或禁用
监听`min`与`max`来为进步按钮设置正确的状态并将`modelValue`设置为范围之内的值
|input-number           |修复当最小/最大值改变时进步按钮不能正确禁用或启用的问题               |fix step-button is not properly disabled or enabled when min or max is changed               |Close #1773                |

fix(input-number): fix step-button is not properly disabled or enabled when min or max is changed

---

packages/web-vue/components/upload/upload.tsx

upload 组件文档对 show-preview-button 作用描述错误
改变代码注释，符合正确逻辑
肉眼验证，无需测试
|      upload     |      文档更新         |     docs update          |                |
- [ x] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others

feat: 修复文档描述错误

---

packages/web-vue/components/menu/sub-menu.tsx

#2089
https://github.com/vuejs/core/blob/9c304bfe7942a20264235865b4bb5f6e53fdee0d/packages/runtime-core/src/helpers/renderSlot.ts#L27-L28
|menu           |修复热更新问题               |fix the hotreload problem               |close #2089                 |

fix(menu): fix the hotreload problem

---

packages/web-vue-storybook/stories/components/date-picker.vue
packages/web-vue/components/date-picker/README.en-US.md
packages/web-vue/components/date-picker/README.zh-CN.md
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker.vue

#1946
Added a new prop to control `<input>` readonly.
| `date-picker` | 增加 `disabled-input` 属性，可以禁用键盘输入 | Add the `disabled-input` property to disable keyboard input | Close #1946 |

feat(date-picker): add disable input support

---

packages/web-vue/components/tabs/tabs-nav.tsx

|   tabs  |   无匹配选项卡时，隐藏选项卡指示器  |  Hide the tab indicator when there are no matching tabs  |   Close #2068 , Close #2069              |

fix(tabs): fix nav-ink problem

---

packages/web-vue/components/upload/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/upload/style/index.less
packages/web-vue/components/upload/upload-list-item.tsx
packages/web-vue/components/upload/upload-picture-item.tsx
packages/web-vue/components/upload/upload.tsx

|    upload       |     新增文件列表额外按钮插槽 `#extra-button`          |       Added file list extra button slot `#extra-button`        |                |

Feat upload extra button

---

packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/drawer/interface.ts

| drawer | 添加 `before-open` 和 `before-close` 事件 | add `before-open` and `before-close` events | Close #2061 |

feat(drawer): add `before-open` and `before-close` events

---

packages/web-vue/components/dropdown/README.en-US.md
packages/web-vue/components/dropdown/README.zh-CN.md
packages/web-vue/components/dropdown/dropdown-button.vue
packages/web-vue/components/dropdown/dropdown.vue

|      dropdown     |   添加hide-on-select属性            |     add hide-on-select props          |       Close #2066          |

feat(dropdown): add hide-on-select props

---

packages/web-vue/components/notification/__demo__/update_duration.md
packages/web-vue/components/notification/__demo__/update_notification.md
packages/web-vue/components/notification/notification-list.tsx

|   notification   |   修复更新 duration 失效的问题    |    Fix the problem that the update duration fails  |  Close #2085  |

fix(notification): fix update problem

---

packages/web-vue/components/auto-complete/auto-complete.tsx
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/components/menu/base-menu.vue
packages/web-vue/components/time-picker/time-picker.vue

|  common    | 更新部分组件 `triggerProps` 的类型               |Update the type of `triggerProps` for some components         |                |

enhance: update the triggerProps types of some components

---

packages/web-vue/components/select/hooks/use-select.ts
packages/web-vue/components/select/select.tsx

|   select   |  新增 `defaultActiveFirstOption` 属性 |  Added `defaultActiveFirstOption` property   |  Close #2084   |

feat(select): add defaultActiveFirstOption prop

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md

|     table    |         修复checkStrictly 属性的默认值在文档中显示错误       |       fixed the checkStrictly prop default in README         |   Close #2133            |

fix(docs): fixed the checkStrictly prop default in README

---

packages/web-vue/components/_utils/date.ts
packages/web-vue/components/_utils/is.ts

dayjs并不支持把格式"2024-Q3"的字符串解析成date，导致"2024-Q3"会被转换成2024-01-01的date
|     date-picker      |         修复因dayjs不支持季度解析导致返回错误的问题      |       Fix the problem that an error is returned because dayjs does not support quarter parsing       |       Close #2057        |

fix(DatePicker): 修复因dayjs不支持季度解析导致返回错误的date #2057

---

packages/web-vue/components/form/form-item.vue

|      form     |       修复 FormItem 的 validateStatus 失效问题     |      Fix invalidation of validateStatus of FormItem       |        
Close #2157         |

fix(form):  in formItem, isError uses props.validateStatus first

---

packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/index.ts
packages/web-vue/components/drawer/interface.ts
packages/web-vue/components/modal/README.en-US.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/index.tsx
packages/web-vue/components/modal/interface.ts

| Modal | 添加函数调用的更新方法 | add update method of function call |                |
| Drawer | 添加函数调用的更新方法 | add update method of function call |                |

enhance(modal): add update method of function call

---

packages/web-vue/components/checkbox/style/index.less

|      checkbox     |         修复复选框在取消选择时会保留悬停样式的问题      |      Fixed checkbox retaining hover style when deselected  |      Close  #2123        |

fix(checkbox):  remove the hover style in the checkbox focus state

---

packages/arco-vue-docs-navbar/src/index.tsx
packages/arco-vue-docs/utils/login.ts

chore: update common api endpoints

---

packages/web-vue/components/list/list.tsx

|     list      |       列表支持后端数据分页        |        list supports backend data pagination       |        #2193        |
采用和table的逻辑一致， 只有`data.length` > `pageSize.value` 才会进行 `slice`
https://github.com/arco-design/arco-design-vue/blob/fb587bd00660709679fea72a2e3406e60f1a193d/packages/web-vue/components/table/table.tsx#L1050-L1058

fix(list): list supports backend data pagination

---

packages/web-vue/components/input/input.tsx

给input设置`maxLength`后，输入内容达到最大值时，选择输入内容在键盘为英文状态下（`Composition`）无法触发内容更改。(`updateValue`)。
场景：  
- 双击内容
- 鼠标选择字符串
- 快捷键全选
在最近一次PR https://github.com/arco-design/arco-design-vue/pull/1942 修改中作者为了wordLength能够生效，将原本的判断逻辑的与逻辑运算符改为或逻辑运算符。导致了非输入法输入（isComposition.value = false）时，最大值情况与运算会直接判为ture。
1. 改回或运算并将长度取值`computedValue`改为`valueLength`确保`wordLength`功能正常。此方案也在 https://github.com/arco-design/arco-design-vue/issues/1926#issuecomment-1345919717 中提到。
3. 原本wordLength必须配合wordSlice使用才能正常截取字符串，现在内部增加defaultMaxLength调用wordLength推算出默认的截取长度。
|      input     |  修复达到最大值后非输入法状态下无法修改内容问题   |  fix issue with content modification at maximum value using non-input method |       #2183 …

fix(input): adjust maxLength checking mechanism

---

packages/web-vue/components/form/form-item.vue
packages/web-vue/components/locale/index.ts
packages/web-vue/components/locale/interface.ts
packages/web-vue/components/locale/lang/en-us.ts
packages/web-vue/components/locale/lang/ja-jp.ts
packages/web-vue/components/locale/lang/zh-cn.ts
packages/web-vue/components/locale/lang/zh-tw.ts
packages/web-vue/package.json
yarn.lock

|   form    |   增加中文检验信息  |   Add Chinese inspection information   |  Close #2131  |

enhance(form): add i18n validate message

---

packages/arco-vue-docs/docs/i18n.en-US.md
packages/arco-vue-docs/docs/i18n.zh-CN.md
packages/web-vue/components/config-provider/__demo__/basic.md
packages/web-vue/components/locale/lang/vi-VN.ts

|     Common      |       国际化支持设置越南语        |      Internationalization support set Vietnamese.        |      Close #2221        |

feat(i18n): locale support vi-vN

---

packages/web-vue/components/_utils/get-value-by-path.ts
packages/web-vue/components/form/__demo__/dynamic.md

|   form   |    修复 field 属性中对数组格式不支持的问题   |   Fix the problem that the array format is not supported in the field attribute  |                |

fix(form): fix field array problem

---

packages/web-vue/components/slider/__demo__/range.md
packages/web-vue/components/slider/slider.vue

|  slider |  修复在 range 模式下 model-value 绑定错误的问题  |  Fix the problem of model-value binding error in range mode   |                |

fix(slider): fix default value problem

---

packages/web-vue/components/calendar/style/index.less

1. 日期为今日的date-circle中文本没有垂直居中显示，存在1px的偏移。原因在于css类arco-calendar-cell-today会将其下方date-circle的box-sizing属性设置为border-box，这导致date-circle的内容高度与行高不匹配，从而使字体产生偏移。
2. 日期为今日的date-circle和其他日期的date-circle选中后大小不一致,这是因为两种date-circle的box-sizing不一致引起的
1.使用flexbox进行文本的居中
2.date-circle在选中后将box-sizing设为border-box
|calendar           |修复一些样式问题               |fix some style problems               |                |

fix(calendar): fix some style problems

---

packages/web-vue/components/tree/tree.vue

Emitting `update:selectedKeys` before the `select` results in a lack of control over the number of selected nodes.
| Tree | 调整 select 和 update:selectedKeys, check 和 update:checkedKeys 的触发顺序 | adjust the emit order of select and update:selectedKeys, check and update:checkedKeys | Close #2227 |

fix(tree): change the order of select and check emit

---

packages/arco-vue-docs/docs/i18n.en-US.md
packages/arco-vue-docs/docs/i18n.zh-CN.md
packages/web-vue/components/locale/lang/km-kh.ts
packages/web-vue/components/locale/lang/vi-vn.ts

增加越南语`vi-VN` 、高棉语(柬埔寨)`km-KH`语言文件。修改官方文档中语言支持列表、并补上遗漏的阿拉伯语（埃及）`ar-EG`支持描述。
这两个语言文件使用了较为权威的语言资源和多个翻译工具进行翻译对照。同时还参考了相应语言的国际化标准和市面上流行的组件库，以确保国际化文件符合语言的规范和当地的习惯用法。
|  common   |   新增越南语`vi-VN`  |   Added Vietnamese (vi-VN)  languages        |         |
|  common   |   新增高棉语(柬埔寨) `km-KH`  |   Added Khmer(Cambodia) (km-KH) languages    |            |

feat(locale): add Vietnamese and Khmer (Cambodian) language support

---

packages/web-vue/components/_components/virtual-list-v2/interface.ts

type中定义了height不是可选，导致不传height时IDE出现提醒
|    common      |       修正虚拟列表 ts 定义问题       |      Fix virtual list ts definition problem        |                |

enhance(virtual-list-v2): optimize type

---

packages/web-vue/components/upload/upload.tsx

beforeUpload的类型定义与文档说法不符
|upload           |允许beforeUpload返回布尔值               |beforeUpload allows to return a boolean value               |                |

enhance(upload): beforeUpload allows to return a boolean value

---

packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/dropdown/dropdown-button.vue
packages/web-vue/components/input/input-search.tsx
packages/web-vue/components/modal/interface.ts
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/popconfirm/popconfirm.vue

|  Changelog(CN) | Changelog(EN) | Related issues |
| ------------- | ------------- | -------------- |
|更新一些组件的的buttonProps类型                |update the buttonProps types of some components               |                |

enhance: update the buttonProps types of some components

---

packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/package.json

|  date-picker |   修复年份范围选择器存在的问题   |   Fix bugs with year range selector |    Close #2229   |
|  common |   组件包增加 `type='module'` 标识，解决 nuxt3 下解析为 CommonJS 的问题   |   The component package adds the `type='module'` flag to solve the problem of parsing to CommonJS under nuxt3  |      |

fix(datepicker): fix year range problem

---

packages/web-vue/components/select/hooks/use-options.ts

Fix #2263
Use computed `sortedSlotOptionInfos` in select/hooks/use-options.ts and watch the computed to ensure correct reactivity dependency, thus to correctly update `optionInfoMap` and `validOptionInfos`.
| Select          | 修复动态 slot options 导致 dropdown 为空的问题              | fix blank dropdown caused by dynamic slot options              |  Close #2263              |

fix(select): fix select slot options

---

packages/web-vue/components/trigger/utils.ts

原来的代码逻辑仅仅通过获取 HTML 元素的可见宽度或者窗口的可视区域来决定视图高宽。
通过window.top来取最顶层窗口的引用，在计算文档高宽时通过比较 `body`、`html` 的几个属性值中的值来获得最大值，从而获得最准确的文档高度和宽度，包括内容和滚动条等部分。
参考自 `popperjs` [getDocumentRect](https://github.com/floating-ui/floating-ui/blob/65758fd8d32e034c45cf4126b43861536b6354b4/packages/dom/src/utils/getDocumentRect.ts#L22)的处理方式。
|  trigger   |   优化弹出位置在 ShadowRoot 中不准确问题   |    Optimize the problem that the popup position is not accurate in ShadowRoot  |    Close #2252     |
微应用时需要保证子应用拥有自己的准确位置，可以将子应用`body`的`position`设置为 `relative`、`absolute`、`fixed`

fix(trigger): Support position calculation within Shadow DOM.

---

packages/web-vue/components/select/select.tsx

…et to modelValue
|         select  |    modelValue设置 undefined 或者 null, _value 设置成modelValue   |       when modelValue is set to undefined or null, _value is set to modelValue          |          #2280      |
`_value.value` 不需要 和`modelValue`保持一致吗？

fix(select): sync _value and modelValue

---

packages/web-vue/components/upload/upload-list-item.tsx

The parameter transferred in `extra-button` slot is inconsistent with documentation
Adjust slot parameter according to documentation
|     Upload      |      调整 extra-button 插槽参数         |       modify parameter transferred in extra-button slot        |                |

fix(upload): fix slot parameter problem

---

packages/web-vue/components/list/list.tsx

|   list |   修复向上滚动时可能触发 reach-bottom 的问题  | Fix an issue that may trigger reach-bottom when scrolling up   |    Close #2283            |

fix(list): fix reach problem

---

packages/web-vue/components/transfer/style/index.less
packages/web-vue/components/transfer/transfer-view.vue

|    Transfer       | 修复 title 部分 ellipsis 失效               |Fix title ellipsis failure               |     Close #1558          |

fix(Transfer): 修复 title 中内容 ellipsis 失效

---

packages/web-vue/components/trigger/utils.ts

|  trigger   |   修复在 iframe 中报错的问题  |  Fix the problem of reporting errors in iframe  |    Close #2298             |

fix(trigger): add try-catch

---

packages/web-vue/components/transfer/README.en-US.md
packages/web-vue/components/transfer/README.zh-CN.md
packages/web-vue/components/transfer/TEMPLATE.md
packages/web-vue/components/transfer/__demo__/custom-header.md
packages/web-vue/components/transfer/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/transfer/transfer-view.vue
packages/web-vue/components/transfer/transfer.vue

为transfer 组件添加了自定义标题栏的功能
|      Transfer     |  添加自定义标题栏插槽    |   add custom header slots             |   Close #1557              |

feat(Transfer): add custom-header for transfer

---

packages/web-vue/components/switch/switch.vue

|     Switch      |      新增文案显示props         |        add text props       |                |

feat(switch): 开关新增checkedText、uncheckedText

---

packages/web-vue/components/date-picker/README.en-US.md
packages/web-vue/components/date-picker/README.zh-CN.md
packages/web-vue/components/date-picker/interface.ts
packages/web-vue/components/date-picker/panels/month/index.vue
packages/web-vue/components/date-picker/picker-panel.vue
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker-panel.vue
packages/web-vue/components/date-picker/range-picker.vue

常见的组件库中对日期选择器中的月份显示都采用简写形式，以保证样式的稳定性。
例：[Ant Design](https://ant.design/components/date-picker)、[Element](https://cn.element-plus.org/zh-CN/component/date-picker.html)...
增加 `abbreviation` 属性用于控制月份名称是否启用缩写。默认为 `true` 开启简写。
| date-picker | 增加 abbreviation 属性，控制月份是否显示简称 |Add the abbreviation property to control whether the abbreviation of the month is displayed | Close #2262  |

feat(date-picker): add property abbreviation

---

packages/web-vue/components/tree/base-node.vue

|      tree     |           树节点增加 data-level 和 data-key 数据属性    |      add data-level and data-key attributes to tree nodes           |         Close #2191      |

feat(tree): add data-level and data-key attributes to tree nodes

---

packages/web-vue/components/tabs/tab-pane.vue

tab-pane的title在tabs key 未做变更的情况下，插槽无法根据数据的变化及时渲染
tabs-pane onUpdated 的时候重新把新的slots 赋值给 data
|    Tabs       |    修复个别情况下tab-pane 的title 插槽不更新的问题           |      fixed individual cases where tab slots are not updated         |       Close #1078         |

fix: fixed individual cases where tab slots are not updated

---

packages/web-vue/components/image/image.vue

修复image组件宽度高度动态值没有传递的问题
|      image    |       修复 `sizeStyle` 失效的问题        |      Fix `sizeStyle` failure issue       |                |

fix: 修复写法问题导致sizeStyle没有传递的问题

---

packages/web-vue/components/cascader/style/index.less

| Cascader | 修复控件宽度较短时，搜索结果展示异常 | Fix the abnormal display of search results when the width of the control is short | Close #2324 |

fix(cascader): 修复搜索结果展示异常(#2324)

---

packages/web-vue/components/table/style/index.less

|  table  |  修复虚拟列表下显示横向滚动条的问题   |  Fix the problem of displaying the horizontal scroll bar under the virtual list   |    Close #2334  |

fix(table): fix virtual style problem

---

packages/web-vue/components/modal/interface.ts

`ModalConfig` 的这些默认值和 `Modal`的 `props` 保持一致
|      modal     |       modal文档中ModalConfig的默认值        |    The default value of ModalConfig in the modal document           |           Close #2344     |

docs(modal): modal文档中ModalConfig的默认值

---

packages/web-vue/components/select/hooks/use-select.ts

|   select  |   修复输入法状态下 Enter 键会触发选择的问题   |   Fix the problem that the Enter key in the input method state will trigger the selection   |                |

fix(select): fix enter problem

---

packages/web-vue/components/checkbox/checkbox.tsx

fix issure: #2372
- CheckBox value 设置为boolean类型后控制台报警告
CheckBox value 设置为boolean类型后控制台报警告
type中支持boolean类型
给checkbox的value属性设置boolean类型数据，例如：true，浏览器打开控制台
|   checkbox        |      修复 `value` 属性使用 boolean 值出现 ts 错误的问题         |    Fix the ts error problem when the `value` attribute uses a boolean value  |    Close #2372           |

fix(CheckBox): value 设置为boolean类型后控制台报警告 #2372

---

packages/web-vue/components/image/preview-group.vue

|   image-preview |  添加 actions 插槽    |  add actions slot    |   Close #2388     |

feat(image-preview-group): add actions slot

---

packages/web-vue/components/cascader/cascader.vue

|     cascader      |      非严格模式下支持全路径搜索         |      support full path search         |        #2328         |

feat(cascader): support full path search

---

packages/web-vue/components/_components/input-label/input-label.tsx

|  select  |  选择框增加 title 提示  |   Add a title hint to the selection box  |                |

enhance: single input add title

---

packages/web-vue/components/config-provider/config-provider.vue
packages/web-vue/components/config-provider/context.ts
packages/web-vue/components/trigger/trigger.tsx

|   trigger  |   增加 scrollToClose 属性  |    add scrollToClose prop           |    Close #2395            |

feat(trigger): add scrollToClose

---

packages/web-vue/components/divider/divider.tsx

|      divider     |     修复 margin 无法设置为 0 的问题       |      Fix the problem that margin cannot be set to 0       |                |

fix: 修复divider的margin无法设置为0的问题

---

packages/web-vue/components/date-picker/pickers/date-picker.tsx

add missing props to datePicker component
|      DatePicker     |     日期选择器          |    DatePicker                |                |

fix(date-picker): fix missing props declear

---

packages/web-vue/components/radio/__demo__/options.md
packages/web-vue/components/select/TEMPLATE.md

docs: update

---

packages/web-vue/components/drawer/interface.ts
packages/web-vue/components/modal/interface.ts

|  Drawer & Modal         |      修复函数调用形式ts报错         |         fix onOk & onCancel type error in function call      |                |

fix(drawer & modal ): fix onOk & onCancel type error in function call

---

packages/web-vue/components/date-picker/hooks/use-range-header-value.ts

|   date-picker       |    修复日期范围选择器年、月、季度模式的箭头显示逻辑          |      fixed arrow display logic for year, month, and quarter modes in the date range picker         |        #2450         |

fix(date-picker): fixed calculation logic for HeaderOperations

---

packages/web-vue/components/modal/hooks/use-draggable.ts
packages/web-vue/components/modal/modal.vue

|   modal        |      修复定义了top属性时拖拽错误         |      fix modal drag error when define top prop         |     Close #2438           |

fix(modal): fix modal drag error when define top prop

---

packages/web-vue/components/modal/modal.vue

|    modal       |    修复同时设置 `width` 和 `fullscreen` 时，没有全屏的问题     |    Fix the problem that there is no full screen when `width` and `fullscreen` are set at the same time     |        Close  #2440        | 

fix(modal): add width attribute, fullscreen width become invalid.

---

packages/web-vue/components/modal/hooks/use-draggable.ts

修复PR：#2446 遗留的问题
|    modal       |       修复modal拖拽时定义了top属性导致顶部边界错误        |      fix modal drag error when drag to top edge         |                |

fix(modal): fix modal drag error when drag to top edge

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/table.tsx

表格在实际应用中常常需要使用双击和右击事件来提升用户体验和操作效率。组件提供出相关的事件开发者能够轻松地为表格添加这些交互功能。
增加：
- `row-dblclick`：双击行事件
-  `cell-dblclick`：双击单元格事件
-  `row-contextmenu`：右击行事件
-  `cell-contextmenu`：右击单元格事件
实现上也可以用函数柯里化的方式让代码更少一些：
``` ts
const handleRowEvent = (eventName: any) => (record: TableDataWithRaw, ev: Event) => {
emit(eventName, record.raw, ev);
};
const handleRowClick = handleRowEvent('rowClick');
const handleRowDblclick = handleRowEvent('rowDblclick');
const handleRowContextMenu = handleRowEvent('rowContextmenu');
```
|     table      |     增加表格右击、双击的相关事件   |    Add table right-click and double-click events           |     #2381 #2449 #2140 #1316    |
should be submitted to `main` …

feat(table): enhance table event handling

---

packages/web-vue/components/modal/modal.vue

|    modal       | 修复modal组件不能设置width属性的问题              |   fix can not set width attribute           |    Close #2459       |

fix(modal): can not set width attribute

---

packages/web-vue/components/cascader/base-cascader-panel.tsx
packages/web-vue/components/cascader/cascader-search-panel.tsx
packages/web-vue/components/config-provider/__demo__/empty.md
packages/web-vue/components/config-provider/config-provider.vue
packages/web-vue/components/empty/empty.tsx
packages/web-vue/components/list/list.tsx
packages/web-vue/components/select/select-dropdown.vue
packages/web-vue/components/table/table.tsx
packages/web-vue/components/tree-select/tree-select.vue

|      ConfigProvider     |        empty slots 增加component 属性       |         empty slots add component attribute      |    Close  #2405           |

feat(config-provider): empty slots add component attribute

---

packages/web-vue/components/modal/README.en-US.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/__demo__/confirm.md
packages/web-vue/components/modal/index.tsx

https://github.com/arco-design/arco-design-vue/issues/2435
|  Modal         |    修复Modal.confirm标题缺少warning icon的问题           |     fix modal confirm missing warning icon in the title          |    Close #2435      |

fix(modal): fix modal confirm missing warning icon in the title

---

packages/web-vue/components/input-number/README.en-US.md
packages/web-vue/components/input-number/README.zh-CN.md
packages/web-vue/components/input-number/input-number.tsx

`hide-button` should take effect under any circumstances.
隐藏按钮应该在任何情况下生效。
Sorry, I haven't test it yet because of some CI bugs.
由于一些命令无法运行，暂时无法测试（辛苦 maintainers）
| input-number | `hide-button` 在 `mode="button"` 时也会生效 | `hide-button` also takes effect when `mode="button"` | |

feat(number-input): ignoring mode when hide button

---

packages/web-vue/components/config-provider/TEMPLATE.md
packages/web-vue/components/empty/empty.tsx

|   empty   |   增加 `in-config-provider` 属性  |   Add `in-config-provider` property      |                |

feat(empty): add new prop

---

packages/web-vue/components/calendar/calendar.tsx

chore: Update calendar.tsx console.log in prod

chore: Update calendar.tsx console.log in prod

---

packages/web-vue/components/_components/input-label/style/input-label.less

|   select   |   修复搜索模式下鼠标光标定位问题  |  Fix mouse cursor positioning issue in search mode   |                |

fix(select): fix search pointer problem

---

packages/web-vue/components/tree-select/tree-select.vue
packages/web-vue/components/tree/tree.vue

|  tree-select  |   修复在虚拟列表下搜索内容不可选择的问题   |    Fix the problem that the search content under the virtual list cannot be selected    |   Close #2482    |

fix(select-tree): fix search problem

---

packages/web-vue/components/arco-vue.ts

对比 index.ts 发现一个拼写错误和一个遗漏导出
修正即可

fix: Alter typo, and missing export ImagePreviewAction in arco-vue.ts

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/table.tsx

有些业务场景需要判断单元格是够鼠标移入移出，虽然用`slot`也可以做到，但是判断通过判断是哪些字段的单元格移入移出赋给不同的颜色更方便
给单元格增加鼠标移入移出事件
|    Table   |         单元格新增鼠标移入移出事件      |      Added mouse in and out events for cells       |               |

feat(table): add mouse hover events to cells

---

packages/web-vue/components/arco-vue.ts
packages/web-vue/components/select/README.en-US.md
packages/web-vue/components/select/README.zh-CN.md
packages/web-vue/components/select/TEMPLATE.md
packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/base-node.vue
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/node-switcher.vue

doc: fix select doc problem

---

packages/web-vue/components/config-provider/config-provider.vue
packages/web-vue/components/config-provider/context.ts
packages/web-vue/components/date-picker/range-picker.vue

|   ConfigProvider   |  增加 `exchangeTime` 属性   |   Add `exchangeTime` property   |  Close #2517  |

feat(config-provider): add exchangeTime

---

packages/web-vue/components/table/hooks/use-span.ts
packages/web-vue/components/table/table.tsx

|       table    |          修复子树的合并单元格的bug     |    fix the bug of merging cells in subtrees |          #2539       |
这里为了保持唯一性，所以和`key`保持了关联。
也可以展平data渲染，而不是嵌套渲染，这样`rowIndex`和 `columnIndex`才是唯一

fix(table):  fix the bug of merging cells in subtrees

---

packages/web-vue/components/image/image.vue

|      Image     |        在错误状态下，没有 alt 或description情况图标不居中       |       icon not centered without alt or description in error state        |          Close  #1934    |

fix(image): icon not centered without alt or description in error state

---

packages/web-vue/components/image/image.vue

|       Image    |       在错误状态下，没有 alt 或description情况图标不垂直居中        |       icon not centered without alt or description in error state        |          https://github.com/arco-design/arco-design-vue/issues/1934      |

fix: icon not centered without alt or description in error state

---

packages/web-vue/components/tree-select/__demo__/dropdown-slots.md
packages/web-vue/components/tree-select/interface.ts
packages/web-vue/components/tree-select/tree-select.vue

#2429 
与下拉框组件更新保持一致，增加对空状态下`页头` `页脚`插槽的显示控制
|  tree-select   |   增加空状态下 header 和 footer 的显示状态     |      Add header and footer visibility in empty data state      |                |

feat(tree-select): header and footer visibility in empty data state

---

packages/web-vue/components/table/table.tsx

pass .raw to rowClass, 跟文档和 renderSummaryRow 一样保持一致 (#2553)
|  table   |   修复 rowClass 函数 record 参数错误的问题   |   Fix the wrong parameter of rowClass function record   |   Close #2553    |

fix(Table): pass .raw to rowClass, 跟文档和 renderSummaryRow 一样保持一致 (#2553)

---

packages/arco-vue-docs/docs/pro/state-management-pinia.en-US.md
packages/arco-vue-docs/docs/pro/state-management-pinia.zh-CN.md
yarn.lock

docs: fix errors in the pinia example in Arco Pro

---

packages/web-vue/components/cascader/README.en-US.md
packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/TEMPLATE.md
packages/web-vue/components/cascader/__demo__/virtual.md
packages/web-vue/components/cascader/base-cascader-panel.tsx
packages/web-vue/components/cascader/cascader-column.tsx
packages/web-vue/components/cascader/cascader.vue

|  cascader   |    增加虚拟列表功能   |  Add virtual list support  |    Close #2562      |

feat(cascader): add virtual list support

---

packages/web-vue/components/tree-select/tree-select.vue

修复 `tree-select` 错误的 `border` 属性，因为 `select-view` 接收的属性是 `bordered`
border 替换为 bordered
see https://github.com/arco-design/arco-design-vue/blob/main/packages/web-vue/components/_components/select-view/select-view.tsx#L47
|  tree-select   |   border 替换为 bordered   |  replace border with bordered    |                |

fix(tree-select): replace border with bordered

---

packages/web-vue/components/result/500.tsx

|  result   |  修复 500 图片错位问题   |    Fix 500 image misalignment issues    |                |

fix(result): fix 500 image problem

---

packages/web-vue/components/list/README.en-US.md
packages/web-vue/components/list/README.zh-CN.md
packages/web-vue/components/list/list.tsx

支持列表的最大高度maxHeight传字符串形式，例如传动态计算高度 max-height="calc(100vh - 500px)"‘
|     list      |         滚动最大高度支持字符串类型      |          Scroll maxHeight supports string type         |            |

feat(list): Scroll maxHeight supports string type

---

packages/web-vue/components/tree-select/tree-select.vue

|  tree-select  |    修复 `border` 属性默认值错误的问题   |  Fix the problem that the default value of the `border` attribute is wrong   |                |

fix(tree-select): fix border problem

---

packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table.tsx
packages/web-vue/components/table/utils.ts

|  table  |    修复在固定列中开启调整列宽出现的问题    |    Fix the problem of turning on the adjustment of column width in the fixed column  |                |

fix(table): fix fixed resize problem

---

packages/web-vue/components/auto-complete/README.en-US.md
packages/web-vue/components/auto-complete/README.zh-CN.md
packages/web-vue/components/auto-complete/__demo__/virtual-list.md
packages/web-vue/components/auto-complete/auto-complete.tsx

| auto-complete  | 添加虚拟列表支持 | add virtual list support  | Close  #2595    |

feat(auto-complete): add virtual list support

---

packages/web-vue/components/components.ts

|     image-preview-action     |    添加 ImagePreviewAction 类型声明         |    added  image-preview-action type definition        |                |

feat: added image-preview-action type definition

---

packages/web-vue/components/image/README.en-US.md
packages/web-vue/components/image/README.zh-CN.md
packages/web-vue/components/image/TEMPLATE.md
packages/web-vue/components/image/image.vue
packages/web-vue/components/image/interface.ts
packages/web-vue/components/image/preview-toolbar.vue
packages/web-vue/components/image/preview.vue
packages/web-vue/components/image/utils/get-scale.ts

https://github.com/arco-design/arco-design-vue/issues/2165#issuecomment-1488455279
#1542 
#1253 
#1428
1. 新增键盘快捷控制
2. 新增滚轮缩放操作
3. 增加默认展示大小比例
- 支持popup-container 自定义挂载下的操作
- 支持有多个esc事件情况：如modal 和 image-preview 同时展示时按下会根据聚焦情况先关闭图片预览
|   ImagePreview      |  支持键盘快捷、鼠标滚轮操作等一系列功能  |  Support keyboard shortcuts, mouse wheel operation and a series of functions       | Close #1428 , Close #1542 , Close #1253 , Close #2165   |

feat: enhance image preview

---

packages/web-vue/components/arco-vue.ts

| Type| Component | Changelog(CN) | Changelog(EN) | Related issues |
| Bug fix |   common   |   修复全局引入时提示重复注册的问题   |  Fix the problem of prompting for repeated registration when importing globally    |                |
| Breaking change |   common   |  修正 `Alter` 为 `Alert`   |  Fix `Alter` to `Alert`   |                |

fix: fix install problem

---

packages/web-vue/components/grid/__demo__/grid.md
packages/web-vue/components/transfer/README.en-US.md
packages/web-vue/components/transfer/README.zh-CN.md
packages/web-vue/components/transfer/__demo__/search.md
packages/web-vue/components/transfer/transfer-view.vue
packages/web-vue/components/transfer/transfer.vue
packages/web-vue/components/trigger/README.en-US.md
packages/web-vue/components/trigger/README.zh-CN.md
packages/web-vue/components/trigger/TEMPLATE.md

|  transfer |    增加搜索框的配置属性    |   Increase the configuration properties of the search box  |    Close #2655   |

feat(transfer): add input-search props

---

.gitattributes

在windows下，提交到git暂存区时，lf文件会被强制转为crlf

chore(gitattributes): fix lf convert to crlf

---

packages/web-vue/components/input-number/input-number.tsx

|   input-number  |   优化步长按钮的长按效果    |    Optimize the long-press effect of the step button |   Close #2657    |

enhance(input-number): enhance step button

---

packages/web-vue/components/_components/virtual-list-v2/virtual-list.vue

|       virtual-list    |       修复虚拟滚动 scrollTop 位置不对        |         fix the wrong scrolling position of the virtual list      |  #2481              |
看起来是`start` 发生修改时候，删除dom元素时候，同步一下 scrollTop

fix(virtual-list): fix the wrong scrolling position of the virtual list

---

packages/web-vue/components/form/README.en-US.md
packages/web-vue/components/form/README.zh-CN.md
packages/web-vue/components/form/TEMPLATE.md
packages/web-vue/components/form/__demo__/scroll.md
packages/web-vue/components/form/context.ts
packages/web-vue/components/form/form-item.vue
packages/web-vue/components/form/form.vue

#2627 
增加验证失败后滚动到第一个错误字段 `scroll-to-first-error `
增加表单滚动到指定字段方法 `scrollToField `
|     form     |    新增滚动到指定表单字段      |     add scroll into view to the field          |    Close  #2627       |
https://github.com/arco-design/arco-design-vue/assets/48879481/3ed8b868-005e-463b-b381-c319a0d28e7a

feat: add scroll into view to the field

---

packages/web-vue/components/typography/style/index.ts

|   typography  |  修复按需导入时缺少相关组件样式的问题   |    Fix the problem of missing related component styles when importing on demand  |   Close #2676   |

fix(typography): fix style problem

---

packages/web-vue/components/cascader/cascader-column.tsx

开启虚拟列表时空数据不显示空状态 #2684 
📌  为保持不影响以前的dom层级结构添加了外层。实际不加外层（或直接用div包裹）也许会更好看。
加（与以前保持一致）：
未添加（居中）：
|    cascader       |   修复开启虚拟列表时空状态不显示            |     fix empty state in Cascader Virtual list          |    #2684             |

fix(cascader): fix empty state in Cascader Virtual list

---

packages/web-vue/components/avatar/README.en-US.md
packages/web-vue/components/avatar/README.zh-CN.md
packages/web-vue/components/avatar/avatar.vue
packages/web-vue/components/avatar/interface.ts

This PR adds a new ObjectFit prop to the Avatar component. This allows users to specify how the image should fit within the container, providing more flexibility in how Avatars are displayed.
Added an ObjectFit prop to the Avatar component and implemented the necessary changes in the component's rendering logic to apply the CSS object-fit property based on the prop value.
Unit tests were updated to include tests for the new ObjectFit prop. All tests are passing (`npm run test`).
|     Avatar      |       添加了新的 `ObjectFit` 属性        |     Added new `ObjectFit` prop          |     Close #2376           |
No breaking changes …

feat(avatar): add object-fit

---

packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input/input.tsx

|  input-number   |  增加 `input-attrs` 属性  |   Add `input-attrs` attribute   |                |

feat(input-number): add input-attrs

---

packages/web-vue/components/date-picker/hooks/use-range-header-value.ts

日期范围选择器在切换年、月面板时操作箭头的显示逻辑不正常。#2709
https://github.com/arco-design/arco-design-vue/assets/48879481/2c51c765-e886-4318-a68c-1b744b7dad35
修复后表现：
https://github.com/arco-design/arco-design-vue/assets/48879481/b6a242a7-9d27-4aad-b1f0-774119d465ca
|    date-picker     |    修复范围选择器操作箭头显示错误问题           |    fix incorrect display of operations in range selector           |   Close  #2709           |

fix(date-picker): incorrect display of operations in range selector

---

packages/web-vue/components/switch/switch.vue

|   switch   |   优化对 `undefined` 和 `null` 值的处理  |   Optimize handling of `undefined` and `null` values    |  Close #2736  |

enhance(switch): enhance undefined value

---

packages/web-vue/components/mention/mention.tsx

This PR addresses the issue where the `disabled` attribute does not function as expected when used with the Mention component under a text-area.
#2721 
prop disabled in mention.tsx
| Mention   | 修复在text-area下disabled属性无法正常工作的问题 | Fixed the issue where the `disabled` attribute does not work properly under text-area | Close #2721 |
- [ x] Test suite passes (`npm run test`)
- [ x] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ x] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others

fix(Mention): Fix disabled attribute under text-area

---

packages/web-vue/components/calendar/README.en-US.md
packages/web-vue/components/calendar/README.zh-CN.md
packages/web-vue/components/calendar/calendar.tsx
packages/web-vue/components/calendar/header.tsx
packages/web-vue/components/calendar/month.tsx

This PR introduces two new slots to the Calendar component:
- A header slot for custom header content.
- A default slot for rendering custom content in each date cell.
The addition of these slots increases the flexibility and customization options for the Calendar component.
Added two slots to the Calendar component:
- header slot: Allows users to customize the header section of the calendar.
- Default slot: Allows users to provide custom content to be rendered in each date cell.
- These slots are optional and do not break existing functionality.
Manually tested to ensure that the slots work as expected.
|     Calendar      |     新增 `header` 和 `default` 插槽        | …

feat(calendar): add slots

---

packages/arco-vue-docs/locale/en-us.js
packages/arco-vue-docs/locale/zh-cn.js
packages/arco-vue-docs/router.ts
packages/web-vue/components/arco-vue.ts
packages/web-vue/components/watermark/CHANGELOG.md
packages/web-vue/components/watermark/CHANGELOG.zh-CN.md
packages/web-vue/components/watermark/README.en-US.md
packages/web-vue/components/watermark/README.zh-CN.md
packages/web-vue/components/watermark/TEMPLATE.md
packages/web-vue/components/watermark/__demo__/basic.md
packages/web-vue/components/watermark/__demo__/custom.md
packages/web-vue/components/watermark/__demo__/image.md
packages/web-vue/components/watermark/__demo__/multiline.md
packages/web-vue/components/watermark/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/watermark/__test__/demo.test.ts
packages/web-vue/components/watermark/hooks/use-mutation-observer.ts
packages/web-vue/components/watermark/index.ts
packages/web-vue/components/watermark/interface.ts
packages/web-vue/components/watermark/utils/index.ts
packages/web-vue/components/watermark/watermark.tsx

**新增水印组件**
**新增水印组件**
- 支持水印防篡改/删除
- 支持高清屏绘制
- 优化canvas绘制性能
- API如下：
**效果预览：**
https://github.com/arco-design/arco-design-vue/assets/48879481/6ab3e858-b704-4c5b-9a09-28da1b52dd3e
项目现有jest没有添加对canvas测试的支持所以没有写具体的`index.test.ts`
|    watermark       |      新增水印组件         |     add watermark component          |   Close #2720, Close #2659         |
- [] Test suite passes (`npm run test`)
- [] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
⚠️：图片Demo缺失arco图片logo链接

feat(watermark): add watermark component

---

packages/web-vue/components/descriptions/__demo__/basic.md
packages/web-vue/components/descriptions/descriptions-item.vue

|  descriptions   |   修复 `DescriptionsItem` 组件 `span` 属性失效的问题  | Fix the problem of invalid `span` attribute of `DescriptionsItem` component |                |

fix(descriptions): fix span problem

---

packages/web-vue/components/components.ts
packages/web-vue/components/index.ts

|   watermark   |    修复组件入口未暴露问题    |    Fix the problem that component entrance is not exposed   |                |

fix(watermark): fix miss entry

---

packages/web-vue/components/_utils/is.ts

fix: fix isObject function return type error

---

packages/web-vue/components/watermark/style/index.ts

|   watermark   |   修复样式按需加载报错问题   |   Fix the problem of error reporting when styles are loaded on demand  |  Close #2786 |

fix(watermark): fix style problem

---

packages/web-vue/components/calendar/README.en-US.md
packages/web-vue/components/calendar/README.zh-CN.md

When I use `calendar` in my project, I noticed that there was no API `dateRender` like the version of React, and there have been a issue about this (#2248), but I found the API was existed in fact, so that's when I realized that it's the problem from docs
Review the result which is rendered by the changed md files
|     calendar      |       补充calendar组件插槽相关的文档信息       |      Add information about the slots of calendar component         |        #2248        |

docs: add information about the slots of calendar component

---

packages/web-vue/components/date-picker/hooks/use-range-header-value.ts

#2851 
#2748 
|   range-picker    |  修复日期范围部分模式下箭头点击问题              |    resolve arrow click issue in range-picker        |   Close #2851 , Close #2748 |

fix(range-picker): resolve arrow click issue in range-picker

---

packages/web-vue/components/pagination/pagination.tsx

翻页器组件的page应该是从1开始的正整数，因为它代表的是当前页码。如果page为0，可能会导致一些错误或者不符合预期的结果，感觉page不应该设置为0把
|        Pagination   |          修复页码可能为 `0` 的问题     |       Fix the problem that the page number may be `0`     |    Close #2827           |

fix(Pagination): Fix the issue with page being 0 

---

packages/web-vue/components/transfer/__demo__/custom-header.md

- [] Test suite passes (`npm run test`)
- [] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others

fix: 修复文档内容异常

---

packages/web-vue/components/form/README.en-US.md
packages/web-vue/components/form/README.zh-CN.md
packages/web-vue/components/form/TEMPLATE.md
packages/web-vue/components/form/__demo__/validation2.md
packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap

添加form组件的使用示例
|      form     |      添加form组件的使用示例         |      Add a usage example of the form component         |                |

docs(form): add component Example

---

packages/web-vue/components/button/button-group.vue
packages/web-vue/components/button/button.vue
packages/web-vue/components/button/interface.ts

类型使用constant文件中导出的常量
|      button     |       TS类型优化        |       TS类型优化        |                |

enhance(button): TS type optimization

---

packages/arco-vue-docs/components/aside-nav/style.less
packages/web-vue/components/cascader/cascader.vue

|    cascader       |   修改 `multiple` 和 `pathMode` 时会触发绑定值的改变   |   Modifying `multiple` and `pathMode` will trigger changes in the binding value   |    Close #2864            |

enhance(cascader): add props watch

---

packages/web-vue/components/input/README.en-US.md
packages/web-vue/components/input/README.zh-CN.md
packages/web-vue/components/input/__demo__/password.md
packages/web-vue/components/input/input-password.vue

与 [react](https://arco.design/vue/component/input) 版对齐, 增加一些用于控制密码输入框密码可见性的属性
https://github.com/arco-design/arco-design-vue/assets/48879481/9bd21d1f-8d8f-4da5-833c-68852319c9c8
|    input-password       |   新增密码框密码可见性相关属性       |   Enhance the input-password props            |                |

feat(input-password): Enhance the input-password props

---

packages/web-vue/components/select/select.tsx

|   select   |   修复 `defaultPopupVisible` 失效的问题   |   Fix `defaultPopupVisible` failure problem   |    Close #2878   |

fix(select): fix default problem

---

packages/web-vue/components/table/hooks/use-span.ts

|  Table   |   修复 `span-method` 在超出行列数后报错的问题   |   Fix the problem of `span-method` reporting an error after exceeding the number of rows and columns    |    Close #2725    |

fix(table): fix span problem

---

packages/web-vue/components/select/option.vue
packages/web-vue/components/select/style/index.less

下拉选择器没有像 [React Select](https://arco.design/react/components/select) 组件那样有选中效果。
样式文件中已经有了相关变量，补上了代码逻辑
|    select       |   下拉选择器添加选中效果           |  enhance selected state style for options             |                |

enhance(select): enhance selected state style for options

---

packages/web-vue/components/input/style/group.less

|   input  |   修复 `Input.Group` 在线性主题下边框重叠的问题   |   Fix the problem of overlapping borders of `Input.Group` under linear theme   |     |

fix(input): fix group style problem

---

packages/web-vue/components/rate/rate.tsx

|   rate   |    修复在`nuxt`中图标元素缺失的问题     |   Fix missing icon elements in `nuxt`    |                |

fix(rate): fix not display in nuxt

---

packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/tree.vue

|      tree     |    修复tree组件部分事件参数缺失文档           |     fix missing event parameters in tree component documentation           |     #2913           |

docs(tree): fix missing event parameters in tree component

---

packages/web-vue/components/watermark/watermark.tsx

Closes #2941
| Component | Changelog(CN)          | Changelog(EN)                       | Related issues |
| --------- | ---------------------- | ----------------------------------- | -------------- |
| watermark | 修复字体颜色不生效问题 | Fix font color does not take effect | Close #2941    |

fix(watermark): fix font color does not take effect

---

packages/web-vue/components/table/table.tsx

与未开启虚拟列表表现一致：
https://github.com/arco-design/arco-design-vue/assets/48879481/32a4fc02-e721-4b6c-bd97-6f20d6cd4e39
|     table    |  修复表格虚拟列表下不显示 empty  问题       |    fix virtual table list not displaying empty state      |   Closes #2946    |

fix(table): fix virtual table list not displaying empty state

---

packages/web-vue/components/menu/interface.ts
packages/web-vue/components/menu/item.tsx
packages/web-vue/components/menu/sub-menu.tsx

在 Vue.js 3.4.18 版的时候增加了 key 保留属性的检查，所以会报警告。相关 commit: https://github.com/vuejs/core/commit/77a804b1d0d6a3f12fb3674cdceb85ebd6481e02
经测试删除 key 的 props 定义可以解决问题。因 key 本身是保留属性，所以不定义功能也是正常的。
| menu       | 修复警告 “Invalid prop name: key is a reserved property.” | Fix warning “Invalid prop name: key is a reserved property.” | Close #2969 |

fix(menu): Fix warning "Invalid prop name: key is a reserved property"

---

packages/web-vue/components/tree/base-node.vue

| :---------: | ------------- | ------------- | :--------------: |
|      tree     |      解决无效的属性名称控制台警告问题         |        resolve invalid property name console warning issue       |        fix #2991         |

fix(tree): key is a reserved property

---

packages/web-vue/components/collapse/README.en-US.md
packages/web-vue/components/collapse/README.zh-CN.md
packages/web-vue/components/collapse/TEMPLATE.md
packages/web-vue/components/collapse/collapse-item.tsx

|     collapse      |   解决 `vue` 保留属性警告            |    resolve reserved property warning           |                |

fix(collapse): resolve reserved property warning

---

packages/web-vue/components/tree-select/tree-select.vue
packages/web-vue/components/tree/base-node.vue
packages/web-vue/components/tree/tree.vue

|    tree-select   |   新增 `input-value` 相关属性   |   Added `input-value` related properties   |                |
|    tree   |   `title` 插槽新增 `title` 参数   |   The `title` slot has a new `title` parameter   |                |

feat: add tree slot data

---

packages/web-vue/components/tabs/style/index.less

hover 时无过渡效果
修正语法错误
|     tabs      |    修复 title 过渡动画效果    |  fix transition animation for tab title  |     Closes #2894    |

fix(tabs): fix transition animation for tab title

---

packages/web-vue/components/trigger/utils.ts

如 #3042 所描述默认的弹出动画方向不对
https://github.com/arco-design/arco-design-vue/assets/48879481/5b0f6f35-0c62-4c63-b885-ea574316ceef
|    trigger    |   修正位置的弹出动画方向     |    fix animation direction for position popup           |   Closes #3042     |

fix(trigger): fix animation direction for position popup

---

packages/web-vue/components/locale/lang/zh-cn.ts

|  color-picker  |    修复文案错误   |   Fix copywriting errors   |                |

fix(color-picker): 修改错别字

---

packages/web-vue/components/upload/__demo__/submit.md

|     upload      |        示例代码异常       |       example code exception        |      fix #3020         |

fix(upload): example code exception

---

packages/web-vue/components/upload/style/index.ts

按需导入没有使用 `图片组件` 时 `上传组件` 样式缺失无法预览
|  upload   |   修复上传组件预览样式引入缺失     |   import missing image styles for upload component            |    Closes #2882            |

fix(upload): import missing image styles for upload component

---

packages/web-vue/components/color-picker/style/index.less
packages/web-vue/components/color-picker/style/token.less

|    color-picker       |  优化颜色控制条背景圆角样式      |  Optimize color control bar background fillet style   |    #3112  |

fix(color-picker): Optimize color control bar background fillet style

---

packages/web-vue/components/color-picker/style/index.ts
packages/web-vue/components/color-picker/style/token.less

引入组件样式 Token 未导入编译失败
|   color-picker        |    修复样式按需导入错误           |  fix color-picker style import             |       Closes #3025          |

fix(color-picker): fix color-picker style import

---

packages/web-vue/components/verification-code/verification-code.tsx

设置了 `formatter` 时粘贴文本没有执行格式化处理
1. 修复粘贴没有执行格式化回调
2. 优化当返回 true 时使用原值，防止格式化返回的值是多个每次只拿一个字符串
|  verification-code     |   修复粘贴时`formatter`未生效   |     fix formatter not being applied during paste          |                |

fix(verification-code): fix formatter not being applied during paste

---

packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/__demo__/resize.md
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table-col-group.vue
packages/web-vue/components/table/table-column.tsx

table 调整列宽的时候，目前是只支持统一最小调整为 40px 的宽度，体验上存在优化的控件
支持每一列都固定设置 minwidth，当不设置该值时，仍然采用之前的方案
|     Table      |     column 增加 minWidth 属性          |     colum added the minWidth attribute          |                |

feat(table): colum added the minWidth attribute

---

packages/web-vue/components/input-number/input-number.tsx

|    input-number   |   增加 'keydown' 事件，可以禁止默认行为   | Added 'keydown' event to disable default behavior   |                |

feat(input-number): add keydown event

---

packages/web-vue/components/time-picker/time-picker.vue

修复time-picker组件 triggerProps 属性未正确透传至 Tarigger 组件问题
使用`v-bind`将`triggerProps` 属性绑定到 `Tarigger`组件上
|      time-picker     |      triggerProps 属性未正确透传问题         |        TriggerProps property not correctly passed through       |                |

fix: 修复time-picker组件 triggerProps 属性未正确透传至 Tarigger 组件的问题

---

packages/web-vue/components/menu/style/index.less

参考 React：arco-design/arco-design#263
|   Menu  |    修复已选中菜单项中的颜色动画过渡效果          |  fix color transition effect in selected menu item |   Close #2394              |

enhance(menu): menu color transition of selected items

---

packages/web-vue/components/color-picker/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/color-picker/color-picker.tsx
packages/web-vue/components/color-picker/control-bar.tsx

选择颜色时出现的抖动问题
色值转换 hsv 时会出现小的误差导致抖动。开启 v-model外部颜色变化重新 setHsv 出现抖动。
| color-picker  | 修复在 v-model 下选择颜色时出现的抖动问题 |  fix shaking issue when selecting color with v-model  |  Closed #3174 |

fix(color-picker): fix shaking issue when selecting color with v-model

---

packages/web-vue/components/_components/select-view/select-view.tsx
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input-tag/style/input-tag.less
packages/web-vue/components/select/select.tsx
packages/web-vue/components/tag/style/index.less
packages/web-vue/components/tag/tag.vue

|   select  |  增加 `tagNowrap` 选项  |    add `tagNowrap` prop   |                |

feat(select): add tag prop

---

packages/web-vue/components/calendar/calendar.tsx

|     calendar      |  修复modes 不生效问题     |  fix  modes not taking effect  |   Close #3229，Close #3014             |

fix(calendar): modes prop error

---

packages/web-vue/components/card/card.tsx

`headerStyle`与`bodyStyle`的类型为普通对象，没有代码提示
|card           |更新headerStyle与bodyStyle的类型               |update the types of headerStyle and bodyStyle               |                |

feat(card): update the types of headerStyle and bodyStyle

---

packages/web-vue/components/image/README.en-US.md
packages/web-vue/components/image/README.zh-CN.md
packages/web-vue/components/image/preview-group.vue

|  image  |  修复图片组件文档中缺失的事件参数  | fix missing event parameters in image component documentation |                Close #3145 |

docs(image): fix missing event parameters in image component documentation

---

packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input-number/style/index.less

在 `mode` 为 `button` 时  设置 `readOnly` 左右按钮依然可以控制数值变化
参考 react 版设计只读禁用按钮效果修复
https://github.com/arco-design/arco-design/blob/5cff5d656de60d763d6b2d7317b8a2b217728d88/components/InputNumber/style/index.less#L158-L163
|  input-number         | 修复左右按钮模式下只读属性不生效问题   | fix readonly not working in button mode |  Closes #3138              |

fix(input-number): fix readonly not working in button mode

---

packages/web-vue/components/rate/__demo__/character.md

fix: fix bug in Rate component doc

---

packages/web-vue/components/slider/slider-button.vue

|  Slider |  修复拖动更改滑块值在移动端无效 |  Fixed Drag change slider value not working on mobile side   |   #3341    |

fix: 修复Slider组件拖拽时，在移动端无效。

---

.github/workflows/issue-remove-inactive.yml

ci(workflows): optimize remove-labels rule and permissions

---

packages/web-vue/components/date-picker/__demo__/shortcuts-position.md

将month修改为了week
请查看更新的 date-picker#shortcuts-position 演示并将语言环境切换为英语以查看正确的行为
|date-picker|docs(date-picker): 修正快捷方式中的时间范围为下周，原文设置的是'month'|docs(date-picker):  Fix the time range in the shortcut to next week, while the original setting was' month '|Documentation change |

docs(date-picker): 修正快捷方式中的时间范围为下周，原文设置的是'month'

---

packages/web-vue/components/table/style/index.less
packages/web-vue/components/table/style/token.less

暗黑模式下固定列的选中项背景样式透明导致内容重叠
|      Table     |   修复暗黑模式下固定列选中背景样式透明 |  Fix fixed column background style issue in dark mode  |   Closes #2671, Closes #3362, Closes #3365   |

fix(table): fix fixed column background style issue in dark mode

---

packages/web-vue/components/tabs/tabs-nav.tsx

#3387、#3389
#3412
|  Tabs  |  解决`wheel`事件监听器性能警告  | resolve `wheel` event listener passive warning |     Closes #3387         |
|  Tabs  |  优化标签页动态增减时内存释放问题  | optimize memory release during tab removal |     Closes #3389        |

fix(tabs): resolve wheel event listener passive warning

---

packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/drawer.vue

| drawer | 增加 bodyClass 和 bodyStyle | Add bodyClass and bodyStyle |                |

feat(drawer): add bodyClass and bodyStyle

---

packages/web-vue/components/input-number/style/index.ts

fix: #3444
The `InputNumber` component uses `ArcoButton` for its step buttons (increase/decrease), but the button styles were not automatically imported. This caused the step buttons to appear unstyled when using the `InputNumber` component.
Added button style import in the `InputNumber` component's style entry file:
```ts
// packages/web-vue/components/input-number/style/index.ts
import '../../button/style';
```
|    InputNumber       |       修复使用 InputNumber 组件时按钮样式未自动导入的问题        |       Fix the issue where button styles are not automatically imported when using InputNumber component        |        #3444        |

fix(input-number): auto import button style in input-number component

---

packages/web-vue/components/avatar/avatar-group.tsx
packages/web-vue/components/avatar/avatar.vue
packages/web-vue/components/avatar/style/index.less
packages/web-vue/components/badge/badge.tsx
packages/web-vue/components/badge/style/index.less
packages/web-vue/components/config-provider/README.en-US.md
packages/web-vue/components/config-provider/README.zh-CN.md
packages/web-vue/components/config-provider/TEMPLATE.md
packages/web-vue/components/config-provider/__demo__/rtl.md
packages/web-vue/components/config-provider/config-provider.vue
packages/web-vue/components/config-provider/context.ts
packages/web-vue/components/space/space.tsx
packages/web-vue/components/space/style/index.less
packages/web-vue/components/tabs/style/index.less
packages/web-vue/components/tabs/style/rtl.less
packages/web-vue/components/tabs/tabs-button.tsx
packages/web-vue/components/tabs/tabs-nav-ink.vue
packages/web-vue/components/tabs/tabs-nav.tsx
packages/web-vue/components/tabs/tabs.tsx
packages/web-vue/components/tag/style/index.less
packages/web-vue/components/tag/tag.vue

#3280 #1907 
在全局配置里加了rtl属性,支持这几个
|    Space       |          添加 RTL 配置     |         Add RTL configuration      |                |
|    Avatar|           添加 RTL 配置    |         Add RTL configuration      |                |
|    ConfigProvider|           添加 RTL 配置    |       Add RTL configuration        |                |
|    tabs|                       添加 RTL 配置       |        Add RTL configuration        |   |
|    tag|                       添加 RTL 配置       |        Add RTL configuration        |   |

 feat:Add RTL configuration for Space,Avatar,tabs,tag and ConfigProvider

---

packages/web-vue/components/avatar/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/avatar/avatar-group.tsx
packages/web-vue/components/avatar/avatar.vue
packages/web-vue/components/badge/badge.tsx
packages/web-vue/components/calendar/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/config-provider/README.en-US.md
packages/web-vue/components/config-provider/README.zh-CN.md
packages/web-vue/components/config-provider/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/config-provider/config-provider.vue
packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/input/README.en-US.md
packages/web-vue/components/input/README.zh-CN.md
packages/web-vue/components/input/input.tsx
packages/web-vue/components/space/space.tsx
packages/web-vue/components/tabs/tabs-button.tsx
packages/web-vue/components/tabs/tabs-nav-ink.vue
packages/web-vue/components/tabs/tabs-nav.tsx
packages/web-vue/components/tabs/tabs.tsx
packages/web-vue/components/tabs/utils.ts
packages/web-vue/components/tag/tag.vue

fix: fix rtl and docs related errors

---

packages/web-vue/components/_components/virtual-list-v2/virtual-list.vue
packages/web-vue/components/anchor/context.ts
packages/web-vue/components/breadcrumb/context.ts
packages/web-vue/components/button/button.vue
packages/web-vue/components/calendar/header.tsx
packages/web-vue/components/calendar/month.tsx
packages/web-vue/components/calendar/year.tsx
packages/web-vue/components/mention/mention.tsx
packages/web-vue/global.d.ts
packages/web-vue/package.json
packages/web-vue/tsconfig.json
pnpm-lock.yaml

修复 Type 错误和 JSX 命名空间错误
- Fixed various type errors
- Adjusted .d.ts type declaration files
- Updated tsconfig.json configuration

fix(types): fix type errors and adjust type definitions

---

packages/web-vue/components/space/__demo__/split.md
packages/web-vue/components/space/space.tsx
packages/web-vue/components/space/style/index.less

|     space      |      使用css gap属性重构，且修复内部动态元素显示隐藏间距问题         |       Refactoring using css gap properties and fixing hidden spacing issues with internal dynamic element display        |                |

refactor(space): 使用css gap属性，重构space组件
