packages/arco-vue-docs-navbar/package.json
packages/arco-vue-docs/package.json
yarn.lock

update package.json and yarn.lock

feat: update package.json and yarn.lock

---

README.md
README.zh-CN.md

docs: fix readme logo size

---

CONTRIBUTING.zh-CN.md

Fix incorrect link in contributing docs

docs: fix contributing link

---

packages/web-vue/components/alert/__test__/index.test.ts

test(alert): Update alert component test

---

packages/web-vue/components/collapse/collapse.vue

refactor(collapse): refactor repeat code

---

.github/workflows/release.yml

Add a action to create a release automatically when a new tag is created
A simple example can see [my repository](https://github.com/yuhan0709/arco-design-vue/releases) 💪😄 笔芯～

feat: add a auto-release actions to arco-vue

---

packages/web-vue/components/input/style/input.less
packages/web-vue/components/input/style/token.less

Fixes #57 
There is a left padding on the suffix icon while the clear icon has no padding or margin. And this may make the Input element blinking on hover.
Add `margin-left` to clear icon.
| input | 修改 `clear-btn` 样式，解决 `select-view` 可能会抖动的问题 | Modify the style of `clear-btn` to solve the problem that `select-view` may jitter | Close #57  |

style(input): add margin left to clear icon

---

packages/web-vue/components/trigger/trigger.tsx

Move the outsideClickHandler to the document
|trigger|将外部关闭事件移到 `document` 上|Move the `outsideClickHandler` to the `document`|Close #58 |

feat(trigger): move the outsideClickHandler to the document

---

packages/web-vue/components/textarea/textarea.vue

Fix the problem of inaccurate automatic height adjustment
|textarea|修复自动高度调整不准的问题|Fix the problem of inaccurate automatic height adjustment|Close #28 |

fix(textarea): fix the problem of inaccurate automatic height adjustment

---

packages/web-vue/components/_utils/convert-case.ts
packages/web-vue/components/_utils/vue-utils.ts
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table.tsx
packages/web-vue/components/table/utils.ts

Fix table slot problem
|table|修复 `#column` 插槽不能支持Fragment的问题|Fix the issue that `#column` slot cannot support Fragment|Close #48 Close #50 |
|table|修复 `scroll.x` 单独使用不生效的问题|Fix the problem that `scroll.x` does not take effect when used alone|Close #64 |

fix(table): fix table slot problem

---

packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input/input.tsx

Remove preventDefault of keyDown event
|input|移除 `keydown` 事件的阻止默认行为|Remove `preventDefault` of keyDown event|Close #77 |

fix(input): remove preventDefault of keyDown event

---

packages/web-vue/components/input/README.en-US.md
packages/web-vue/components/input/README.zh-CN.md
packages/web-vue/components/input/TEMPLATE.md
packages/web-vue/components/input/input.tsx

Add wordLength prop
| input | 增加 `wordLength` 属性 | Add `wordLength` prop |  Close #71  |

feat(input): add wordLength prop

---

packages/web-vue/components/upload/__demo__/picture-card.md

Added preview to `Upload` component’s photo wall example
|           |               |               |        #53         |

docs(upload): photo wall supports preview pictures

---

.vscode/settings.json
packages/web-vue/components/image/README.en-US.md
packages/web-vue/components/image/README.zh-CN.md
packages/web-vue/components/image/image.vue

* feat(image): add a slot named error-icon to support custom error status icon
* chore(vscode): fix the problem that the configuration does not take effect

Add a slot named error-icon to support custom error status icon (#85)

---

packages/web-vue/components/tabs/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/tabs/tabs-button.tsx
packages/web-vue/components/tabs/tabs-nav.tsx
packages/web-vue/components/tabs/tabs.tsx

Pref the scrolling method of the tab bar
| tabs | 优化标签栏滚动方法 | Optimize the scrolling method of the tab bar |                |

pref(tabs): pref the scrolling method of the tab bar

---

packages/web-vue/components/input-tag/input-tag.tsx

Fix the width of the input box is calculated incorrectly
| input-tag | 修复输入框宽度计算错误的问题 | Fix the problem that the width of the input box is calculated incorrectly | Close #56  |

fix(input-tag): fix the width of the input box is calculated incorrectly

---

packages/web-vue/components/input-number/input-number.tsx

Fix the problem of invalid accuracy
| input-number | 修复精度失效的问题 | Fix the problem of invalid accuracy | Close #81  |

fix(input-number): fix the problem of invalid accuracy

---

packages/web-vue/components/select/select.tsx

Fix the empty slot loss problem
| select | 修复 `#empty` 插槽丢失的问题 | Fix the issue of `#empty` slot loss |                |

fix(select): fix the empty slot loss problem

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/table-column.tsx
packages/web-vue/components/table/utils.ts

Add title slot
| table | 添加 `table-column` 中的 `#title` 插槽 | Add the `#title` slot in `table-column` |                |

feat(table): add title slot

---

.husky/pre-commit

chore: remove yarn test from pre-commit

---

packages/web-vue/components/menu/sub-menu-pop.vue

Change the value of `trigger` property of `Trigger` from `click` to `hover`
|     menu      |  将弹出型 `menu` 的默认展开方式改为 hover             |  Change the default expansion method of pop-up `menu` to hover             |        -        |

feat(menu): change the default expansion method of menu to hover

---

packages/web-vue/components/textarea/textarea.vue

fix maximum call of onUpdate
| textarea | 修复 `autoSize` 模式下内部循环更新的问题 | Fix the problem of internal loop update in `autoSize` mode | Close #110 |

fix(textarea): fix maximum call of onUpdate

---

packages/web-vue/components/input-number/input-number.tsx

fix negative wrong
| input-number | 修复输入负号出错的问题 | Fix the problem of inputting the negative sign error |  Close #99 |

fix(input-number): fix negative wrong

---

packages/web-vue/components/image/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/image/image.vue

Add height to the img tag
|     image      |   修复图片的高度限制无效的问题            |    Fix the problem that the height limit of the img is invalid           |     Close #101           |

fix(image): height does not take effect

---

packages/web-vue/components/modal/modal.vue

```
<a-modal title="this is title">
<div>this is body</div>
</a-modal>
```
add `v-if="$slots.title || title"`
|   modal  |   修复 `title` 属性不生效的问题  | Fix the problem that the `title` attribute does not take effect |                |

fix(modal): fix invalid title props

---

packages/web-vue/components/breadcrumb/breadcrumb-item.tsx
packages/web-vue/components/steps/step.vue

remove required props
| breadcrumb  |  移除 `breadcrumb-item` 中私有属性的 `required` 限制 | Remove the `required` restriction on private attributes in `breadcrumb-item` |                |
| steps  |  移除 `step` 中私有属性的 `required` 限制 | Remove the `required` restriction on private attributes in `step` |                |

fix(props): remove required props

---

packages/web-vue/components/typography/edit-content.vue

change the input event to `input`
|   typography        |       修复无法输入的问题        |   Fixed the problem of unable input            |   Close #120             |

fix(typography): the problem of unable input

---

packages/web-vue/components/upload/upload.tsx

添加limit 后，上传文件达到限制，但是上传按钮仍然可以点击
增加isMax根据fileList和limit计算
|   upload    |    修复 `limit` 属性无效的问题    |     Fix the problem of invalid `limit` prop    |                |

fix(upload): fix computed isMax

---

packages/web-vue/components/trigger/trigger.tsx
packages/web-vue/components/upload/upload.tsx

fix disabled error
| trigger | 修复 `disabled` 状态切换失效的问题 | Fix the problem of invalid state switching of `disabled` |                |

fix(trigger): fix disabled error

---

packages/web-vue/components/table/__demo__/custom.md
packages/web-vue/components/table/__demo__/fixed.md
packages/web-vue/components/table/table.tsx

fix the group header problem
| table | 修复表头分组中表格操作项占位错误的问题 | Fix the problem that the table operation items in the header grouping are occupied incorrectly |                |

fix(table): fix the group header problem

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/__demo__/row-selection.md
packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table.tsx

Add rowKey and expand-row slot
| table | 增加 `row-key` 属性 | Add `row-key` prop | Close #67  |
| table | 增加 `expandable` 中的 `expandedRowRender ` 和 `icon` 属性 | Add `expandedRowRender` and `icon` props in `expandable` |
| table | 增加 `expand-icon` 和 `expand-row` 插槽 | Add `expand-icon` and `expand-row` slots |

feat(table): add rowKey and expand-row slot

---

packages/web-vue/components/breadcrumb/breadcrumb-item.tsx

fix inherit attrs problem
| breadcrumb | 修复 `breadcrumb-item` 没有继承 Attribute 的问题 | Fix the problem of `breadcrumb-item` not inheriting Attribute |                |

fix(breadcrumb): fix inherit attrs problem

---

packages/web-vue/components/textarea/style/index.ts
packages/web-vue/components/textarea/textarea.vue

fix disabled problem
| textarea | 修复 `disabled` 不生效的问题 | Fix the problem that `disabled` does not take effect |
| textarea | 修复缺失 `style/index.js` 的问题 | Fix the issue of missing `style/index.js` |

fix(textarea): fix disabled problem

---

packages/web-vue/components/index.ts

Fix the problem of incorrect name export by Alert
|  alert | 修复组件导出名字错误的问题 | Fix the problem of incorrect name export by alert |

fix: fix the problem of incorrect name export by Alert

---

packages/web-vue/components/message/README.en-US.md
packages/web-vue/components/message/README.zh-CN.md
packages/web-vue/components/message/__demo__/type.md
packages/web-vue/components/message/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/message/index.ts
packages/web-vue/components/message/interface.ts
packages/web-vue/components/message/message.vue
packages/web-vue/components/notification/README.en-US.md
packages/web-vue/components/notification/README.zh-CN.md
packages/web-vue/components/notification/index.ts
packages/web-vue/components/notification/interface.ts

Add onClose callback & loading type
| message | 增加 `onClose` 回调方法 | Added `onClose` callback method | Close #141  |
| message | 增加 `loading` 方法 | Added `loading` method | Close #60  |
| notifaction | 增加 `onClose` 回调方法 | Added `onClose` callback method |

feat(message): add onClose callback & loading type

---

packages/web-vue/components/alert/README.en-US.md
packages/web-vue/components/alert/README.zh-CN.md
packages/web-vue/components/alert/TEMPLATE.md
packages/web-vue/components/alert/__demo__/action.md
packages/web-vue/components/alert/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/alert/alert.vue

Add action slot
| alert | 增加 `#action` 插槽 | Add `#action` slot  |                |

feat(alert): add action slot

---

packages/arco-vue-docs/docs/dark.en-US.md
packages/arco-vue-docs/docs/i18n.en-US.md
packages/arco-vue-docs/docs/start.en-US.md
packages/arco-vue-docs/docs/theme.en-US.md
packages/arco-vue-scripts/src/scripts/build-style/index.ts
packages/web-vue/components/input-tag/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/input-tag/__test__/demo.test.ts
packages/web-vue/components/style/color/colors.less
packages/web-vue/components/style/color/css-variables.less
packages/web-vue/components/style/index.less
packages/web-vue/components/style/theme/global.less
packages/web-vue/components/upload/README.en-US.md
packages/web-vue/components/upload/README.zh-CN.md
packages/web-vue/components/upload/TEMPLATE.md
packages/web-vue/components/upload/__demo__/request.md
packages/web-vue/components/upload/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/upload/upload.tsx
packages/web-vue/package.json

chore: update snap & add upload demo

---

packages/web-vue/components/form/README.en-US.md
packages/web-vue/components/form/README.zh-CN.md
packages/web-vue/components/form/TEMPLATE.md
packages/web-vue/components/form/__demo__/async.md
packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/form/context.ts
packages/web-vue/components/form/form-item.tsx
packages/web-vue/components/form/form.vue
packages/web-vue/components/form/interface.ts

Add setFields method
| form | 增加 `setFields` 方法 | Add `setFields` method |  Close #136   |

feat(form): add setFields method

---

packages/web-vue/components/_utils/vue-utils.ts

Fix group table-column problem
| table | 修复 `<table-column>` 在分组表头错误的问题 | Fix the problem that `<table-column>` is wrong in the header of the grouping table | Close #143  |

fix(table): fix group table-column problem

---

packages/web-vue/components/trigger/utils.ts

fix the problem of svg position error
| trigger |  修复 `<svg>` 元素定位错误的问题 | Fix the problem of `<svg>` element positioning error |                |

fix(trigger): fix the problem of svg position error

---

packages/web-vue/components/input-tag/input-tag.tsx

Depending on item.closable and disabled
|  input-tag  |  修复disabled状态下标签仍可被关闭    |    fix tag can be close in the disabled state     |                |

fix(input-tag): fix tag can be close in the disabled state

---

packages/arco-vue-docs-navbar/package.json
packages/arco-vue-docs/app.vue
packages/arco-vue-docs/package.json
yarn.lock

Add a page view duration tracker and update the navbar version

site: add vue page_view tracker

---

packages/web-vue/components/image/__demo__/progressive-loader.md
packages/web-vue/components/image/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/image/image.vue
packages/web-vue/components/image/style/image.less

set the max size of error to fit parent
|     image      |       将错误状态图标的最大尺寸设置为父元素的大小        |     set the max size of error to fit parent          |       -         |

style(image): set the max size of error to fit parent

---

packages/web-vue/components/_hooks/use-popup-manager.ts
packages/web-vue/components/drawer/__test__/__snapshots__/index.test.ts.snap
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/image/__test__/__snapshots__/index.test.ts.snap
packages/web-vue/components/image/preview.vue
packages/web-vue/components/modal/__test__/__snapshots__/index.test.ts.snap
packages/web-vue/components/modal/modal.vue

|     Modal      |  统一管理弹出层的 zIndex             |     Manage the zIndex of the popup          |  Close #158          |

feat(zindex): manage the zindex of modal/drawer/image.preview

---

packages/web-vue/components/_utils/is.ts
packages/web-vue/components/upload/README.en-US.md
packages/web-vue/components/upload/README.zh-CN.md
packages/web-vue/components/upload/interfaces.ts
packages/web-vue/components/upload/upload-button.tsx
packages/web-vue/components/upload/upload-list-item.tsx
packages/web-vue/components/upload/upload-list.tsx
packages/web-vue/components/upload/upload-picture-item.tsx
packages/web-vue/components/upload/upload.tsx
packages/web-vue/components/upload/utils.tsx

add events and slots
|  upload | 增加 `upload-button` 和 `upload-item` 插槽  | Added `upload-button` and `upload-item` slots |                |
|  upload | 增加 `success` 和 `error` 事件  | Added `success` and `error` events |                |
|  upload | 增加 `on-click-button` 、`custom-icon`、`directory ` 属性  | Add `on-click-button`, `custom-icon`, `directory` attributes |                |

feat(upload): add events and slots

---

packages/web-vue/components/tree-select/README.en-US.md
packages/web-vue/components/tree-select/README.zh-CN.md
packages/web-vue/components/tree-select/hooks/use-filter-tree-node.ts
packages/web-vue/components/tree-select/hooks/use-selected-state.ts
packages/web-vue/components/tree-select/interface.ts
packages/web-vue/components/tree-select/panel.vue
packages/web-vue/components/tree-select/tree-select.vue
packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/base-node.vue
packages/web-vue/components/tree/context.ts
packages/web-vue/components/tree/hooks/use-checked-state.ts
packages/web-vue/components/tree/hooks/use-draggable.ts
packages/web-vue/components/tree/hooks/use-node-key.ts
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/transition-node-list.vue
packages/web-vue/components/tree/tree.vue
packages/web-vue/components/tree/utils/index.ts
packages/web-vue/components/tree/utils/tree-data.ts

|      tree     |   `key` 支持 `number`  类型            |   `key` support `number`            |    close #163           |

feat(tree): add type number for key

---

packages/web-vue/components/_utils/get-value-by-path.ts
packages/web-vue/components/table/utils.ts

| form |  修复 `filed` 字段传入 null 导致报错的问题   | Fix the problem that the input of null in the `filed` field causes an error to be reported |                |

fix(form): fix the field is null

---

packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input-tag/style/input-tag.less
packages/web-vue/components/input/input.tsx

fix composition & press enter problem
| input-tag | 修复中文输入法问题 |  Fix Chinese input method problem  |                |
| input-tag | 修复 Enter 键触发 form 提交的问题 | Fix the issue that the Enter key triggers form submission |                |

fix(input-tag): fix composition & press enter problem

---

packages/web-vue/components/cascader/README.en-US.md
packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/TEMPLATE.md
packages/web-vue/components/cascader/__test__/__snapshots__/index.test.ts.snap
packages/web-vue/components/cascader/cascader-option.tsx
packages/web-vue/components/cascader/cascader-panel.tsx
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/cascader/interface.ts
packages/web-vue/components/cascader/utils.ts

add number value & VNode label support
|  cascader  |  增加 `options.value` 数字类型和 `options.label` 自定义渲染的支持  | Add `options.value` number type and `options.label` custom rendering support |                |

feat(cascader): add number value & VNode label support

---

packages/web-vue/components/cascader/cascader-search-panel.tsx
packages/web-vue/components/cascader/style/index.less

fix search panel not scroll
|  cascader  |  修复搜索输入框不能滚动的问题 |  Fix the problem that the search input box cannot be scrolled  |                |

fix(cascader): fix search panel not scroll

---

packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/drawer.vue

add width & height string support
| drawer  | `width` 和 `height` 增加支持字符类型 | `width` and `height` added support for character types  |   Close #159   |

feat(drawer): add width & height string support

---

packages/web-vue/components/tree-select/hooks/use-selected-state.ts
packages/web-vue/components/tree/tree.vue

|     tree-select      |      无法选中 key 为 0 的选项         |      cannot select the option with key 0         |      -          |

fix(tree-select): cannot select the option with key 0

---

packages/web-vue/components/_components/select-view/select-view.tsx
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/textarea/textarea.vue

| common |  修复 input 型组件在弹出层不能获取焦点的问题 | Fix the problem that the input type component cannot get the focus in the pop-up layer |  Close #177  |

fix: fix input component can't focus on popup

---

packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table-column.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table.tsx

|  table  |  `columns.render` 增加 `rowIndex` 参数  |  `columns.render` adds `rowIndex` parameter  |                |

feat(table): column render add rowIndex

---

packages/web-vue/components/_components/select-view/select-view.tsx
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/textarea/textarea.vue

fix input component focus problem
| common | 修复 input 型组件重复获取焦点的问题 | Fix the problem that input type components repeatedly get focus | Close #192 #190     |

fix: fix input component focus problem

---

packages/web-vue/components/_components/select-view/select-view.tsx
packages/web-vue/components/auto-complete/auto-complete.tsx
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/mention/mention.tsx
packages/web-vue/components/select/select.tsx
packages/web-vue/components/textarea/textarea.vue
packages/web-vue/components/time-picker/time-picker.vue
packages/web-vue/components/tree-select/tree-select.vue
packages/web-vue/components/trigger/trigger.tsx

add preventFocus prop
| trigger | 增加 `prevent-focus` 属性  |  Add `prevent-focus` property  |  Close #177   |
| select | 增加 `trigger-props` 属性  |  Add `trigger-props` property  |   |
| cascader | 增加 `trigger-props` 属性  |  Add `trigger-props` property  |      |

feat(trigger): add preventFocus prop

---

packages/web-vue/components/upload/style/index.less
packages/web-vue/components/upload/upload-list-item.tsx
packages/web-vue/components/upload/upload-list.tsx
packages/web-vue/components/upload/upload-picture-item.tsx
packages/web-vue/components/upload/upload.tsx

fix image name overflow problem
|  upload | 修复图片名过长时溢出的问题 | Fix the problem of overflow when the picture name is too long |                |
|  upload | 修复照片墙模式，超出长度不能换行的问题 | Fix the problem that the photo wall mode cannot wrap when it exceeds the length |                |

fix(upload): fix image name overflow problem

---

packages/web-vue/components/textarea/textarea.vue

add wordLength prop
|  textarea  | 增加 `word-length` 属性 |  Add `word-length` attribute |                |

feat(textarea): add wordLength prop

---

packages/web-vue/components/select/select.tsx

fix option slot no data
|  select  |  修复 `option` 插槽没有传出 `data` 参数的问题  | Fix the problem that the `data` parameter is not sent from the `option` slot  |                |

fix(select): fix option slot no data

---

packages/web-vue/components/_utils/pick-sub-comp-slots.ts
packages/web-vue/components/tree-select/panel.tsx
packages/web-vue/components/tree-select/tree-select.vue

|    tree-select       |    支持 tree 的 slots           |      support the slots of tree         |     Close #146            |

feat(tree-select): support the slots of tree

---

packages/web-vue/components/menu/style/index.less
packages/web-vue/components/menu/style/token.less
packages/web-vue/components/menu/sub-menu-pop.vue

|    menu       |  弹出型子菜单适配暗色主题             |    pop menu adapts to dark theme           |     -           |

style(menu): pop menu adapts to dark theme

---

packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/components/time-picker/time-picker.vue
packages/web-vue/components/tree-select/tree-select.vue

|    date-picker       |   修复在 form 里校验异常的问题            |     Fix the problem of abnormal verification in form          |      Close #189           |

fix(date-picker): fix the problem of invalid verification

---

packages/web-vue/components/_components/dropdown/dropdown.vue
packages/web-vue/components/dropdown/style/index.less
packages/web-vue/components/select/select.tsx

add footer slot
| select  |  增加 `footer` 插槽  | Add `footer` slot |                |

feat(select): add footer slot

---

packages/web-vue/components/_components/select-view/select-view.tsx
packages/web-vue/components/input-tag/input-tag.tsx

add backspace support
| input-tag |  增加退格键的支持 | Add support for backspace key |                |

feat(input-tag): add backspace support

---

packages/web-vue/components/table/table.tsx

do not scroll when data is empty
|  table  | 数据为空时不展示滚动 | Do not scroll when data is empty | Close #238  |

fix(table): do not scroll when data is empty

---

packages/web-vue/components/trigger/__demo__/nest.md
packages/web-vue/components/trigger/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/trigger/context.ts
packages/web-vue/components/trigger/trigger.tsx

Fix nest problem
| trigger | 修复嵌套不同类型 `<trigger>` 时触发错误的问题 | Fix the problem of triggering errors when nesting different types of `<trigger>` |  Close #230  |

fix(trigger): fix nest problem

---

packages/web-vue/components/alert/style/index.less
packages/web-vue/components/alert/style/token.less
packages/web-vue/components/button/style/index.less
packages/web-vue/components/button/style/token.less
packages/web-vue/components/card/style/index.less
packages/web-vue/components/divider/style/index.less
packages/web-vue/components/divider/style/token.less
packages/web-vue/components/typography/style/index.less
packages/web-vue/components/typography/style/token.less

style: modify alert & button style

---

packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/table/table-operation-td.tsx

fix expand button trigger form submit
| table | 修复展开行按钮触发表单提交的问题 | Fix the issue that the expand row button triggers form submission | Close #204  |

fix(table): fix expand button trigger form submit

---

packages/web-vue/components/_utils/vue-utils.ts
packages/web-vue/components/breadcrumb/breadcrumb.tsx
packages/web-vue/components/steps/steps.tsx

Fix the problem of unavailable step status
| steps |  修复 `<step>` 组件中 `status` 属性不生效的问题 | Fix the problem that the `status` attribute in the `<step>` component does not take effect | Close #219 |

fix(steps): fix the problem of unavailable step status

---

packages/web-vue/components/form/style/index.less

https://github.com/arco-design/arco-design-vue/blob/1d7ff6c6ccb8549629343da8d8effe76473d5828/packages/web-vue/components/form/style/index.less#L112
https://github.com/arco-design/arco-design-vue/blob/1d7ff6c6ccb8549629343da8d8effe76473d5828/packages/web-vue/components/form/form-item.tsx#L473
https://github.com/arco-design/arco-design-vue/blob/1d7ff6c6ccb8549629343da8d8effe76473d5828/packages/web-vue/components/form/form-item.tsx#L155
tsx 文件与 less 文件中 表单额外显示内容 的 className 不一致，导致表单额外显示内容未应用相应样式。
统一类名
|     form      | 修复表单附加内容样式没生效的问题 |  Fix the problem that the additional content style of the form does not take effect   |                |
should be submitted to …

fix: style of form item extra

---

packages/web-vue/components/_utils/types.ts
packages/web-vue/components/affix/affix.vue
packages/web-vue/components/auto-complete/auto-complete.tsx
packages/web-vue/components/button/button.vue
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/checkbox/checkbox-group.vue
packages/web-vue/components/checkbox/checkbox.vue
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input/input-search.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/mention/mention.tsx
packages/web-vue/components/popover/popover.vue
packages/web-vue/components/radio/radio-group.vue
packages/web-vue/components/radio/radio.vue
packages/web-vue/components/rate/rate.tsx
packages/web-vue/components/select/select.tsx
packages/web-vue/components/slider/slider.vue
packages/web-vue/components/switch/switch.vue
packages/web-vue/components/table/table.tsx
packages/web-vue/components/tag/tag.vue
packages/web-vue/components/textarea/textarea.vue
packages/web-vue/components/time-picker/time-picker.vue
packages/web-vue/components/transfer/transfer.vue
packages/web-vue/components/tree-select/tree-select.vue
packages/web-vue/components/trigger/trigger.tsx
packages/web-vue/components/upload/upload.tsx

jsx prop support array
|  common  |  修复在 `<form>` 中使用输入型组件在控制台出现类型警告的问题  |   Fix the issue of type warning in the console when using input components in `<form>`   |                |

fix: jsx prop support array

---

packages/web-vue/components/collapse/style/index.less
packages/web-vue/components/collapse/style/token.less

feat: add collapse token

---

packages/web-vue/components/comment/style/token.less

feat: add comment token

---

packages/web-vue/components/textarea/textarea.vue

如下图，可以添加一个发送按钮，当focus的时候显示，不focus的时候隐藏，因为textarea focus选择器不能选择父元素，所以加一个slot方便使用
除了focus， textarea:placeholder-shown（显示占位符的时候不显示发送按钮）也可以用

textarea add slot

---

packages/web-vue/components/card/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/link/README.en-US.md
packages/web-vue/components/link/README.zh-CN.md
packages/web-vue/components/link/TEMPLATE.md
packages/web-vue/components/link/__demo__/hoverable.md
packages/web-vue/components/link/__demo__/icon.md
packages/web-vue/components/link/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/link/link.vue
packages/web-vue/components/link/style/index.less
packages/web-vue/components/link/style/token.less
packages/web-vue/components/style/theme/css-variables.less

|    link       |    增加通过 `icon` 属性/插槽设置图标        |      Add icon setting via `icon` property/slot property or slot         |               |

feat: Link supports icon property & hoverable property

---

packages/web-vue/components/steps/style/circle.less

|   steps   |   修复竖直步骤条连线颜色的问题  | Fix the problem of the connection color of the vertical step bar  |                |

fix(steps): style problem

---

packages/web-vue/components/pagination/README.en-US.md
packages/web-vue/components/pagination/README.zh-CN.md
packages/web-vue/components/pagination/pagination.tsx

add base-size & buffer-size
| pagination |   增加 `base-size` & `buffer-size` 属性  |   add `base-size` & `buffer-size` props   |  Close #251 , Close #252         |

feat(pagination): add base-size & buffer-size

---

packages/web-vue/components/style/icon.less

|  common  |  修复新版浏览器中选择图标会出现外边框的问题   |  Fix the problem that the outer border of the icon will appear when selecting the icon in the new version of the browser  |                |

fix(icon): style problem

---

packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input/input.tsx

|  input  |  修复数字键盘回车键没有触发 `press-enter` 的问题  |  Fix the problem that the enter key of the numeric keyboard does not trigger `press-enter`  |  Close #262  |

fix(input): fix pressEnter problem

---

packages/arco-vue-scripts/package.json
packages/arco-vue-scripts/src/index.ts
packages/arco-vue-scripts/src/scripts/docgen/index.ts
packages/arco-vue-scripts/src/scripts/jsongen/index.ts
packages/arco-vue-scripts/src/utils/get-package.ts
packages/web-vue/.gitignore
packages/web-vue/package.json

add jsongen command
|  common  |  增加对 web-types 和 vetur 的智能提示支持  | Added support for smart prompts for web-types and vetur  |                |

feat(scripts): add jsongen command

---

packages/web-vue/components/form/README.en-US.md
packages/web-vue/components/form/README.zh-CN.md
packages/web-vue/components/form/context.ts
packages/web-vue/components/form/form-item.tsx
packages/web-vue/components/form/form.vue

add form rules prop
|  form  |  增加 `rules` 属性  |  Add `rules` prop  |                |

feat(form): add form rules prop

---

packages/web-vue/components/descriptions/style/index.less

modify desc value style
|  descriptions  |  修改 value 区域样式，支持换行文本  |  Modify the style of the value area to support line-wrapping text  |  Close #233 |

feat(desc): modify desc value style

---

packages/web-vue/components/avatar/README.en-US.md
packages/web-vue/components/avatar/README.zh-CN.md
packages/web-vue/components/avatar/avatar-group.tsx
packages/web-vue/components/avatar/avatar.vue
packages/web-vue/components/avatar/style/index.less
packages/web-vue/components/avatar/style/token.less

|   avatar        |      支持 `maxStyle` 和 `maxPopoverTriggerProps` 属性。         |  supports `maxStyle` and `maxPopoverTriggerProps` properties.             |                |

feat: Avatar supports maxStyle & maxPopoverTriggerProps property

---

packages/web-vue/components/_utils/constant.ts
packages/web-vue/components/descriptions/README.en-US.md
packages/web-vue/components/descriptions/README.zh-CN.md
packages/web-vue/components/descriptions/__demo__/align.md
packages/web-vue/components/descriptions/__demo__/layout.md
packages/web-vue/components/descriptions/descriptions.tsx

|  descriptions  |  增加 `align` 属性  |  Add the `align` prop  |                |

feat(desc): add align prop

---

packages/web-vue/components/tree/style/index.less

|     tree      |     让树节点的内容垂直居中          |      let the content of tree node centerd in vertical         |      Close #240           |

fix(tree): let the content of tree node centerd in vertical

---

packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/modal/modal.vue

fix open event
|  modal  |  修复初始触发 `open` 事件的问题  | Fix the issue of initial triggering of the `open` event  |                |
|  drawer  |  修复初始触发 `open` 事件的问题  | Fix the issue of initial triggering of the `open` event  |                |

fix(modal): fix open event

---

packages/web-vue/components/menu/sub-menu-pop.vue

|      menu     |        `trigger-props` 不生效       |        the prop trigger-props take no effect       |     Close #256            |

fix(menu): the prop trigger-props take no effect

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/style/index.less
packages/web-vue/components/table/table.tsx

|  table  |  增加 `footer` 插槽   |  Add `footer` slot  |                |
|  table  |  常规模式下表格宽度大于容器时会开启滚动条   |  In normal mode, the scroll bar will be turned on when the table width is larger than the container  |  Close #217   |

feat(table): add footer slot

---

packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/__demo__/async.md
packages/web-vue/components/drawer/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/modal/README.en-US.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/__demo__/async.md
packages/web-vue/components/modal/__demo__/basic.md
packages/web-vue/components/modal/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/popconfirm/README.en-US.md
packages/web-vue/components/popconfirm/README.zh-CN.md
packages/web-vue/components/popconfirm/__demo__/async.md
packages/web-vue/components/popconfirm/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/popconfirm/popconfirm.vue

add on-before-ok to async close
|  modal  |  增加 `on-before-ok` 和 `on-before-cancel` 属性事件  | Added `on-before-ok` and `on-before-cancel` property events |                |
|  drawer  |  增加 `on-before-ok` 和 `on-before-cancel` 属性事件  | Added `on-before-ok` and `on-before-cancel` property events |                |
|  popconfirm  |  增加 `on-before-ok` 和 `on-before-cancel` 属性事件  | Added `on-before-ok` and `on-before-cancel` property events |                |

feat: add on-before-ok to async close

---

packages/web-vue/components/progress/README.en-US.md
packages/web-vue/components/progress/README.zh-CN.md
packages/web-vue/components/progress/circle.vue
packages/web-vue/components/progress/line.vue
packages/web-vue/components/progress/progress.vue
packages/web-vue/components/progress/steps.vue

add trackColor prop
|  progress |  增加 `track-color` 属性  |   Add `track-color` prop  |   Close #257        |

feat(progress): add trackColor prop

---

packages/arco-vue-scripts/package.json
packages/arco-vue-scripts/src/configs/vite.material.library.ts
packages/arco-vue-scripts/src/configs/vite.material.library.umd.ts
packages/arco-vue-scripts/src/index.ts
packages/arco-vue-scripts/src/scripts/build-material-library/index.ts
packages/arco-vue-scripts/src/scripts/build-material/index.ts
packages/arco-vue-scripts/src/scripts/build-style/index.ts
packages/arco-vue-scripts/src/scripts/dtsgen/index.ts
packages/arco-vue-scripts/src/utils/get-package.ts

feat(script): add material-library script

---

packages/web-vue/components/style/index.less

Add body font-family
|  common |   增加 body 上的 font-family   |  Add the font-family on the body  |                |

feat(font): add body font-family

---

packages/web-vue/components/list/__test__/index.test.ts
packages/web-vue/components/list/list.tsx

|    list       |   增加空数据的展示            |    Add the display of empty data          |                |

fix(list): add empty status

---

packages/web-vue/components/comment/style/index.less
packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/TEMPLATE.md
packages/web-vue/components/drawer/__demo__/popup-container.md
packages/web-vue/components/drawer/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/drawer/__test__/__snapshots__/index.test.ts.snap
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/drawer/style/index.less
packages/web-vue/components/drawer/style/token.less
packages/web-vue/components/dropdown/style/index.less
packages/web-vue/components/dropdown/style/token.less
packages/web-vue/components/empty/style/index.less
packages/web-vue/components/empty/style/token.less
packages/web-vue/components/list/style/index.less
packages/web-vue/components/page-header/page-header.vue
packages/web-vue/components/page-header/style/index.less
packages/web-vue/components/page-header/style/token.less
packages/web-vue/components/pagination/page-jumper.vue
packages/web-vue/components/pagination/page-options.vue
packages/web-vue/components/pagination/pagination.tsx
packages/web-vue/components/pagination/style/index.less

|    pagination       |    修复 `disabled` 属性设置为 true 时，输入框和条数选择器未禁用的问题     | Fix the problem that the input box and the number selector are not disabled when the `disabled` property is set to true             |                |
|    drawer       |    修复设置 `popup-container` 属性时，抽屉仍然是 `fixed` 布局的问题         |  Fix the problem that the drawer is still in the fixed layout when setting the popup-container property         |                |

fix: Fix drawer popup container not work & fix[Pagination]: disable jumper and pageSize selector when disabled is true

---

packages/web-vue/components/progress/README.en-US.md
packages/web-vue/components/progress/README.zh-CN.md
packages/web-vue/components/progress/TEMPLATE.md
packages/web-vue/components/progress/__demo__/basic.md
packages/web-vue/components/progress/__demo__/circle.md
packages/web-vue/components/progress/__demo__/linear.md
packages/web-vue/components/progress/__demo__/mini.md
packages/web-vue/components/progress/__demo__/steps.md
packages/web-vue/components/progress/__demo__/trackColor.md
packages/web-vue/components/progress/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/progress/circle.vue
packages/web-vue/components/progress/progress.vue
packages/web-vue/components/progress/style/index.less
packages/web-vue/components/progress/style/token.less
packages/web-vue/components/radio/style/index.less
packages/web-vue/components/radio/style/token.less
packages/web-vue/components/spin/dot-loading.tsx
packages/web-vue/components/spin/style/dot-loading.less
packages/web-vue/components/spin/style/token.less
packages/web-vue/components/statistic/style/index.less
packages/web-vue/components/statistic/style/token.less

|    progress       |  修复 `text ` 插槽未生效的问题              |        Fix the problem that the `text` slot does not take effect      |       

fix: Progress slots text not work

---

packages/web-vue/components/_utils/vue-utils.ts
packages/web-vue/components/form/form-item.tsx
packages/web-vue/components/space/space.tsx
packages/web-vue/components/spin/spin.tsx
packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/table.tsx

some bugs fix and perf
|  form  |    修复 `setFields` 方法设定空值失效的问题       |  Fix the problem of invalid setting of null value in `setFields` method  |                |

fix: some bugs fix and perf

---

packages/web-vue/components/auto-complete/auto-complete.tsx

fix disabled problem
|  auto-complete |   修复 disabled 不可用的问题            |    Fix the problem that disabled is unavailable   |                |

fix(auto-complete): fix disabled problem

---

packages/web-vue/components/_utils/constant.ts
packages/web-vue/components/textarea/__demo__/auto-size.md
packages/web-vue/components/textarea/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/textarea/textarea.vue
packages/web-vue/components/textarea/utils.ts

support min & max rows
|  textarea  |  增加最小行和最大行的支持  |   Add support for min rows and max rows  |                |

feat(textarea): support min & max rows

---

packages/web-vue/.eslintrc.js
packages/web-vue/components/_components/dropdown/dropdown-option.vue
packages/web-vue/components/_components/dropdown/utils.ts
packages/web-vue/components/_components/select-view/select-view.tsx
packages/web-vue/components/cascader/README.en-US.md
packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/__demo__/multiple.md
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/cascader/interface.ts
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input-tag/interface.ts
packages/web-vue/components/input-tag/utils.ts
packages/web-vue/components/select/README.en-US.md
packages/web-vue/components/select/README.zh-CN.md
packages/web-vue/components/select/utils.ts
packages/web-vue/components/tag/index.ts

add tag-props support
|  select  |  增加 `tagProps` 的支持  |  Add support for `tagProps`  |  Close #179   |
|  cascader  |  增加 `tagProps` 的支持  |  Add support for `tagProps`  |                |
|  input-tag  |  增加 `tagProps` 的支持  |  Add support for `tagProps`  |                |

feat: add tag-props support

---

packages/web-vue/components/menu/README.en-US.md
packages/web-vue/components/menu/README.zh-CN.md
packages/web-vue/components/menu/base-menu.vue
packages/web-vue/components/menu/context.ts
packages/web-vue/components/menu/hooks/use-level.ts
packages/web-vue/components/menu/hooks/use-menu-context.ts
packages/web-vue/components/menu/hooks/use-menu-data-collector.ts
packages/web-vue/components/menu/hooks/use-menu-open-state.ts
packages/web-vue/components/menu/interface.ts
packages/web-vue/components/menu/item.tsx
packages/web-vue/components/menu/menu.tsx

|     menu      |       新增属性  `auto-open-selected`        |    add prop    auto-open-selected       |       Close #237          |

feat(menu): add prop auto-open-selected

---

packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/tree.vue

Fixes #138 
The tree component does not deal with checked keys after `loadMore`.
Execute `onCheck` function after the execution of `loadMore`.
| tree          | 动态加载节点后更新勾选状态              | Update checked keys after load more              | Close #138                |
I made the `e` argument optional. Please review this and check if there are any unexpected side effects.

fix(tree): execute onCheck function after load more

---

packages/web-vue/components/space/space.tsx

fix render comment item
|  space  |  修复渲染 v-if 节点的问题  |   Fix the problem of rendering v-if nodes   |  Close #317    |

fix: fix render comment item

---

packages/web-vue/components/drawer/drawer.vue

|       Drawer    |      `Drawer` 支持 `okButtonProps` 和  `cancelButtonProps` 属性        |     `Drawer` supports okButtonProps & cancelButtonProps         |                |

feat: drawer supports okButtonProps & cancelButtonProps

---

packages/web-vue/components/pagination/README.en-US.md
packages/web-vue/components/pagination/README.zh-CN.md
packages/web-vue/components/pagination/TEMPLATE.md
packages/web-vue/components/pagination/__demo__/custom.md
packages/web-vue/components/pagination/page-item-ellipsis.vue
packages/web-vue/components/pagination/page-item-step.vue
packages/web-vue/components/pagination/page-item.vue
packages/web-vue/components/pagination/pagination.tsx
packages/web-vue/components/pagination/style/index.less
packages/web-vue/components/table/table.tsx

add slot & formatTotal
|  pagination  |  修改和增加插槽，支持模板自定义   |   Modify and add slots, support template customization  |                |
|  pagination  |  增加 `format-total` 属性   |   Add `format-total` prop | Close #290   |

feat(pagination): add slot & formatTotal

---

packages/web-vue/components/table/table.tsx

fix button trigger form submit
|   table   |   修复树形展开按钮触发表单提交的问题  |  Fix the problem that the tree expand button triggers form submission  | Close #319  |

fix: fix button trigger form submit

---

packages/arco-vue-docs/components/article/style.less
packages/arco-vue-scripts/src/scripts/docgen/templates/events.ts
packages/arco-vue-scripts/src/scripts/docgen/templates/methods.ts
packages/arco-vue-scripts/src/scripts/docgen/templates/props.ts
packages/arco-vue-scripts/src/scripts/docgen/templates/slots.ts

feat(script): support generate version

---

packages/web-vue/components/menu/base-menu.vue
packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/tree.vue

…uto-expand-parent
|    tree       |     新增属性 `default-expand-selected` `default-expand-checked` `auto-expand-parent`          |       add prop default-expand-selected default-expand-checked auto-expand-parent        |         Close #300        |

feat(tree): add prop default-expand-selected default-expand-checked auto-expand-parent

---

packages/web-vue/components/spin/spin.tsx

fix remount problem
|  spin | 修复容器模式下切换状态导致子组件重新加载的问题  | Fix the problem that switching states in container mode causes sub-components to reload |                |

fix: fix remount problem

---

packages/web-vue/components/avatar/avatar-group.tsx

style: eliminate the prettier warning

---

packages/web-vue/components/carousel/style/index.less

子项样式优先级过高，导致父级样式不生效。已经out的子项与current子项覆盖。
|   carousel        |     out子项内未隐藏         |    The out subitem is not hidden           |                |

fix(carousel): carousel item cover

---

packages/web-vue/components/input-tag/__demo__/status.md
packages/web-vue/components/input-tag/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input-tag/style/index.less
packages/web-vue/components/input-tag/style/input-tag.less
packages/web-vue/components/input-tag/utils.ts
packages/web-vue/components/input/style/input.less
packages/web-vue/components/tag/style/index.less

optimize animation & style
|  input-tag  |  优化标签动画和关闭按钮样式  |  Optimize label animation and close button style  |  Close #283, Close #294 |

chore(input-tag): optimize animation & style

---

packages/web-vue/components/menu/style/index.less

… parent element
|     menu      |     修复菜单宽度没有撑满父元素的问题          |       fix the problem that the width of the menu cannot fill the parent element        |        Close #344         |

fix(menu): fix the problem that the width of the menu cannot fill the parent element

---

packages/web-vue/components/modal/__test__/__snapshots__/index.test.ts.snap
packages/web-vue/components/modal/index.tsx
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/modal/style/index.less

fix modal message style error
|  modal  |  修复 modal 信息展示模式错误的问题  | Fix the problem of modal information display mode error |                |
|  modal  |  简单模式下不展示标题栏关闭按钮  | The title bar close button is not displayed in simple mode |                |

fix(modal): fix modal message style error

---

packages/web-vue/components/_components/select-view/select-view.tsx
packages/web-vue/components/_components/select-view/style/index.less
packages/web-vue/components/cascader/README.en-US.md
packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/message/style/index.less
packages/web-vue/components/select/README.en-US.md
packages/web-vue/components/select/README.zh-CN.md
packages/web-vue/components/select/__demo__/linkage.md
packages/web-vue/components/select/base-select.tsx

update message style
|  message  |  使用 flex 布局方式展示信息  |  Use flex layout to display message  |  Close #282   |

fix(message): update message style

---

packages/web-vue/components/textarea/__demo__/status.md
packages/web-vue/components/textarea/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/textarea/textarea.vue

fix disabled style
|  textarea  |  修正禁止模式的样式问题  |   Fix the style problem of prohibited mode   |                |

fix(textarea): fix disabled style

---

packages/web-vue/components/tabs/tabs-tab.vue

fix closable problem
|  tabs |  修复可编辑模式下选项卡 closable 失效的问题  | Fix the problem of tab closable failure in editable mode  |                |

fix(tabs): fix closable problem

---

packages/web-vue/components/statistic/README.en-US.md
packages/web-vue/components/statistic/README.zh-CN.md
packages/web-vue/components/statistic/statistic.vue

fix precision problem
|   statistic  |  修复 precision 为 0 时没有生效的问题 |  Fix the problem that it does not take effect when precision is 0  | Close #253     |

fix(statistic): fix precision problem

---

packages/web-vue/components/collapse/README.en-US.md
packages/web-vue/components/collapse/README.zh-CN.md
packages/web-vue/components/collapse/__demo__/basic.md
packages/web-vue/components/collapse/collapse-item.vue
packages/web-vue/components/collapse/collapse.vue
packages/web-vue/components/collapse/context.ts

key add number support
| collapse |  key增加对number的支持 |  key adds support for number  |  Close #304  |

feat(collapse): key add number support

---

packages/web-vue/components/input-number/__demo__/basic.md
packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input/input.tsx

fix input - & . problem
|  input-number  |  修复可重复输入 `-` 和 `.` 的问题  |  Fix the problem of repeatable input of `-` and `.`  |  Close #342  |

fix(input-number): fix input - & . problem

---

packages/web-vue/components/form/README.en-US.md
packages/web-vue/components/form/README.zh-CN.md
packages/web-vue/components/form/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/form/form-item.tsx

add some props
|  form  |  `form-item` 增加布局和类名相关属性  |   `form-item` adds layout and class name related attributes  |                |

feat(form): add some props

---

packages/web-vue/components/tabs/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/tabs/style/index.less
packages/web-vue/components/tabs/tabs-nav.tsx
packages/web-vue/components/tabs/tabs.tsx

add headerPadding
|  tabs  |  增加 headerPadding 属性并默认开启  | Add headerPadding property and enable it by default |                |

feat(tabs): add headerPadding

---

packages/web-vue/components/avatar/CHANGELOG.zh-CN.md
packages/web-vue/components/carousel/CHANGELOG.zh-CN.md
packages/web-vue/components/input-tag/CHANGELOG.zh-CN.md
packages/web-vue/components/steps/CHANGELOG.zh-CN.md

docs: update some changelog docs

---

packages/web-vue/components/card/__demo__/bordered.md
packages/web-vue/components/card/card-meta.tsx
packages/web-vue/components/card/card.tsx
packages/web-vue/components/card/context.ts

refactor card, fix slots problem
|  card  |   修复 slots 内容存在不更新的问题   |  Fix the problem that the content of slots is not updated   |                |

fix(card): refactor card, fix slots problem

---

packages/web-vue/components/trigger/trigger.tsx

fix popup resize & alignPoint problem
|  trigger  |  修复弹出层尺寸变化不会触发更新的问题   | Fix the problem that the pop-up layer size change will not trigger the update  |   Close #215     |
|  trigger  |  修复 `align-point` 模式下位置和自适应不生效的问题   | Fix the problem that the position and adaptation in `align-point` mode do not take effect  |                |

fix(trigger): fix popup resize & alignPoint problem

---

packages/web-vue/components/input-tag/style/input-tag.less
packages/web-vue/components/input/style/input.less

fix input & input-tag style problem
|  input-tag  |  修复组件高度问题  |  Fix the component height problem   |  Close #370  |
|  input-tag  |  修复组件关闭按钮宽度问题  |  Fix the width of the component close button   |  Close #379  |

fix(input): fix input & input-tag style problem

---

packages/web-vue/components/cascader/utils.ts

fix totalLeafOptions cal
|  cascader  |   修复多选模式下存在空子菜单时计数错误的问题  |  Fix the problem of counting errors when there is an empty sub-menu in multi-select mode   |   Close #381   |

fix(cascader): fix totalLeafOptions cal

---

CONTRIBUTING.md
CONTRIBUTING.zh-CN.md
README.md
README.zh-CN.md
packages/web-vue/components/modal/README.en-US.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/interface.ts

add ts prop
|  modal  |   `ModalConfig ` 增加 `simple` 属性注解      |  `ModalConfig` adds `simple` attribute annotation   |                |

fix(modal): add ts prop

---

packages/web-vue/components/popconfirm/README.en-US.md
packages/web-vue/components/popconfirm/README.zh-CN.md
packages/web-vue/components/popconfirm/popconfirm.vue
packages/web-vue/components/popconfirm/style/index.less
packages/web-vue/components/popconfirm/style/token.less

fix style problem
|   popconfirm  |   修正组件样式问题，并调整按钮默认大小为 `mini`，同React保持一致    |   Fix the component style problem, and adjust the default size of the button to `mini`, which is consistent with React    |                |

fix(popconfirm): fix style problem

---

packages/web-vue/components/cascader/utils.ts

fix totalLevel error
|  cascader  | 修复层级 totalLevel 计算错误的问题  |  Fix the problem that the level totalLevel is calculated incorrectly |                |

fix(cascader): fix totalLevel error

---

packages/web-vue/components/anchor/style/index.less
packages/web-vue/components/breadcrumb/style/index.less
packages/web-vue/components/breadcrumb/style/token.less
packages/web-vue/components/message/style/index.less
packages/web-vue/components/modal/__test__/__snapshots__/index.test.ts.snap
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/modal/style/index.less

|   modal        |      修复 `alignCenter` 属性不生效的问题        |    Fix the problem that the `alignCenter` property does not take effect         |                |
|   modal        |      调整组件的 `alignCenter` 属性默认为 `true`     |    The `alignCenter` property of the adjustment component defaults to `true`     |                |

fix: the align-center property of Modal not work

---

packages/web-vue/components/_utils/dom.ts
packages/web-vue/components/anchor/anchor.vue
packages/web-vue/components/anchor/context.ts
packages/web-vue/components/anchor/utils.ts

fix positioning during initialization problem
|  anchor  |    修复加载后不会定位到 hash 位置的问题   | Fix the problem that the hash position will not be located after loading  |                |

fix(anchor): fix positioning during initialization problem

---

packages/web-vue/components/space/README.en-US.md
packages/web-vue/components/space/README.zh-CN.md
packages/web-vue/components/space/__demo__/vertical.md
packages/web-vue/components/space/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/space/space.tsx
packages/web-vue/components/space/style/index.less

|    space       |  新增属性 `fill`             |        add property `fill`       |       Close #328          |

feat(space): add fill property

---

packages/web-vue/components/layout/style/index.less

|    menu       |   修复侧边栏可折叠的时候高度溢出的问题            |    Fix the problem of height overflow when the sidebar is collapsible           |      Close #401           |

fix(layout): the sider overflows when collapse is true

---

packages/web-vue/components/menu/README.en-US.md
packages/web-vue/components/menu/README.zh-CN.md
packages/web-vue/components/menu/__demo__/collapse-control.md
packages/web-vue/components/menu/__demo__/pop-button.md
packages/web-vue/components/menu/__demo__/pop.md
packages/web-vue/components/menu/__demo__/size.md
packages/web-vue/components/menu/__demo__/sub-menu.md
packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/menu/interface.ts
packages/web-vue/components/menu/item.tsx
packages/web-vue/components/menu/style/index.less
packages/web-vue/components/menu/sub-menu-inline.vue
packages/web-vue/components/menu/sub-menu-pop.vue
packages/web-vue/components/menu/sub-menu.tsx

|      menu     |   `sub-menu` 和 `menu-item` 新增 icon 的 slot            |    add icon slot for`sub-menu` and `menu-item`           |       Close #395          |

feat(menu): add icon slot

---

packages/web-vue/components/_hooks/use-resize-observer.ts
packages/web-vue/components/trigger/context.ts
packages/web-vue/components/trigger/trigger.tsx

fix resize & context problem
|  trigger  |   修复容器尺寸变化导致弹出层位置错误的问题   |  Fix the problem of the wrong position of the pop-up layer caused by the change of container size |                |
|  trigger  |   修复嵌套使用中 hover 方式导致弹出层关闭的问题   |   Fix the problem that the pop-up layer is closed due to the hover method in nested use  |      Close #344           |

fix(trigger): fix resize & context problem

---

packages/web-vue/components/input-number/input-number.tsx

fix model-value display problem
|   input-number  |   修复 `model-value` 为 0 时展示错误的问题  |  Fix the problem of displaying errors when `model-value` is 0  |                |

fix(input-number): fix model-value display problem

---

packages/web-vue/components/table/table.tsx

fix fixed table resize
|   table   |  修复固定列模式下，表格尺寸变化导致表头和主体宽度不一致问题  |  Fix the problem of inconsistent width between the header and the main body caused by the change of the table size in the fixed column mode  |   Close #353  |

fix(table): fix fixed table resize

---

packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table-column.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table-th.tsx

|  table |  `columns` 新增 cellStyle 属性  | `columns` added cellStyle property  |  Close #285   |

feat(table): add cellStyle

---

packages/web-vue/components/drawer/style/index.less
packages/web-vue/components/modal/style/index.less

fix(drawer): fix close btn style

---

packages/web-vue/components/upload/README.zh-CN.md
packages/web-vue/components/upload/TEMPLATE.md
packages/web-vue/components/upload/__demo__/avatar.md
packages/web-vue/components/upload/__demo__/basic.md
packages/web-vue/components/upload/__demo__/beforeUpload.md
packages/web-vue/components/upload/__demo__/custom-button.md
packages/web-vue/components/upload/__demo__/custom-icon.md
packages/web-vue/components/upload/__demo__/directory.md
packages/web-vue/components/upload/__demo__/limit.md
packages/web-vue/components/upload/__demo__/onRemove.md
packages/web-vue/components/upload/__demo__/picture-list.md
packages/web-vue/components/upload/__demo__/submit.md
packages/web-vue/components/upload/__demo__/upload-list.md
packages/web-vue/components/upload/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/upload/style/index.less
packages/web-vue/components/upload/upload-button.tsx
packages/web-vue/components/upload/upload-list-item.tsx
packages/web-vue/components/upload/utils.tsx

|      Upload     |     修复 `Upload` 组件上传中的图标位置不对的样式问题         |               |                |
|      Upload     |     修复 `Upload` 组件拖拽上传文件夹时，`beforeUpload` 的第二个参数获取到的不是全部文件的 bug。          |      Fix the bug that the second parameter of `beforeUpload` does not get all the files when the `Upload` component drags and uploads the folder.         |                |
|      Upload     |     修复 `Upload` 组件拖拽上传时，鼠标进入内部文字，拖拽样式闪动的 bug。         |      Fix the bug that the mouse enters the internal text and the drag style flashes when the `Upload` component is dragged and uploaded.         |                |

fix: upload drag directory

---

packages/web-vue/CHANGELOG.md
packages/web-vue/CHANGELOG.zh-CN.md
packages/web-vue/components/upload/context.ts
packages/web-vue/components/upload/upload-list-item.tsx
packages/web-vue/components/upload/upload-list.tsx
packages/web-vue/components/upload/upload-picture-item.tsx
packages/web-vue/components/upload/upload-progress.tsx
packages/web-vue/components/upload/upload.tsx

|  upload   |    新增 `show-remove-buttoon` 、`show-retry-button`、`show-cancel-button` 属性   |  add `show-remove-buttoon` and `show-retry-button` and `show-cancel-button` property  |                |
|  upload   |    新增 `imageLoading` 属性   |  add `imageLoading` property  |                |
|  upload   |    `<a>` 增加 `target`、`download` 属性  |  `<a>` add `target` and `download` props  |                |

feat(upload): add props

---

packages/web-vue/CHANGELOG.md
packages/web-vue/CHANGELOG.zh-CN.md
packages/web-vue/components/upload/context.ts
packages/web-vue/components/upload/upload-list-item.tsx
packages/web-vue/components/upload/upload-list.tsx
packages/web-vue/components/upload/upload-picture-item.tsx
packages/web-vue/components/upload/upload-progress.tsx
packages/web-vue/components/upload/upload.tsx

add download prop
|  upload |  增加 `download` 属性  |  Add `download` attribute  |                |

feat(upload): add download prop

---

packages/web-vue-storybook/stories/components/dropdown.tsx
packages/web-vue-storybook/stories/index.stories.ts
packages/web-vue/components/dropdown/utils.ts
packages/web-vue/components/select/utils.ts

fix JSX render problem
|   dropdown   |  修复使用 JSX 时，Group 不可用的问题  | Fix the problem that Group is unavailable when using JSX  |       |
|   select   |  修复使用 JSX 时，Group 不可用的问题  | Fix the problem that Group is unavailable when using JSX  |       |

fix(dropdown): fix JSX render problem

---

packages/web-vue/components/input-tag/input-tag.tsx

fix input problem
| input-tag |  修复 resize 导致的中文输入失效的问题 |   Fix the problem of Chinese input failure caused by resize   |  Close #426     |

fix(input-tag): fix input problem

---

packages/web-vue/components/_components/resize-observer.tsx

fix nest problem
|  affix  |   修复与 anchor 组件组合使用，显示 warning 的问题   |  Fix the problem of displaying warning when used in combination with the anchor component  |   Close #423      |

fix(resize): fix nest problem

---

packages/web-vue/components/input/README.en-US.md
packages/web-vue/components/input/README.zh-CN.md
packages/web-vue/components/input/__demo__/word-limit.md
packages/web-vue/components/input/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/input/input.tsx
packages/web-vue/components/input/style/index.less
packages/web-vue/components/textarea/README.en-US.md
packages/web-vue/components/textarea/README.zh-CN.md
packages/web-vue/components/textarea/__demo__/word-limit.md
packages/web-vue/components/textarea/textarea.vue

|   input  |   `max-length` 增加 `errorOnly` 属性，增加 `word-slice` 属性   |   `max-length` adds `errorOnly` attribute and `word-slice` attribute   |                |
|   textarea  |   `max-length` 增加 `errorOnly` 属性，增加 `word-slice` 属性   |   `max-length` adds `errorOnly` attribute and `word-slice` attribute   |                |

feat(input): add errorOnly and word-slice

---

packages/web-vue/components/link/link.vue

add click event
|   link  |   增加 click 事件   |  Add click event  |                |

feat(link): add click event

---

packages/web-vue/components/progress/circle.vue
packages/web-vue/components/progress/line.vue
packages/web-vue/components/progress/steps.vue

fix precision problem
|  progress  |   修复显示数值精度问题  |   Fix the display value precision problem   |                |

fix(progress): fix precision problem

---

packages/web-vue/components/upload/upload-button.tsx

render tip on basic type
|   upload   | 修复按钮模式下 tip 没有显示的问题 |  Fix the problem that tip is not displayed in button mode  |  Close #442    |

fix(upload): render tip on basic type

---

packages/web-vue/components/switch/README.en-US.md
packages/web-vue/components/switch/README.zh-CN.md
packages/web-vue/components/switch/TEMPLATE.md
packages/web-vue/components/switch/__demo__/color.md
packages/web-vue/components/switch/__demo__/value.md
packages/web-vue/components/switch/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/switch/__test__/index.test.ts
packages/web-vue/components/switch/switch.vue

add custom value & color
|   switch   |  增加 `checked-value` 和 `unchecked-value` 属性  | Added `checked-value` and `unchecked-value` attributes |  Close #397   |
|   switch   |  增加 `checked-color` 和 `unchecked-color` 属性  |  Added `checked-color` and `unchecked-color` attributes  |  Close #432    |

feat(switch): add custom value & color

---

packages/web-vue/components/badge/__demo__/max.md
packages/web-vue/components/badge/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/badge/badge.tsx

do not render badge when count is 0
|  badge  |  count 为 0 时不再渲染徽标   |  No longer render the logo when count is 0  |    Close #435    |

fix(badge): do not render badge when count is 0

---

packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/__test__/__snapshots__/index.test.ts.snap
packages/web-vue/components/drawer/drawer.vue

add unmount-on-close prop
|  drawer  |  增加 unmount-on-close 属性   | Add unmount-on-close attribute |                |

feat(drawer): add unmount-on-close prop

---

packages/web-vue/components/modal/modal.vue

fix button text problem
|  modal  |  修复按钮内容不能动态修改的问题   |  Fix the problem that the button content cannot be modified dynamically  |  Close #431        |

fix(modal): fix button text problem

---

packages/web-vue/components/modal/README.en-US.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/TEMPLATE.md
packages/web-vue/components/modal/__demo__/form.md
packages/web-vue/components/modal/__demo__/width.md
packages/web-vue/components/modal/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/modal/__test__/__snapshots__/index.test.ts.snap
packages/web-vue/components/modal/index.tsx
packages/web-vue/components/modal/interface.ts
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/modal/style/index.less

add width and top
|   modal  |  修改 wrapper 层展示 modal 的方式，并添加 `width` 和 `top` 属性  |  Modify the way the wrapper layer displays modal, and add the `width` and `top` attributes  |   Close #335     |

feat(modal): add width and top

---

packages/arco-vue-docs/pages/icon/icon-demo.vue
packages/arco-vue-scripts/package.json
packages/arco-vue-scripts/src/scripts/build-style/index.ts
packages/arco-vue-scripts/src/scripts/icongen/svgo.config.ts
packages/arco-vue-scripts/src/scripts/icongen/vue-template.ts
packages/web-vue/components/_utils/vue-utils.ts

add size prop
|  common  |  图标类组件增加 size 属性  |   Icon component adds size attribute   |     Close #336         |

feat(icon): add size prop

---

packages/web-vue/components/table/style/index.less

fix scroll style problem
|   table  |  修复 table 滚动模式下最后一行多余边框的问题  |  Fix the problem of extra border on the last row in table scroll mode  |   Close #332     |

fix(table): fix scroll style problem

---

packages/web-vue/components/upload/upload-button.tsx
packages/web-vue/components/upload/upload.tsx

|  upload    |   修复照片墙模式错误的问题  |  Fix the problem of wrong photo wall mode  |                |

fix(upload): fix error

---

packages/web-vue/components/modal/modal.vue
packages/web-vue/components/modal/style/index.less

fix style problem
|  modal  |  修复 modalStyle 失效的问题  |  Fix the problem of invalid modalStyle  |                |
|  modal  |  修复 flex 布局导致垂直居中且超出高度显示不全的问题  |  Fix the problem that the flex layout causes vertical centering and incomplete display beyond the height  |                |

fix(modal): fix style problem

---

packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker.vue

|     date-picker      |      修复 `readonly` 无效的问题         |    fix the proplem that property `readonly` is invalid           |                |

fix(date-picker): readonly is invalid

---

packages/web-vue/components/grid/README.en-US.md
packages/web-vue/components/grid/README.zh-CN.md
packages/web-vue/components/grid/grid-row.vue
packages/web-vue/components/grid/style/row.less

|   grid        |     `Row` 新增属性 `wrap`          |  add property `wrap` to `Row`             |                |

feat(row): add property `wrap`

---

packages/web-vue/components/descriptions/README.en-US.md
packages/web-vue/components/descriptions/README.zh-CN.md
packages/web-vue/components/descriptions/descriptions.tsx

|     descriptions      |  `value` 和 `label` 插槽增加 index、data 参数         |     The index and data parameters are added to the Value and Label slots        |                |

feat(descriptions): supplement slot params

---

packages/web-vue/components/table/style/index.less
packages/web-vue/components/table/style/token.less
packages/web-vue/components/table/table-col-group.vue
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table-operation-th.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table.tsx

style: opt table style

---

packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/TEMPLATE.md
packages/web-vue/components/cascader/__demo__/basic.md
packages/web-vue/components/cascader/__demo__/check-strictly.md
packages/web-vue/components/cascader/__demo__/clear.md
packages/web-vue/components/cascader/__demo__/format.md
packages/web-vue/components/cascader/__demo__/lazy-load.md
packages/web-vue/components/cascader/__demo__/multiple.md
packages/web-vue/components/cascader/__demo__/path.md
packages/web-vue/components/cascader/cascader-option.tsx
packages/web-vue/components/cascader/cascader-panel.tsx
packages/web-vue/components/cascader/cascader-search-panel.tsx
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/cascader/context.ts
packages/web-vue/components/cascader/hooks/use-selected-path.ts
packages/web-vue/components/cascader/utils.ts

add loadMore prop
|  cascader  |  增加 `load-more` 属性，支持数据懒加载  |   Added `load-more` attribute to support lazy loading of data  |                |

feat(cascader): add loadMore prop

---

packages/web-vue/components/steps/step.vue
packages/web-vue/components/steps/steps.tsx

fix nextError style problem
|  steps |  修复下一步错误连线颜色错误问题  |  Fix the wrong connection color problem in the next step  |                |

fix(steps): fix nextError style problem

---

packages/web-vue/components/table/table.tsx

fix sorter problem
|  table  |  修复 `sortOrder ` 置空失效的问题  |  Fix the problem of invalid `sortOrder` emptying  |   Close #425   |
|  table  |  修复 `expand-icon` 插槽在子树中不生效的问题  |  Fix the issue that the `expand-icon` slot does not take effect in the subtree  |                |
|  table  |  修复固定列在表格尺寸动态变化时阴影不显示的问题  |   Fix the problem that the shadow of the fixed column does not display when the table size changes dynamically   |                |

fix(table): fix sorter problem

---

packages/web-vue/components/form/form-item-message.vue
packages/web-vue/components/form/utils.ts

fix help error
|  form  |   修复表单项 help 内容显示错误的问题   |  Fix the problem that the help content of the form item is displayed incorrectly  |   Close #438   |

fix(form): fix help error

---

packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/select/__demo__/group.md
packages/web-vue/components/select/__demo__/search.md

fix composition problem
|  input-tag  |  修复中文输入法问题  |  Fix Chinese input method problem  |                |
|  select  |  修复搜索时中文输入法问题  |  Fix the problem of Chinese input method when searching  |                |
|  select  |  修复在 `drawer` 中 placeholder 显示不全的问题  |   Fix the incomplete display of placeholder in `drawer`  |  Close #462     |

fix(input-tag): fix composition problem

---

packages/web-vue/components/upload/context.ts
packages/web-vue/components/upload/upload-list-item.tsx
packages/web-vue/components/upload/upload.tsx

add showLink prop
|   upload  |  增加 `show-link` 属性  |  Add `show-link` attribute  |   #369    |

feat(upload): add showLink prop

---

packages/web-vue/components/auto-complete/auto-complete.tsx
packages/web-vue/components/mention/mention.tsx
packages/web-vue/components/mention/style/index.less
packages/web-vue/components/mention/style/index.ts
packages/web-vue/components/mention/style/token.less
packages/web-vue/components/textarea/textarea.vue

add input slots & option slot
|  auto-complete  |  增加 input 中的插槽和 option 插槽支持   |  Increase input slot and option slot support  |   Close #461    |
|  mention  |  增加 input 中的插槽和 option 插槽支持   |  Increase input slot and option slot support  |                |
|  mention  |  文本域类型下的下拉菜单跟随提示文字显示   |  The drop-down menu under the text field type is displayed following the prompt text  |                |

feat(auto-complete): add input slots & option slot

---

packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/TEMPLATE.md
packages/web-vue/components/table/__demo__/expand.md
packages/web-vue/components/table/__demo__/fixed.md
packages/web-vue/components/table/__demo__/lazy-load.md
packages/web-vue/components/table/__demo__/sort.md
packages/web-vue/components/table/context.ts
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/style/index.less
packages/web-vue/components/table/style/token.less
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table-th.tsx
packages/web-vue/components/table/table.tsx

add loadMore & alignLeft
|   table  |   增加 `loadMore` 属性，支持子树懒加载  |  Added `loadMore` property to support sub-slacker loading  |   Close #79       |
|   table  |   增加 `filterIconAlignLeft` 属性  |  Add `filterIconAlignLeft` property |                |
|   table  |   增加 `change` 事件，可获取处理后数据  |  Added `change` event to get processed data  |   Close #281,  Close #479   |

feat(table): add loadMore & alignLeft

---

packages/web-vue/components/form/README.en-US.md
packages/web-vue/components/form/README.zh-CN.md
packages/web-vue/components/form/TEMPLATE.md
packages/web-vue/components/form/__demo__/auto-width.md
packages/web-vue/components/form/__demo__/extra.md
packages/web-vue/components/form/__demo__/grid.md
packages/web-vue/components/form/__demo__/nest.md
packages/web-vue/components/form/context.ts
packages/web-vue/components/form/form-item-label.vue
packages/web-vue/components/form/form-item-message.vue
packages/web-vue/components/form/form-item.tsx
packages/web-vue/components/form/form.vue
packages/web-vue/components/form/style/index.less
packages/web-vue/components/form/style/status.less
packages/web-vue/components/form/style/token.less
packages/web-vue/components/form/utils.ts

add autoWidth & labelFlex & mergeProps prop
|  form  |   增加 `autoLabelWidth` 属性，支持标签宽度自适应   |   Added `autoLabelWidth` property to support adaptive label width   |                |
|  form  |   增加 `labelColFlex` 属性，支持标签宽度设置   |  Added `labelColFlex` property to support label width setting  | Close #473           |
|  form  |   增加 `mergeProps` 属性，支持自定义属性和事件覆写 |  Add `mergeProps` attribute, support custom attributes and event override  |  Close #188   |

feat(form): add autoWidth & labelFlex & mergeProps prop

---

packages/web-vue/components/pagination/__demo__/custom.md
packages/web-vue/components/pagination/page-jumper.vue

fix jumper problem
|   pagination  |  修复跳转输入框失焦时没有清除值的问题  |  Fix the problem that there is no clear value when the jump input box is out of focus   |                |

fix(pagination): fix jumper problem

---

packages/arco-vue-docs/components/article/style.less
packages/arco-vue-docs/components/aside-nav/index.vue
packages/arco-vue-docs/docs/pro/build.en-US.md
packages/arco-vue-docs/docs/pro/build.zh-CN.md
packages/arco-vue-docs/docs/pro/directory.en-US.md
packages/arco-vue-docs/docs/pro/directory.zh-CN.md
packages/arco-vue-docs/docs/pro/i18n.en-US.md
packages/arco-vue-docs/docs/pro/i18n.zh-CN.md
packages/arco-vue-docs/docs/pro/layout.en-US.md
packages/arco-vue-docs/docs/pro/layout.zh-CN.md
packages/arco-vue-docs/docs/pro/mock.en-US.md
packages/arco-vue-docs/docs/pro/mock.zh-CN.md
packages/arco-vue-docs/docs/pro/npm-scripts.en-US.md
packages/arco-vue-docs/docs/pro/npm-scripts.zh-CN.md
packages/arco-vue-docs/docs/pro/routes-and-menu.en-US.md
packages/arco-vue-docs/docs/pro/routes-and-menu.zh-CN.md
packages/arco-vue-docs/docs/pro/start.en-US.md
packages/arco-vue-docs/docs/pro/start.zh-CN.md
packages/arco-vue-docs/docs/pro/state-management.en-US.md
packages/arco-vue-docs/docs/pro/state-management.zh-CN.md
packages/arco-vue-docs/locale/en-us.js
packages/arco-vue-docs/locale/zh-cn.js
packages/arco-vue-docs/router.ts

docs: add the docs of pro

---

packages/web-vue/components/statistic/countdown.vue
packages/web-vue/components/statistic/statistic.vue

fix value problem
|  statistic  |  value 值支持响应式修改  |  value supports responsive modification  |     Close #512      |

fix(statistic): fix value problem

---

packages/web-vue/components/drawer/drawer.vue

add hide title
|  drawer  |  当没有设置 title 和 closable 时，隐藏标题栏  |  Hide the title bar when title and closable are not set  |   Close #474   |

feat(drawer): add hide title

---

packages/web-vue/components/input/input.tsx

fix change & attr problem
|   input  |  修复 change 事件触发问题  |  Fix change event trigger issue |                |
|   input  |  修复当存在前后置标签时，样式设置位置错误的问题  |  Fix the problem that the style setting is in the wrong position when there are front and rear tags |                |

fix(input): fix change & attr problem

---

packages/web-vue/components/upload/__demo__/picture-card.md
packages/web-vue/components/upload/style/index.less
packages/web-vue/components/upload/upload-button.tsx
packages/web-vue/components/upload/upload-list.tsx
packages/web-vue/components/upload/upload.tsx

add imagePreview prop
|   upload   |   增加 imagePreview 属性，可以使用内置图片预览功能   |  Increase the imagePreview property, you can use the built-in image preview function   |   Close #369    |
|   upload   |   当 `listType` 为图片类时，默认设置 accept 为 `image/*`  |  When `listType` is an image class, the default accept is `image/*`   |   Close #441    |
|   upload   |   增加 `showOnExceedLimit` 属性   |  Added `showOnExceedLimit` prop   |   Close #465              |

feat(upload): add imagePreview prop

---

packages/web-vue/components/trigger/trigger.tsx
packages/web-vue/components/trigger/utils.ts

fix arrow position problem
|  trigger  |  修复某些情况下弹出框箭头位置错误的问题  |   Fix the problem that the arrow position of the popup box is wrong in some cases   |                |

fix(trigger): fix arrow position problem

---

packages/web-vue/components/table/table.tsx

add hideExpandButtonOnEmpty prop
|    table   |  增加 hideExpandButtonOnEmpty 属性    |    Add hideExpandButtonOnEmpty property    |  Close #503    |

feat(table): add hideExpandButtonOnEmpty prop

---

.yarnrc.yml
packages/arco-vue-scripts/copy-template.js
packages/arco-vue-scripts/package.json
packages/web-vue/package.json
yarn.lock

fix init problem on windows
Close #493 

fix: fix init problem on windows

---

packages/web-vue/components/message/README.zh-CN.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/notification/README.zh-CN.md

修正文档中错别字“一下”为“以下”

---

packages/arco-vue-docs/router.ts

docs: progress show error

---

packages/web-vue/components/list/style/index.less

|    list       |  `split` 样式在 `bodered` 为 `false`的时候失效             |      the style of `split` invalid when `bordered` is `false`         |                |

fix(list): split invalid when bordered is false

---

packages/web-vue/components/image/image.vue

|     image      |    `Image.PreviewGroup` 应该优先收集 `previewProps.src`           |   the`Image.PreviewGroup` component should collect `previewProps.src` first            |                |

fix(image): the group component should collect previewProps.src first

---

packages/arco-vue-docs/app.vue
packages/arco-vue-docs/style/index.less

feat: add global notice

---

packages/web-vue/components/_components/input-label/style/index.ts
packages/web-vue/components/_components/select-view/style/index.ts
packages/web-vue/components/cascader/README.en-US.md
packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/form/style/index.less
packages/web-vue/components/input/style/input.less
packages/web-vue/components/select/README.en-US.md
packages/web-vue/components/select/README.zh-CN.md
packages/web-vue/components/select/base-select.tsx
packages/web-vue/components/steps/__demo__/dot.md
packages/web-vue/components/steps/steps.tsx
packages/web-vue/components/table/style/index.less
packages/web-vue/components/textarea/textarea.vue
packages/web-vue/components/upload/upload.tsx

fix style problem
|   steps  |   修复 dot 模式下可以开启 small 的问题   |   Fix the problem that small can be enabled in dot mode  |                |
|   form  |   label-col 改用 flex 布局，解决 mini 尺寸下高度错误的问题   |   Label-col uses flex layout to solve the problem of wrong height under mini size  |                |
|   table  |   修复 table 内容超出容器，导致某些情况下边框不显示的问题   |   Fix the problem that the table content exceeds the container, causing the border not to be displayed in some cases  |   Close #528   |
|   select  |   修复按需加载没有导入样式的问题   |   Fix on-demand loading without imported styles  |   Close #531    |
|   input  |   修复在 Safari 浏览器下 disabled 状态字体颜色错误的问题   |   Fix the problem of wrong …

fix: fix style problem

---

packages/web-vue/components/message/README.zh-CN.md
packages/web-vue/components/message/TEMPLATE.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/TEMPLATE.md
packages/web-vue/components/notification/README.zh-CN.md
packages/web-vue/components/notification/TEMPLATE.md

Correct typos "一下" to "以下"

---

packages/web-vue/components/statistic/statistic.vue

fix animation problem
|  statistic  |  修复动态赋值问题  |   fix dynamic assignment issue   |                |

fix(statistic): fix animation problem

---

packages/web-vue/components/button/style/index.less

fix only-icon style
|  button  |  修复 onlyIcon 模式图标未对齐问题  |   Fix onlyIcon mode icons not aligned   |                |

fix(button): fix only-icon style

---

packages/arco-vue-docs/docs/pro/build.en-US.md
packages/arco-vue-docs/docs/pro/build.zh-CN.md
packages/arco-vue-docs/docs/pro/directory.zh-CN.md
packages/arco-vue-docs/docs/pro/i18n.en-US.md
packages/arco-vue-docs/docs/pro/i18n.zh-CN.md
packages/arco-vue-docs/docs/pro/layout.en-US.md
packages/arco-vue-docs/docs/pro/layout.zh-CN.md
packages/arco-vue-docs/docs/pro/mock.en-US.md
packages/arco-vue-docs/docs/pro/mock.zh-CN.md
packages/arco-vue-docs/docs/pro/npm-scripts.zh-CN.md
packages/arco-vue-docs/docs/pro/routes-and-menu.en-US.md
packages/arco-vue-docs/docs/pro/routes-and-menu.zh-CN.md
packages/arco-vue-docs/docs/pro/start.en-US.md
packages/arco-vue-docs/docs/pro/start.zh-CN.md
packages/arco-vue-docs/docs/pro/state-management.en-US.md
packages/arco-vue-docs/docs/pro/state-management.zh-CN.md
yarn.lock

docs: fix pro docs problem

---

packages/web-vue/components/_components/virtual-list/hooks/use-scroll-to.ts
packages/web-vue/components/_components/virtual-list/interface.ts
packages/web-vue/components/_components/virtual-list/virtual-list.vue
packages/web-vue/components/_hooks/use-options.tsx

|     select      |       调用虚拟列表的 `scrollTo` 函数时缺失了参数        |      missing arguments when calling scrollTo         |                |

fix(select): missing arguments when calling scrollTo

---

packages/arco-vue-docs/docs/pro/directory.en-US.md
packages/arco-vue-docs/docs/pro/directory.zh-CN.md

docs: remove duplicate lines

---

packages/web-vue/components/button/button.vue
packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input-number/style/index.less
packages/web-vue/components/input/input-search.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/input/style/group.less
packages/web-vue/components/input/style/password.less
packages/web-vue/components/input/style/search.less
packages/web-vue/components/input/style/size.less

fix input-search & input-number problem
|  input  |  修复 input-search 在 button 模式属性失效的问题  |  Fix the problem that the input-search attribute is invalid in button mode  |   Close #549    |
|  input-number  |   修复输入时光标位置改变的问题  |  Fix the problem that the cursor position changes when inputting   |   Close #544  |

fix(input): fix input-search & input-number problem

---

packages/web-vue/components/time-picker/time-column.vue

fix(time-column): fix types

---

packages/web-vue/components/_components/dropdown/dropdown-panel.vue
packages/web-vue/components/_components/dropdown/style/index.less
packages/web-vue/components/select/__demo__/loading.md
packages/web-vue/components/select/base-select.tsx

chore loading state
|  select  |  优化加载中状态显示  |  Optimize loading status display  |   Close #542    |

feat(select): chore loading state

---

packages/web-vue/components/cascader/README.en-US.md
packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/TEMPLATE.md
packages/web-vue/components/cascader/__demo__/loading.md
packages/web-vue/components/cascader/cascader-panel.tsx
packages/web-vue/components/cascader/cascader-search-panel.tsx
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/cascader/style/index.less

add loading state
|   cascader  |  增加 loading 属性   |    Add loading prop    |                |

feat(cascader): add loading state

---

packages/web-vue/components/input/style/input.less

fix background-color error in dark mode
| input |  修复暗黑模式下背景颜色错误的问题  |  Fix the problem of wrong background color in dark mode  |   Close #556    |

fix(input): fix background-color error in dark mode

---

packages/web-vue/components/button/style/index.less

|   button  |   修复按钮组中 iconOnly 按钮的对齐问题  |  Fix alignment of iconOnly buttons in button groups   |   Close #564    |

fix(button): fix button group align problem

---

packages/web-vue/components/_components/dropdown/dropdown-option.vue
packages/web-vue/components/cascader/cascader-option.tsx
packages/web-vue/components/checkbox/checkbox.vue
packages/web-vue/components/radio/radio.vue
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table-operation-th.tsx
packages/web-vue/components/table/table-th.tsx
packages/web-vue/components/transfer/transfer-list-item.tsx
packages/web-vue/components/transfer/transfer-view.vue
packages/web-vue/components/tree/base-node.vue

perf select used with checkbox-group
|  common  |  优化组件内置的选择框不会受到外部选择框组的控制  |    The select box built into the optimization component will not be controlled by the external select box group   |   Close #540    |

perf(select): perf select used with checkbox-group

---

packages/web-vue/components/tag/tag.vue

fix checkable class name error
|   tag   |    修复 checkable 状态样式错误的问题    |   Fix checkable state style bug  |                |

fix(tag): fix checkable class name error

---

packages/web-vue/components/table/__demo__/sort.md
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table.tsx

add sorter boolean support
|  table  | `sortable.sorter` 增加 boolean 类型，支持服务器端排序 |  `sortable.sorter` adds boolean type to support server-side sorting  |   Close #572   |

feat(table): add sorter boolean support

---

packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/modal/README.en-US.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/interface.ts
packages/web-vue/components/modal/modal.vue

add escToClose support
|   modal  |  增加 `escToClose` 属性并默认开启  |  Added `escToClose` property and enabled by default  |   Close #421    |
|   drawer  |  增加 `escToClose` 属性并默认开启  |  Added `escToClose` property and enabled by default  |     Close #533 |

feat(modal): add escToClose support

---

packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/pickers/date-picker.tsx
packages/web-vue/components/date-picker/pickers/month-picker.tsx
packages/web-vue/components/date-picker/pickers/quarter-picker.tsx
packages/web-vue/components/date-picker/pickers/week-picker.tsx
packages/web-vue/components/date-picker/pickers/year-picker.tsx
packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/components/time-picker/utils/index.ts

- [] Typescript definition change
|      date-picker     |      修复事件参数缺失的问题         |       fix the problem of missing event parameters        |                |

fix(date-picker): fix the event params of date-picker

---

packages/web-vue/components/switch/style/index.less
packages/web-vue/components/switch/switch.vue

style: add switch token

---

packages/web-vue/components/grid/__demo__/grid.md
packages/web-vue/components/grid/index.ts

fix install name
|  grid  |   修复组件名注册错误问题   |   Fix component name registration error problem   |                |

fix(grid): fix install name

---

packages/arco-vue-scripts/src/scripts/icongen/index.ts

fix: check data property in optimizedSvg

---

packages/web-vue/components/input/README.en-US.md
packages/web-vue/components/input/README.zh-CN.md
packages/web-vue/components/input/TEMPLATE.md
packages/web-vue/components/input/__demo__/search-button.md
packages/web-vue/components/input/__demo__/status.md
packages/web-vue/components/input/input-search.tsx

|   input   |  `<input-search>` 组件增加自定义搜素按钮内容的功能  |   The `<input-search>` component adds the ability to customize the content of the search button  |  Close #597  |

feat(input): input-search support button slots

---

packages/web-vue/components/_components/feedback-icon.vue
packages/web-vue/components/_components/select-view/select-view.tsx
packages/web-vue/components/_components/select-view/style/index.less
packages/web-vue/components/form/README.en-US.md
packages/web-vue/components/form/README.zh-CN.md
packages/web-vue/components/form/TEMPLATE.md
packages/web-vue/components/form/__demo__/status.md
packages/web-vue/components/form/form-item.tsx
packages/web-vue/components/form/style/status.less
packages/web-vue/components/input-number/style/index.less
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/input/style/input.less
packages/web-vue/components/input/style/token.less

add feedback icon
|  form  |  增加表单和相应输入组件的反馈图标功能  |  Added feedback icon function for forms and corresponding input components  |   Close #464     |

feat: add feedback icon

---

packages/web-vue/components/input/style/group.less

|  input  |  修复 `<input-group>` 组件包裹 `<select>` 组件的样式问题  | Fix `<input-group>` component wrapping `<select>` component style issue  |    Close #598     |

fix(input): fix input-group style problem

---

packages/web-vue/components/typography/base.tsx
packages/web-vue/components/typography/interface.ts

|   typography  | 修复 JSX 使用中存在警告的问题   |  Fix the problem of warning in JSX usage  |   Close #235   |

fix(typography): move slots.default() to render

---

packages/web-vue/components/split/README.en-US.md
packages/web-vue/components/split/README.zh-CN.md
packages/web-vue/components/split/__demo__/basic.md
packages/web-vue/components/split/__demo__/nested.md
packages/web-vue/components/split/interface.ts
packages/web-vue/components/split/split.vue

|     split      |      属性 `min` `max` 支持设置 px         |      Attributes `min` and `max` support setting pixel values        |                close #585  |

feat(split): attributes `min` and `max` support setting pixel values

---

packages/web-vue/components/popconfirm/README.en-US.md
packages/web-vue/components/popconfirm/README.zh-CN.md
packages/web-vue/components/popconfirm/TEMPLATE.md
packages/web-vue/components/popover/README.en-US.md
packages/web-vue/components/popover/README.zh-CN.md
packages/web-vue/components/popover/TEMPLATE.md
packages/web-vue/components/select/__demo__/basic.md
packages/web-vue/components/tooltip/README.en-US.md
packages/web-vue/components/tooltip/README.zh-CN.md
packages/web-vue/components/tooltip/TEMPLATE.md

docs: add some tip

---

packages/web-vue/components/date-picker/README.en-US.md
packages/web-vue/components/date-picker/README.zh-CN.md
packages/web-vue/components/date-picker/hooks/use-format.ts
packages/web-vue/components/date-picker/hooks/use-value-format.ts
packages/web-vue/components/date-picker/interface.ts
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/pickers/date-picker.tsx
packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/components/time-picker/utils/index.ts

|     date-picker      |      增加属性 `value-format` 用于格式化返回值         |        Added attribute `value-format` to format the return value       |    Close #508     |

feat(date-picker): add property `value-format`

---

packages/web-vue/components/_components/picker/input-range.vue
packages/web-vue/components/_components/picker/input.vue
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker.vue

|    date-picker       |       点击清除按钮的时候不要展开弹出层        |      do not open the popup when clear         |    close #596          |

feat(date-picker): do not open the popup when clear

---

packages/web-vue/components/typography/README.en-US.md
packages/web-vue/components/typography/README.zh-CN.md
packages/web-vue/components/typography/base.tsx
packages/web-vue/components/typography/interface.ts

|     typography      |     新增属性 `copy-delay` 用于自定义复制成功状态消失的延迟时间          |     add property `copy-delay` support customize the delay time for the disappearance of copy success status          |    close #618             |

feat(typography): add property `copyDelay`

---

packages/web-vue/components/cascader/README.en-US.md
packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/select/README.en-US.md
packages/web-vue/components/select/README.zh-CN.md
packages/web-vue/components/select/base-select.tsx

add icon slots
|   select   |  增加自定义图标插槽   |   Added custom icon slot   |   Close #582   |

feat(select): add icon slots

---

packages/web-vue/components/message/message-list.tsx
packages/web-vue/components/message/message.vue
packages/web-vue/components/modal/style/index.ts

fix message type problem
|  message  |   修复使用 loading 类型时类型警告的问题  |  fix type warning when using loading type   |    Close #620    |
|  modal  |   修复样式文件缺少 `<button>` 组件样式引用的问题  |  Fix style file missing `<button>` component style reference   |    Close #587             |

fix(message): fix message type problem

---

packages/web-vue/components/button/style/index.less

|   button  |  修复链接模式文字未居中的问题  |  Fix link mode text not centered  |   Close #611   |

fix(button): fix button href type text align

---

packages/arco-vue-docs-navbar/package.json
packages/arco-vue-docs-navbar/src/index.less
packages/web-vue/components/dropdown/README.en-US.md
packages/web-vue/components/dropdown/README.zh-CN.md
packages/web-vue/components/dropdown/TEMPLATE.md
packages/web-vue/components/dropdown/__demo__/button.md
packages/web-vue/components/dropdown/dropdown-button.vue
packages/web-vue/components/dropdown/dropdown.vue
yarn.lock

add dropdown props
|  dropdown |   `<dropdown-button>` 组件补全 dropdown 相关属性  |   `<dropdown-button>` component completes dropdown related properties    |                |

fix(dropdown): add dropdown props

---

packages/web-vue/components/input/style/group.less
packages/web-vue/components/input/style/index.less

|   input   |   修复 `input-group` 中使用 input 组件圆角问题    |   Fix `input-group` with rounded corners of input components   |                |

fix(input): fix input-group style

---

packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table.tsx

|   table  |  修复阻止冒泡导致懒加载失效的问题        |   Fix the problem of preventing bubbling and causing lazy loading to fail  |                |

fix(table): fix lazy load problem

---

packages/web-vue/components/icon-component/icon.vue

|   common  |  自定义 icon 组件增加 fill 属性，解决自定义颜色问题  |   Add the fill attribute to the custom icon component to solve the problem of custom color   |                |

fix(icon): add fill attr

---

packages/web-vue/components/date-picker/picker.vue

|     date-picker      |      `headerValue` 在 `vue 3.2.28` 中报错         |         `headerValue` reporting error in `vue 3.2.28`      |                |

fix(date-picker): `headerValue` reporting error in `vue 3.2.28`

---

packages/web-vue/components/trigger/utils.ts

fix auto-fit arrow position
|  trigger  |   优化自动调整位置后箭头的位置   |   Optimize the position of the arrow after auto-adjusting the position  |    Close #601    |

fix(trigger): fix auto-fit arrow position

---

packages/web-vue/components/switch/style/index.less

fix turn on style problem
|  switch  |  修复开关动画偶现抖动问题  |   Fixed the occasional jitter problem of switch animation   |   Close #546   |

fix(switch): fix turn on style problem

---

packages/web-vue/components/transfer/transfer-view.vue

use option label to search
|  transfer  |  修复搜索功能应该检查选项的问题  |  Fix search function should check option label  |                |

fix(transfer): use option label to search

---

packages/web-vue/components/_utils/constant.ts

|   input   |   增加 input 元素部分原始属性的透传   |   Increase the transparent transmission of some original attributes of the input element   |   Close #663   |

perf(input): add input attrs

---

packages/web-vue/components/image/style/preview.less

|      image     |  修复操作项的 `Tooltip` 被遮盖的问题      |       Fix the problem that the `Tooltip` of the action item is covered        |         Close #644        |

fix(image): the Tootip of Action has a wrong `zindex`

---

packages/arco-vue-docs/docs/pro/mock.en-US.md
packages/arco-vue-docs/docs/pro/mock.zh-CN.md

docs: jump link correction

---

packages/web-vue/components/modal/modal.vue
packages/web-vue/components/modal/style/index.less

add title align prop
|  modal  |  增加 `title-align` 属性  |  Added `title-align` attribute  |   Close #614    |

feat(modal): add title align prop

---

packages/web-vue/components/tooltip/style/index.ts

fix lost trigger style problem
|  tooltip  |   修复按需加载时丢失 trigger 样式的问题   |  Fix the issue of losing trigger style when loading on demand  |   Close #666     |

fix(tooltip): fix lost trigger style problem

---

packages/web-vue/components/image/preview.vue

|     image      |      修复旋转方向错误的问题         |     Fix the problem of wrong rotation direction          |     Close #644            |

fix(image): wrong direction of rotation

---

packages/arco-vue-docs/docs/pro/permission.en-US.md
packages/arco-vue-docs/docs/pro/permission.zh-CN.md
packages/arco-vue-docs/docs/pro/routes-and-menu.en-US.md
packages/arco-vue-docs/docs/pro/routes-and-menu.zh-CN.md
packages/arco-vue-docs/locale/en-us.js
packages/arco-vue-docs/locale/zh-cn.js
packages/arco-vue-docs/router.ts

docs: add vue pro permission control docs

---

packages/web-vue/components/_hooks/use-responsive.ts
packages/web-vue/components/layout/sider.vue
packages/web-vue/components/menu/README.en-US.md
packages/web-vue/components/menu/README.zh-CN.md
packages/web-vue/components/menu/TEMPLATE.md
packages/web-vue/components/menu/__demo__/breakpoint.md
packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/menu/base-menu.vue
packages/web-vue/components/menu/interface.ts

|      menu     |       支持响应式收缩        |       Responsive collapsed support        |      close #500          |

feat(menu): support responsive breakpoint

---

packages/arco-vue-scripts/src/scripts/docgen/index.ts

feat(script-docgen): add component desc

---

packages/web-vue/components/cascader/__demo__/check-strictly.md
packages/web-vue/components/cascader/cascader-option.tsx
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/checkbox/checkbox.vue

fix check-strictly problem
|   cascader  |   修复严格模式下禁用项仍可通过单选选择器选择的问题  |  Fixed an issue where disabled items could still be selected via radio selectors in strict mode  |  Close #669    |
|   cascader  |   修复严格模式下搜索结果没有包含路径选项的问题  |  Fixed an issue where search results in strict mode did not include path options  |   Close #649    |

fix(cascader): fix check-strictly problem

---

packages/web-vue/components/message/index.ts
packages/web-vue/components/notification/index.ts

|  message  |  修复同时调用时，出现销毁报错的问题   |   Fixed the problem of destroying an error when calling at the same time   |    Close #657 , Close #686   |

fix(message): fix destroy problem

---

packages/web-vue/components/upload/upload.tsx
packages/web-vue/components/upload/utils.tsx

only generate image when image type
|   upload  |   仅在文件类型为图片时生成初始预览图片   |   Generate initial preview image only if file type is image   |   Close #702    |

fix(upload): only generate image when image type

---

packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/TEMPLATE.md
packages/web-vue/components/tree/__demo__/node-icon.md
packages/web-vue/components/tree/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/tree/base-node.vue
packages/web-vue/components/tree/context.ts
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/tree.vue

|      tree     |    新增插槽 `icon` 用于全局定制节点图标           |   Add slot `icon` for customizing node icon globally            |                close #696  |

feat(tree): add icon slot

---

packages/web-vue/components/_components/virtual-list/hooks/use-render-children.tsx
packages/web-vue/components/_components/virtual-list/interface.ts
packages/web-vue/components/_components/virtual-list/utils/index.ts
packages/web-vue/components/_components/virtual-list/virtual-list.vue
packages/web-vue/components/table/table.tsx

|    virtual-list       |     修复在滚动条显示和隐藏的边界情况下数据变化没有更新视图的问题          |      Fixed an issue where data changes did not update the view in the border case where the scroll bar was shown and hidden         |         close #704        |
|    virtual-list       |     修复行高计算没有包含边框的问题         |     Fix the problem that the row height calculation does not include the border          |      close #703           |

fix(virtual-list): view not update & itemHeight is wrong

---

packages/web-vue/components/upload/upload-list.tsx

|     upload      |      修复使用插槽 `upload-item` 报错的问题         |     fix error when using slot `upload-item`          |          |

fix(upload): fix error when using slot `upload-item`

---

packages/web-vue/components/cascader/cascader.vue

|  cascader  |  修复选项更新后选择框展示没有更新的问题  |  Fix the problem that the selection box display is not updated after the option is updated   |      Close #712           |

fix(cascader): fix option update problem

---

packages/web-vue/components/_hooks/use-index.ts
packages/web-vue/components/grid/grid-item.vue
packages/web-vue/components/select/README.en-US.md
packages/web-vue/components/select/README.zh-CN.md
packages/web-vue/components/select/TEMPLATE.md
packages/web-vue/components/select/__demo__/remote.md
packages/web-vue/components/select/hooks/use-options.ts
packages/web-vue/components/select/hooks/use-select.ts
packages/web-vue/components/select/option.vue
packages/web-vue/components/select/select.tsx

|  select  |  增加 `search-delay` 属性，并默认为 `500ms`  |  Added `search-delay` property and defaulted to `500ms`  |                |

feat(select): add search delay

---

packages/web-vue/components/_hooks/use-input.ts
packages/web-vue/components/cascader/README.en-US.md
packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/cascader-option.tsx
packages/web-vue/components/cascader/cascader-search-panel.tsx
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/cascader/context.ts
packages/web-vue/components/cascader/utils.ts

|   cascader  |   增加 `search-delay` 属性，并默认为 `500ms`  |   Added `search-delay` property and defaulted to `500ms`   |                |
|   cascader  |   增加 `search-option-only-label` 属性，并修改搜索下拉菜单中的选项默认展示路径标签  |   Add the `search-option-only-label` attribute and modify the default display path label of the options in the search drop-down menu   |   Close #668        |

feat(cascader): add search delay

---

packages/web-vue/components/trigger/trigger.tsx

|  trigger  |  增加 `show` 和 `hide` 事件  |  Added `show` and `hide` events  |                |

feat(trigger): add show/hide event

---

packages/web-vue/components/_components/resize-observer-v2.vue
packages/web-vue/components/trigger/__demo__/arrow.md
packages/web-vue/components/trigger/trigger.tsx
packages/web-vue/components/trigger/utils.ts

|  trigger  |   弹出层增加一层 `wrapper div` 用来提供对tranform动画的支持   |  Add a layer of `wrapper div` to the pop-up layer to provide support for tranform animation  |                |

chore(trigger): add wrapper div for support transform animate

---

packages/web-vue/components/_components/resize-observer-v2.vue
packages/web-vue/components/popconfirm/popconfirm.vue
packages/web-vue/components/popover/popover.vue
packages/web-vue/components/tooltip/tooltip.vue
packages/web-vue/components/trigger/__demo__/arrow.md
packages/web-vue/components/trigger/trigger.tsx
packages/web-vue/components/trigger/utils.ts

|   tooltip  |   优化显示动画，同 react 版本保持一致   |  Optimized display animation, consistent with the react version   |                |
|   popover  |   优化显示动画   |  Optimize display animation   |                |
|   popconfirm  |   优化显示动画   |  Optimize display animation   |                |

perf(tooltip): add animate

---

packages/web-vue/components/table/utils.ts

|   table  |   修复 table-column 嵌套使用时，v-for 不能渲染的问题     |  Fix the problem that v-for cannot render when table-column is nested  |   Close #723   |

fix(table): fix table-column nest problem

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/__demo__/span.md
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table.tsx

|   table    |   增加 `span-all`  属性   |  Added `span-all` attribute  |  Close #469    |

feat(table): add span-all prop

---

packages/web-vue/components/pagination/style/index.less

|   pagination  |   修复在safari下跳转器文字没有对齐的问题   | Fix the problem that the jumper text is not aligned under safari  |                |

fix(pagination): fix style error in safari

---

packages/web-vue/components/modal/index.tsx
packages/web-vue/components/modal/modal.vue

|   modal  | 优化点击遮罩层关闭  |  Optimize click mask layer off  | Close #707   |

perf(modal): perf click mask to close

---

packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/select/select.tsx

|  input  |   modelValue 支持 null   |   modelValue support null            |     Close #741            |

perf(input): support value null

---

packages/web-vue/components/list/list.tsx
packages/web-vue/components/list/style/index.less
packages/web-vue/components/transfer/transfer-view.vue
packages/web-vue/components/transfer/transfer.vue

|  transfer  |  修复列表显示问题  |   Fix list display issue   |   Close #742    |

fix(transfer): fix style problem

---

packages/web-vue/components/menu/style/index.less

|   menu        |       菜单项的图标没有垂直居中        |  the icon of sub-menu are not centered in vertically             |     close #761            |

fix(menu): the icon of sub-menu are not centered in vertically

---

packages/web-vue/components/date-picker/hooks/use-format.ts
packages/web-vue/components/date-picker/hooks/use-header-value.ts
packages/web-vue/components/date-picker/panels/date/index.vue
packages/web-vue/components/date-picker/panels/header.vue
packages/web-vue/components/date-picker/panels/month/index.vue
packages/web-vue/components/date-picker/panels/quarter/index.vue
packages/web-vue/components/date-picker/picker-panel.vue
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/style/index.less
packages/web-vue/components/date-picker/style/token.less

|      date-picker     |       支持在头部快捷切换年月        |        support quick switching of year and month in the head       |      close #616 close #586          |

feat(date-picker): support quick switching of year and month in the head

---

packages/arco-vue-docs/docs/pro/directory.en-US.md
packages/arco-vue-docs/docs/pro/directory.zh-CN.md

docs(directory): fix the description of the directory for arco-design-pro-vue

docs(directory): fix the description of the directory for arco-design-pro-vue

---

packages/arco-vue-docs/docs/pro/directory.en-US.md
packages/arco-vue-docs/docs/pro/directory.zh-CN.md
packages/arco-vue-docs/docs/pro/start.en-US.md
packages/arco-vue-docs/docs/pro/start.zh-CN.md

docs: pro document update

---

packages/web-vue/components/_utils/get-value-by-path.ts
packages/web-vue/components/form/form-item.vue

|  form  |   修复嵌套数据中重置方法失效的问题  |  Fix the problem of reset method invalid in nested data  |  Close #752               |

fix(form): fix path field error

---

packages/web-vue/components/rate/README.en-US.md
packages/web-vue/components/rate/README.zh-CN.md
packages/web-vue/components/rate/TEMPLATE.md
packages/web-vue/components/rate/__demo__/color.md
packages/web-vue/components/rate/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/rate/rate.tsx

|   rate  |   增加 color 属性  |   Add color attribute  |   Close #440              |

feat(rate): add color prop

---

packages/web-vue/components/steps/TEMPLATE.md
packages/web-vue/components/steps/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/steps/context.ts
packages/web-vue/components/steps/index.ts
packages/web-vue/components/steps/interface.ts
packages/web-vue/components/steps/step.vue
packages/web-vue/components/steps/steps.vue

|  steps  |  使用 Context 方式优化组件  |  Use Context to optimize components  |                |

perf(steps): use context refactor

---

packages/web-vue/components/avatar/README.en-US.md
packages/web-vue/components/avatar/README.zh-CN.md
packages/web-vue/components/avatar/avatar-group.tsx
packages/web-vue/components/avatar/avatar.vue
packages/web-vue/components/avatar/constants.ts
packages/web-vue/components/avatar/context.ts
packages/web-vue/components/avatar/interface.ts

|   avatar  |   使用 Context 方式优化组件  |   Use Context to optimize components  |  Close #685   |

perf(avatar): use context refactor

---

packages/web-vue/components/breadcrumb/breadcrumb-item.tsx
packages/web-vue/components/breadcrumb/breadcrumb.tsx
packages/web-vue/components/breadcrumb/context.ts

|  breadcrumb   |  使用 Context 方式优化组件   |  Use Context to optimize components  |                |

perf(bread): use context refactor

---

packages/web-vue/components/slider/slider.vue

|  slider  |  修复输入框改变时不会触发 change 的问题  |  Fix the problem that change will not be triggered when the input box is changed  |                |

fix(slider): fix input not trigger change

---

packages/web-vue/components/list/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/list/list-item.tsx

|  list  |   列表项应渲染为 div   |   List items should be rendered as div  |                |

fix(list): use div item

---

packages/web-vue/components/_components/input-label/style/input-label.less
packages/web-vue/components/_hooks/use-index.ts
packages/web-vue/components/_utils/is-equal.ts
packages/web-vue/components/select/README.en-US.md
packages/web-vue/components/select/README.zh-CN.md
packages/web-vue/components/select/__demo__/basic.md
packages/web-vue/components/select/__demo__/linkage.md
packages/web-vue/components/select/__demo__/multiple.md
packages/web-vue/components/select/__demo__/remote.md
packages/web-vue/components/select/context.ts
packages/web-vue/components/select/hooks/use-options.ts
packages/web-vue/components/select/option.vue
packages/web-vue/components/select/select.tsx

|  select   |  修复 label 属性失效的问题  |  Fix the problem that the label attribute is invalid  |   Close #748    |
|  select   |  修复 option 的属性没有同步更新的问题  |  Fix the problem that the properties of option are not updated synchronously  |                |

fix(select): fix option update error

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/TEMPLATE.md
packages/web-vue/components/table/__demo__/custom.md
packages/web-vue/components/table/__demo__/scroll.md
packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/table/context.ts
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/style/index.less
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table.tsx

|   table  |  滚动模式支持设置高度百分比  |  Scroll mode supports setting height percentage  |   Close #590   |
|   table  |  column 数据增加 slotName 属性，允许指定渲染插槽  |  The column data adds the slotName property to allow specifying a rendering slot  |   Close #692    |
|   table  |  增加 `pagination-left` 和 `pagination-right` 插槽  |  Added `pagination-left` and `pagination-right` slots  |               |

feat(table): support 100% height, add column slotName prop

---

packages/web-vue/components/tabs/tabs.tsx

|  tabs  |  修复初始化时会触发 activeKey 修改的问题   |  Fix the problem that activeKey modification will be triggered during initialization  |                |

fix(tabs): fix init change error

---

packages/web-vue/components/upload/upload-progress.tsx
packages/web-vue/components/upload/utils.tsx

|   upload  |   修复上传进度计算错误的问题  |   Fix the problem of incorrect upload progress calculation  |  Close #784    |
|   upload  |   修复上传中，取消按钮失效的问题  |   Fix the problem that the cancel button does not work during uploading  |     |

fix(upload): fix percent problem

---

packages/arco-vue-docs/docs/pro/directory.zh-CN.md
packages/web-vue/components/tabs/README.en-US.md
packages/web-vue/components/tabs/README.zh-CN.md
packages/web-vue/components/tabs/tabs.tsx

docs: update pro & tabs doc

---

packages/web-vue/components/date-picker/range-picker.vue

|     date-picker      |       修复范围选择器弹出层的偏移量错误的问题       |   Fix the problem that the offset of the range selector popup layer is wrong            |              |

fix(date-picker): the offset of popup is wrong

---

packages/web-vue/components/message/README.en-US.md
packages/web-vue/components/message/README.zh-CN.md
packages/web-vue/components/message/index.ts
packages/web-vue/components/message/interface.ts
packages/web-vue/components/notification/README.en-US.md
packages/web-vue/components/notification/README.zh-CN.md
packages/web-vue/components/notification/index.ts
packages/web-vue/components/notification/interface.ts

|  common  |   `modal`, `message`, `notifaction` 组件的函数式调用增加 appContext 的支持，详情请参见文档   |   `modal`, `message`, `notifaction` component function calls add support for appContext, see documentation for details  |   Close #791 , Close #458    |

feat(message): add appContext

---

packages/web-vue/components/drawer/README.en-US.md
packages/web-vue/components/drawer/README.zh-CN.md
packages/web-vue/components/drawer/drawer.vue

|   drawer   |  增加 `hide-cancel` 属性  |  Added `hide-cancel` attribute  |   Close #793   |

feat(drawer): add hideCancel

---

packages/web-vue/components/_utils/pick.ts
packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/components/grid/grid-col.vue
packages/web-vue/components/grid/hook/use-responsive-state.ts
packages/web-vue/components/grid/hook/use-responsive-value.ts
packages/web-vue/components/grid/interface.ts

|      grid     |      当列跨度为0的时候`a-col`将被隐藏         |      `a-col` will be hidden when colspan is 0          |      close #763          |

feat(grid): `a-col` will be hidden when colspan is 0

---

packages/web-vue/components/modal/README.en-US.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/TEMPLATE.md
packages/web-vue/components/modal/__demo__/draggable.md
packages/web-vue/components/modal/__demo__/form.md
packages/web-vue/components/modal/__demo__/fullscreen.md
packages/web-vue/components/modal/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/modal/hooks/use-draggable.ts
packages/web-vue/components/modal/index.tsx
packages/web-vue/components/modal/interface.ts
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/modal/style/index.less

|   modal  |  增加 `draggable` 属性，支持可拖动 |  Add `draggable` property to support draggable  |                |
|   modal  |  增加 `fullscreen` 属性，支持全屏展示 |  Added `fullscreen` property to support full screen display  |   Close #140   |

feat(modal): add draggable, fullscreen and appContext

---

packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table.tsx

|  table |  修改排序函数 sorter 的传出数据，增强使用  |  Modify the outgoing data of the sorting function sorter to enhance the usage  |                |

perf(table): modify sorter function params

---

packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/hooks/use-checked-state.ts
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/tree.vue

|   tree        |      支持设置半选节点         |      support for setting half-checked nodes         |       close #785          |
|   tree        |      实例上新增可调用的方法:  `getCheckedNodes` `getSelectedNodes` `getExpandedNodes` `getHalfCheckedNodes`      |      add some methods in instance: `getCheckedNodes` `getSelectedNodes` `getExpandedNodes` `getHalfCheckedNodes`        |                |

feat(tree): support for setting half-checked nodes

---

packages/web-vue/components/descriptions/descriptions.tsx

|  descriptions  |  修复 `data` 为空数据时报错的问题  |  Fix the problem of error when `data` is empty data  |                |

fix(desc): fix error when data is empty

---

packages/web-vue/components/button/style/index.less

https://github.com/arco-design/arco-design-vue/issues/759
给对应样式增加权重

Make 'Button' component compatible with Tailwindcss preflight

---

packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/context.ts
packages/web-vue/components/tree/hooks/use-checked-state.ts
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/tree.vue
packages/web-vue/components/tree/utils/index.ts

|     tree      |       添加树的实例方法        |      add instance method to tree component         |       close #755          |

feat(tree): add instance method to tree component

---

packages/web-vue/components/typography/base.tsx

修复slots改变时ellipsisText未变化
✅ Closes: #821
|      typography     |         修复 `ellipsisText` 未更新的问题      |       Fix `ellipsisText` not updating           |  Close  #821             |

fix: 🐛 修复slots改变时ellipsisText未变化

---

packages/web-vue/components/descriptions/README.en-US.md
packages/web-vue/components/descriptions/README.zh-CN.md
packages/web-vue/components/descriptions/__demo__/basic.md
packages/web-vue/components/descriptions/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/descriptions/descriptions.tsx

|   descriptions   |   `column` 属性支持响应式配置            |  The `column` property supports reactive configuration  |   Close #670      |

feat(desc): column prop support ResponsiveValue

---

packages/web-vue/components/_hooks/use-overflow.ts
packages/web-vue/components/_utils/keyboard.ts
packages/web-vue/components/descriptions/README.en-US.md
packages/web-vue/components/descriptions/README.zh-CN.md
packages/web-vue/components/descriptions/__demo__/basic.md
packages/web-vue/components/descriptions/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/descriptions/descriptions.tsx
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/modal/index.tsx
packages/web-vue/components/modal/modal.vue

|  modal  |  修复创建方法中返回的 `close` 函数错误的问题  | Fixed `close` function returning wrong in create method |  Close #836          |

fix(modal): fix return close func error

---

packages/web-vue/components/_hooks/use-overflow.ts
packages/web-vue/components/_utils/keyboard.ts
packages/web-vue/components/auto-complete/auto-complete.tsx
packages/web-vue/components/descriptions/README.en-US.md
packages/web-vue/components/descriptions/README.zh-CN.md
packages/web-vue/components/descriptions/__demo__/basic.md
packages/web-vue/components/descriptions/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/descriptions/descriptions.tsx
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/mention/mention.tsx
packages/web-vue/components/modal/index.tsx
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/select/README.en-US.md
packages/web-vue/components/select/README.zh-CN.md
packages/web-vue/components/select/__test__/index.test.ts
packages/web-vue/components/select/context.ts
packages/web-vue/components/select/hooks/use-options.ts
packages/web-vue/components/select/hooks/use-select.ts
packages/web-vue/components/select/option.vue
packages/web-vue/components/select/select.tsx
packages/web-vue/components/select/utils.ts

|  select  |   修复开启虚拟列表时，搜索功能失败的问题  |  Fixed the problem that the search function failed when the virtual list was opened  |                |
|  select  |   修复小键盘 `Enter` 键不能选中的问题  |  Fix the problem that the `Enter` key on the small keyboard cannot be selected  |                |

fix(select): fix virtual list problem

---

packages/web-vue/components/cascader/__demo__/panel.md
packages/web-vue/components/cascader/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/cascader/__test__/index.test.ts
packages/web-vue/components/cascader/base-cascader-panel.tsx
packages/web-vue/components/cascader/cascader-panel.vue
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/cascader/hooks/use-selected-path.ts
packages/web-vue/components/cascader/index.ts
packages/web-vue/components/cascader/style/index.less
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/components/time-picker/time-picker.vue

|  cascader  |  修复下拉菜单选中路径可能与当前值不符的问题  |  Fix the problem that the selected path of the drop-down menu may not match the current value   |   Close #806  |

fix(cascader): fix select path problem

---

packages/web-vue/components/date-picker/range-picker.vue

…me is selected
|    date-picker       |       选择结束时间的时候没有触发 select 事件        |       the select event is not triggered when the end time selected        |         close #818        |

fix(date-picker): the selected event is not triggered when the end time selected

---

packages/web-vue/components/form/__demo__/status.md
packages/web-vue/components/select/__demo__/footer.md
packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/__demo__/editable.md
packages/web-vue/components/table/__demo__/scroll.md
packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/table/context.ts
packages/web-vue/components/table/hooks/use-column-filter.ts
packages/web-vue/components/table/hooks/use-column-resize.ts
packages/web-vue/components/table/hooks/use-column-sorter.ts
packages/web-vue/components/table/hooks/use-data.ts
packages/web-vue/components/table/hooks/use-drag.ts
packages/web-vue/components/table/hooks/use-filter.ts
packages/web-vue/components/table/hooks/use-row-selection.ts
packages/web-vue/components/table/hooks/use-sorter.ts
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/style/index.less
packages/web-vue/components/table/table-column.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table-th.tsx
packages/web-vue/components/table/table.tsx
packages/web-vue/components/table/utils.ts

|   table   |  使用 Context 方式重构组件，`table-colum` 支持二次封装  |   Use Context to refactor components, `table-colum` supports secondary encapsulation  |                |
|   table   |  scroll 属性增加 `maxHeight`, `minWidth` 属性  |  scroll property adds `maxHeight`, `minWidth` properties  |                |
|   table   |  修复开启排序后，表头文字不能居中的问题  |  Fixed the problem that the header text could not be centered after sorting was enabled  |     Close #816           |

perf(table): use context refactor

---

packages/web-vue/components/tree/tree.vue

|       tree    |         修复新版本中展开事件名称错误的问题      | Fix the problem that the expansion event name is wrong in the new version      |         close #851        |

fix(tree): the name of expanded event is wrong

---

packages/arco-vue-docs/index.ts
packages/web-vue/components/form/style/index.less
packages/web-vue/components/select/option.vue
packages/web-vue/components/select/style/index.less
packages/web-vue/components/transfer/style/index.less
packages/web-vue/components/transfer/transfer-list-item.tsx

|   form  |   修复 `form-item` 星号与 windicss 的兼容问题  |  Fix `form-item` asterisk compatibility with windicss   |                |
|   select  |   修复选项 #icon 插槽的垂直居中问题  |  Fixed vertical centering of option #icon slots  |                |
|   select  |   修复选项超出宽度后没有显示省略的问题  |  Fix the problem that the omission is not displayed after the option exceeds the width  |                |
|   transform  |   修复选项超出宽度后没有显示省略的问题  |  Fix the problem that the omission is not displayed after the option exceeds the width  |                |

fix: fix some style problem

---

packages/arco-vue-docs/docs/pro/state-management-pinia.zh-CN.md

docs: update state-management-pinia

---

packages/web-vue/components/_utils/is-equal.ts
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/table-column.tsx
packages/web-vue/components/table/table.tsx

| table   |  修复 `table-column` 组件在模板中直接书写对象参数时导致不断更新的问题       |  Fixed the problem that the `table-column` component caused continuous updating when writing object parameters directly in the template   |                |
| table   |  修复仅有一个 `table-column` 时没有列数据的问题             |  Fix the problem that there is no column data when there is only one `table-column`   |                |
| table   |  修复 `table-column` 的排序问题，可通过 `index` 参数解决             |  Fix the sorting problem of `table-column`, which can be solved by the `index` parameter    |                |

fix(table): fix table-column problem

---

packages/web-vue/components/auto-complete/auto-complete.tsx
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/date-picker/picker.vue
packages/web-vue/components/date-picker/range-picker.vue
packages/web-vue/components/dropdown/dropdown-option.vue
packages/web-vue/components/dropdown/style/index.less
packages/web-vue/components/mention/mention.tsx
packages/web-vue/components/time-picker/time-picker.vue

|  dropdown  | 修复选项中图标的垂直居中问题  |  Fixed vertical centering of icons in options  |                |
|  common | 修复部分组件的下拉菜单动画问题  |  Fixed drop-down menu animation issues for some components  |                |

fix(dropdown): fix option icon vertical align problem

---

packages/web-vue/components/select/hooks/use-options.ts
packages/web-vue/components/select/interface.ts
packages/web-vue/components/select/option.vue

fix(select): fix option problem

---

packages/web-vue/components/tree/style/index.less

|      tree     |   修复连接线显示错乱的问题            |      fix the connection line is displayed incorrectly         |      close #852           |

fix(tree): fix the connection lines are messed up

---

packages/web-vue/components/layout/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/menu/indent.vue
packages/web-vue/components/menu/style/index.less

|     menu      |      解决菜单项的缩进换行的问题         |     fix the indentation of menu item is wrapped         |   close #835          |

fix(menu): the menu indent was not displayed correctly

---

packages/web-vue/components/button/__demo__/icon.md
packages/web-vue/components/button/__demo__/loading.md
packages/web-vue/components/tree-select/README.en-US.md
packages/web-vue/components/tree-select/README.zh-CN.md
packages/web-vue/components/tree-select/tree-select.vue

|   tree-select  |   修复 `max-tags` 参数名错误的问题，应为 `max-tag-count`   |  Fix `max-tags` parameter name is wrong, it should be `max-tag-count`  |                |

fix(tree-select): fix prop error

---

packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/hooks/use-checked-state.ts
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/tree.vue
packages/web-vue/components/tree/utils/index.ts

|     tree      |     新增配置项 `onlyCheckLeaf`          |      add property `onlyCheckLeaf `        |                |

feat(tree): add property onlyCheckLeaf

---

packages/arco-vue-docs/components/cell-code/index.vue
packages/arco-vue-docs/locale/en-us.js
packages/arco-vue-docs/locale/zh-cn.js
packages/arco-vue-docs/package.json
packages/arco-vue-docs/utils/code-sandbox.ts

feat(site): use CodeSandbox

---

packages/arco-vue-docs-navbar/package.json
packages/arco-vue-docs-navbar/src/index.tsx

feat(site): nav support search

---

packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/tree.vue

|      tree     |   支持关闭展开时的动效            |      support to turn off expand transition animation         |       close #815          |

feat(tree): enable to close expand transition animation

---

packages/web-vue/components/avatar/avatar.vue

|   avatar   |   修复没有内容时会出现警告提示的问题  |  Fixed an issue where a warning message would appear when there was no content   |                |

fix(avatar): fix watch warning problem

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/TEMPLATE.md
packages/web-vue/components/table/__demo__/summary.md
packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/table/style/index.less
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table.tsx

|  table  |  增加总结行功能  | Add summary prop  |    Close #617             |

feat(table): add summary

---

packages/web-vue/components/_utils/dom.ts
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/tag/README.en-US.md
packages/web-vue/components/tag/README.zh-CN.md
packages/web-vue/components/tag/__demo__/size.md
packages/web-vue/components/tag/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/tag/tag.vue

Check the Mini size missing style of the Tag component in the official website documentation
1. Tag
remove mini size type.
When using config provider, if size is equal to 'mini', will return 'small'.
2. Modal
When Modal is displayed, in the `handleOpen` callback function, will get `document.activeElement`, and cancel the focus.
|      tag     |         移除尺寸类型 `mini`      |       Remove `mini` size type        |                |
|   modal |  修复使用函数方式触发Modal显示时，按钮处于焦点，此时点击回车会继续出发点击事件 | Fix the bug that the enter key triggers modal display multiple times | #603  |

Fix Tag And Modal Bug

---

packages/web-vue/components/affix/affix.vue
packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md

|  affix |   修复组件在 SSR 下报错的问题   |  Fix the problem of component reporting error under SSR   |                |

fix(affix): fix ssr problem

---

packages/web-vue/components/select/option.vue
packages/web-vue/components/select/select.tsx

|  select         |        多选模式下tag可以删除       |    Multiple mode tag delete           |         #855        |

fix: [select] in multiple mode no close

---

packages/web-vue/components/select/__demo__/fallback.md
packages/web-vue/components/select/select.tsx

|   select  |   修复 `fallback-option` 属性设置 false 失效的问题   |   Fix the problem that `fallback-option` attribute setting false is invalid   |                |

fix(select): fix fallback problem

---

packages/web-vue/components/menu/style/index.less

|     menu      |         弹出框中的图标与文字没有对齐      |       The icon in the popup box is not aligned with the text        |                |

fix: icons are not aligned with text

---

packages/web-vue/components/tree-select/README.en-US.md
packages/web-vue/components/tree-select/README.zh-CN.md
packages/web-vue/components/tree-select/TEMPLATE.md
packages/web-vue/components/tree-select/__demo__/fallback.md
packages/web-vue/components/tree-select/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/tree-select/hooks/use-selected-state.ts
packages/web-vue/components/tree-select/interface.ts
packages/web-vue/components/tree-select/tree-select.vue
packages/web-vue/components/tree/interface.ts

|      tree-select     |     新增参数 `fallback-option`          |      add property `fallback-option`         |     close #880            |

feat(tree-select): add property fallback-option

---

packages/web-vue/components/typography/base.tsx
packages/web-vue/components/typography/interface.ts

|   typography        |       修复复制无效的问题        |        fix the problem that copy does not work       |     close #902            |

fix(typography): copy does not work

---

packages/web-vue/components/upload/upload.tsx

|  upload   |  修复 onButtonClick 属性不可用的问题  |  Fix onButtonClick property not available  |                |

fix(upload): fix onButtonClick prop problem

---

packages/web-vue/components/tree-select/hooks/use-selected-state.ts

|     tree-select      |     修复  null 值显示为空的问题      |     Fix the problem that the null value is displayed as empty         |      close #898           |

fix(tree-select): null should not be displayed

---

packages/web-vue/components/mention/__demo__/basic.md
packages/web-vue/components/mention/mention.tsx

|  mention  |   修复 v-model 双向绑定在选择值时错误的问题   |   Fix v-model two-way binding error when selecting value   |  Close #899  |

fix(mention): fix v-model error

---

packages/web-vue/components/input-number/input-number.tsx

|  input-number  |   修复切换 `mode` 时展示错误的问题  |  Fixed display error when switching `mode`  |                |

fix(input-number): fix change mode problem

---

packages/web-vue/components/_utils/types.ts
packages/web-vue/components/input-tag/README.en-US.md
packages/web-vue/components/input-tag/README.zh-CN.md
packages/web-vue/components/input-tag/__demo__/size.md
packages/web-vue/components/input-tag/index.ts
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input-tag/interface.ts
packages/web-vue/components/input-tag/utils.ts
packages/web-vue/components/tag/index.ts
packages/web-vue/components/tag/interface.ts

|   input-tag  |  增加 `field-names` 属性  |  Added `field-names` attribute |                |

feat(input-tag): add fieldNames

---

packages/web-vue/components/modal/modal.vue
packages/web-vue/components/modal/style/index.less

|  modal  |  修复 `align-center="false"` 时自动宽度和拖动错误的问题   |  Fix auto width and drag error when `align-center="false"`  |     Close #914     |

fix(modal): fix base mode problem

---

packages/web-vue/components/form/README.en-US.md
packages/web-vue/components/form/README.zh-CN.md
packages/web-vue/components/form/form-item-label.vue
packages/web-vue/components/form/form-item.vue
packages/web-vue/components/form/style/index.less

| New feature |  form  |   支持修改表单项标签的渲染元素   |  Rendering elements that support modifying form item labels  |  Close #900   |
| Component style change |  form  |   表单项内容样式增加最大宽度，防止溢出   |  Form item content style increases maximum width to prevent overflow  |  Close #795    |

feat(form): add label component

---

packages/web-vue/components/_components/virtual-list/virtual-list.vue
packages/web-vue/components/table/table.tsx

|  New feature |  table  |  增加 `selectAll` 方法  |  Added `selectAll` method  |   Close #708        |
|  Bug fix |  table  |  修复某些情况下虚拟列表宽度错误的问题  |  Fix the problem of wrong virtual list width in some cases  |      |

feat(table): add selectAll

---

packages/web-vue/components/select/hooks/use-options.ts

|  mention  |   修复开发环境下出现警告提示的问题   |   Fix the problem of warning prompts in the development environment  |                |

fix(mention): fix dev warning problem

---

packages/web-vue/components/_components/virtual-list/filler.vue
packages/web-vue/components/_components/virtual-list/virtual-list.vue
packages/web-vue/components/table/table.tsx

|   table  |  修复虚拟列表和滚动一起使用的问题 |  Fix virtual list and scrolling used together  |                |

fix(table): fix virtual-list use with scroll

---

packages/web-vue/components/menu/style/index.less

|      menu     |       修复菜单图标的高度不对的问题        |      Fixed the problem that the height of menu icon is wrong         |                |

fix(menu): the line-height of icon is wrong

---

packages/web-vue/components/menu/README.en-US.md
packages/web-vue/components/menu/README.zh-CN.md
packages/web-vue/components/menu/base-menu.vue
packages/web-vue/components/menu/context.ts
packages/web-vue/components/menu/interface.ts
packages/web-vue/components/menu/sub-menu-pop.vue
packages/web-vue/components/menu/sub-menu.tsx

|     menu      |      支持通过 `popup-max-height` 设置弹出框的最大高度         |     Support set the set the maximum height of popover by `popup-max-height`          |     close #932            |

feat(menu): support set the maximum height of popover

---

packages/web-vue/components/upload/context.ts
packages/web-vue/components/upload/index.ts
packages/web-vue/components/upload/interfaces.ts
packages/web-vue/components/upload/upload-list-item.tsx
packages/web-vue/components/upload/upload-list.tsx
packages/web-vue/components/upload/upload-picture-item.tsx
packages/web-vue/components/upload/upload-progress.tsx
packages/web-vue/components/upload/upload.tsx
packages/web-vue/components/upload/utils.tsx

|  upload   |  增加图标相关插槽     |   Added icon related slots   |   Close #762     |
|  upload   |  增加 updateFile 方法，onBeforeUpload 支持返回 File     |   Added updateFile method, onBeforeUpload supports returning File   |  Close #903    |
|  upload   |  优化初始图片显示逻辑     |  Optimize initial image display logic  |   Close #904             |

feat(upload): add slots and method

---

packages/web-vue/components/_hooks/use-overflow.ts
packages/web-vue/components/_utils/dom.ts
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/modal/style/index.less

|  Performance improvement  |  modal  |  修复在滚动条为浮动的情况下，body没有锁定的问题  |  Fix the problem that the body is not locked when the scroll bar is floating   |                |
|  Component style change  |  modal  |  修复在简单模式下，title-align 靠左对齐失效的问题  |  Fix the problem that title-align is left-aligned invalid in simple mode   |   Close #938    |

perf(modal): perf body scroll judgment method

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/TEMPLATE.md
packages/web-vue/components/table/__demo__/filter.md
packages/web-vue/components/table/__demo__/summary.md
packages/web-vue/components/table/__demo__/virtual-list.md
packages/web-vue/components/table/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/table/hooks/use-column-resize.ts
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/style/index.less
packages/web-vue/components/table/style/token.less
packages/web-vue/components/table/table-column.tsx
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table-operation-th.tsx
packages/web-vue/components/table/table-th.tsx
packages/web-vue/components/table/table.tsx

| New feature | table  |  columns 属性增加 titleSlotName，filterable 属性增加 slotName  | Add titleSlotName to the columns attribute and slotName to the filterable attribute  |  Close #947  |
| New feature | table  |  table-column 增加 filter-content，filter-content 插槽  |  table-column adds filter-content, filter-content slot  |                |
| New feature | table  |  增加 summary-cell 插槽  |  Added summary-cell slot  |                |
| Performance improvement | table  |  横向滚动模式下，如果数据为空，表头会显示滚动条  |  In horizontal scrolling mode, if the data is empty, the header will display a scroll bar  |                |

feat(table): add slots

---

packages/web-vue/components/auto-complete/auto-complete.tsx
packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input-number/style/index.less
packages/web-vue/components/input-tag/input-tag.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/input/style/group.less
packages/web-vue/components/input/style/index.less
packages/web-vue/components/mention/mention.tsx
packages/web-vue/components/textarea/textarea.vue

|  New feature  |  mention  |  增加 allow-clear 属性和事件  |  Added allow-clear property and event  |   Close #941              |
|  New feature  |  auto-complete  |  增加 allow-clear 属性和事件  |  Added allow-clear property and event  |                |
|  Performance improvement  |  input  |  输入类组件的 `clear` 事件会同时触发 `change` 事件  |  The `clear` event of the input class component will also trigger the `change` event  |                |

feat(input): modify clear event

---

packages/web-vue/components/arco-vue.ts
packages/web-vue/components/cascader/README.en-US.md
packages/web-vue/components/cascader/README.zh-CN.md
packages/web-vue/components/cascader/base-cascader-panel.tsx
packages/web-vue/components/cascader/cascader-panel.vue
packages/web-vue/components/cascader/cascader-search-panel.tsx
packages/web-vue/components/cascader/cascader.vue
packages/web-vue/components/cascader/index.ts
packages/web-vue/components/cascader/utils.ts
packages/web-vue/components/index.ts
packages/web-vue/components/select/hooks/use-options.ts

|  New feature  |  cascader  |    增加 empty 插槽    |   add empty slot  |                |
|  Bug fix  |  cascader  |    修复 2.22.0 版本中懒加载的 isLeaf 失效的问题    |   Fix the problem that lazy loaded isLeaf is invalid in version 2.22.0  |                |
|  Bug fix  |  cascader  |    修复 options 属性在某些情况下不能触发更新的问题    |   Fixed an issue where the options property could not trigger an update in some cases  |                |

feat(cascader): add empty slot

---

packages/web-vue/components/image/image.vue
packages/web-vue/components/image/style/image.less

|   New feature  |   image  |   增加 footer-class  属性 |  Add footer-class attribute  |                |
|   Component style change  |   image  |   修复 footer 区域底部圆角样式问题  |  Fix the rounded corner style problem at the bottom of the footer area  |                |

fix(image): fix footer style

---

packages/web-vue/components/pagination/page-jumper.vue
packages/web-vue/components/pagination/pagination.tsx
packages/web-vue/components/pagination/style/index.less

|  New feature  |  pagination  |  增加 `jumper-prepend` 和  `jumper-append` 插槽 | Added `jumper-prepend` and `jumper-append` slots   |  Close #667   |
|  Performance improvement  |  pagination  |   优化切换 pageSize 时的页码改变逻辑   |  Optimize the page number change logic when switching pageSize  |   Close #498  |

feat(pagination): add slots

---

packages/web-vue/components/steps/__test__/index.test.ts
packages/web-vue/components/steps/context.ts
packages/web-vue/components/steps/step.vue
packages/web-vue/components/steps/steps.vue

if a-steps is not the excatly parent of a-step ,a-step can not get a correct index
Closes #958 
when using useIndex function, find a correct parent by given a parentClassName
add a unit-test (nested step can have correct index)
By testing the stepNumber when give a-steps some a-step which are not the excatly child of a-steps
|    steps       |      修复 Steps 与 Step 组件非直接父子关系时 index 错误的问题        |    Fix the problem of index error when Steps and Step components are not in direct parent-child relationship           |   Close   #958            | 

refactor: make nested step can have correct index

---

packages/web-vue/components/cascader/utils.ts

|      cascader     |复选框的半选状态显示错误|checkbox indeterminate status error|                |

fix: checkbox indeterminate status error on cascader multiple mode

---

packages/web-vue/components/_utils/dom.ts
packages/web-vue/components/rate/style/index.less

|  modal  |    修复在某些情况下不会锁定 body 的问题   |  Fixed an issue where the body would not be locked in some cases  |                |

fix(modal): fix body scroll problem

---

packages/web-vue/components/table/table-th.tsx

|   table   |   当 columns 属性中存在 titleSlotName 时会优先使用      |   When titleSlotName exists in the columns attribute, it will be used first   |                |

perf(table): render titleSlot first

---

packages/arco-vue-docs/router.ts

当点击 anchor 时，会出现 nprogress
同 path 下发生 router 不 restart nprogress
|     docs      |      同 path 下发生 router 不执行 nprogress         |     same path router change not restart nprogress          |      -          |

docs: fix anchor hash change nprogress restart

---

packages/web-vue/components/card/style/index.less
packages/web-vue/components/card/style/token.less
packages/web-vue/components/modal/modal.vue

| Type| Component | Changelog(CN) | Changelog(EN) | Related issues |
|  New feature |  modal | 增加动画名属性   |   Add animation name attribute  |   Close #961         |
|  Component style change |  modal | 修复全屏下动画导致闪现滚动条的问题   |   Fix the issue that the scroll bar flashes when the animation is in full screen  |      |

feat(modal): add animation-name

---

packages/web-vue/components/pagination/style/index.less
packages/web-vue/components/pagination/style/token.less
packages/web-vue/components/textarea/textarea.vue

|   pagination   |   分页选择项增加 padding   |   Add padding to pagination options  |                |

fix(pagination): add padding style

---

packages/web-vue/components/cascader/style/index.less
packages/web-vue/components/cascader/style/token.less

style: cascader add token

---

packages/web-vue/components/tree-select/tree-select.vue

fix(tree-select): valiable name conflict

---

packages/web-vue/components/typography/base.tsx

|     typography      |    解决 `slots.default` 报警告的问题           |     fixed the warning of `slots.default`         |      close #964           |

fix(typography): fix the warning of slot.default

---

packages/web-vue/components/button/button-group.vue
packages/web-vue/components/button/button.vue
packages/web-vue/components/button/context.ts

|  button |  修复 `config-provide` 注入失效的问题  | Fix `config-provide` injection invalid problem |                |

fix(button): fix config problem

---

.github/PULL_REQUEST_TEMPLATE.md
packages/arco-vue-scripts/src/scripts/changelog/index.ts
packages/arco-vue-scripts/src/scripts/changelog/template/main.en-US.njk
packages/arco-vue-scripts/src/scripts/changelog/template/main.zh-CN.njk
packages/arco-vue-scripts/src/scripts/changelog/utils.ts
packages/vite-plugin-arco-vue-docs/src/parse-changelog.ts
packages/web-vue/CHANGELOG.md
packages/web-vue/components/avatar/CHANGELOG.md
packages/web-vue/components/badge/CHANGELOG.md
packages/web-vue/components/breadcrumb/CHANGELOG.md
packages/web-vue/components/cascader/CHANGELOG.md
packages/web-vue/components/date-picker/CHANGELOG.md
packages/web-vue/components/form/CHANGELOG.md
packages/web-vue/components/input/CHANGELOG.md
packages/web-vue/components/menu/CHANGELOG.md
packages/web-vue/components/modal/CHANGELOG.md
packages/web-vue/components/pagination/CHANGELOG.md
packages/web-vue/components/select/CHANGELOG.md
packages/web-vue/components/steps/CHANGELOG.md
packages/web-vue/components/table/CHANGELOG.md
packages/web-vue/components/tabs/CHANGELOG.md
packages/web-vue/components/tree-select/CHANGELOG.md
packages/web-vue/components/trigger/CHANGELOG.md

feat(changelog): update changelog

---

packages/web-vue/components/config-provider/README.en-US.md
packages/web-vue/components/config-provider/README.zh-CN.md
packages/web-vue/components/config-provider/config-provider.vue
packages/web-vue/components/config-provider/index.ts

|   config-provider        |     添加 `isGlobal` 属性          |     add property isGlobal          |                |

feat(config-provider): add property isGlobal

---

packages/web-vue/components/config-provider/README.en-US.md
packages/web-vue/components/config-provider/README.zh-CN.md
packages/web-vue/components/config-provider/TEMPLATE.md
packages/web-vue/components/config-provider/config-provider.vue
packages/web-vue/components/config-provider/context.ts
packages/web-vue/components/config-provider/index.ts
packages/web-vue/components/tooltip/README.en-US.md
packages/web-vue/components/tooltip/README.zh-CN.md
packages/web-vue/components/tooltip/tooltip.vue
packages/web-vue/components/trigger/trigger.tsx

|   config-provider    |   增加 updateAtScroll 属性  | Add updateAtScroll property  |                |

feat(config): add updateAtScroll prop

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/hooks/use-row-selection.ts
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table.tsx

table组建的select事件在部分场景下需要当前事件发生行的 key 值
在不影响现在 select 的情况下，select 发送第二个参数为 rowKey
❗️为了接口一致性，checkout 和 radio 都补充了参数 
|     table      |      `select` 事件新增第二个参数 `rowKey`         |    Add a second param `rowKey` to the `select` event           |                - |

feat: table select event support row key param

---

packages/web-vue/components/tag/interface.ts

|   tag   |   修复 TagProps 的问题   |   Fix TagProps issues      |                |

fix(tag): fix ts problem

---

packages/web-vue/components/table/__demo__/editable.md
packages/web-vue/components/table/__demo__/expand.md
packages/web-vue/components/table/__demo__/row-selection.md
packages/web-vue/components/table/__demo__/subtree.md
packages/web-vue/components/table/context.ts
packages/web-vue/components/table/hooks/use-expand.ts
packages/web-vue/components/table/hooks/use-row-selection.ts
packages/web-vue/components/table/interface.ts
packages/web-vue/components/table/style/index.ts
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table.tsx
packages/web-vue/components/table/utils.ts

|  New feature  |  table  |   增加行选择器和展开行双向绑定属性  | Add row selector and expand row two-way binding properties   |                |
|  Enhancement  |  table  |  自定义单元格渲染的 `record` 参数支持修改  |  The `record` parameter of custom cell rendering supports modification  |                |

feat(table): add v-model

---

packages/web-vue/components/_hooks/use-popup-manager.ts
packages/web-vue/components/drawer/drawer.vue
packages/web-vue/components/image/preview.vue
packages/web-vue/components/message/message-list.tsx
packages/web-vue/components/modal/__demo__/function.md
packages/web-vue/components/modal/modal.vue
packages/web-vue/components/notification/notification-list.tsx
packages/web-vue/components/trigger/trigger.tsx

|  modal |  使用 `esc` 关闭时只会关闭最上层弹窗  |   When closing with `esc`, only the topmost popup will be closed  |  Close #698 , Close #817               |

perf(modal): esc to close last modal

---

packages/web-vue/components/input-number/input-number.tsx

|   input-number  |   修复 error 属性失效的问题             |     Fix the problem that the error attribute is invalid   |                |

fix(input-number): fix `error` problem

---

packages/web-vue/components/date-picker/interface.ts
packages/web-vue/components/date-picker/range-picker.vue

|     date-picker      |       增加参数 `exchangeTime`        |      add property exchangeTime         |                |

feat(datepicker): add property exchangeTime

---

packages/web-vue/components/tree/tree.vue

|    tree       |   调用方法操作单个节点的时候在回调参数重增加目标节点信息            |        When calling a method to operate a single node, add the target node information in the callback parameter       |        close #1013         |

feat(tree): add targetNode when operating a single node

---

packages/web-vue/components/menu/style/index.less
packages/web-vue/components/notification/interface.ts
packages/web-vue/components/notification/notification-list.tsx
packages/web-vue/components/notification/notification.vue

|  New feature  |  notification   |    增加 button 属性   |    Add button prop    |                |
|  Component style change |  menu   |    弹出菜单的 icon 增加 margin-right   |    Popup menu icon increased margin-right    |                |

feat(notification): add button prop

---

packages/web-vue/components/menu/base-menu.vue
packages/web-vue/components/menu/context.ts
packages/web-vue/components/menu/hooks/use-menu-data-collector.ts
packages/web-vue/components/menu/item.tsx
packages/web-vue/components/menu/sub-menu.tsx

|      menu     |    菜单数据收集器收集到的数据有缺失           |     Fix the problem that the collected menu data is incomplete          |       close #996          |

fix(menu): the collected menu data is incomplete

---

packages/web-vue/components/checkbox/style/index.less

checkbox 在 disabled 的情况下，hover 情况还会改变勾选框的颜色
设置 disbaled hover style（ArcoReact 的实现方式）
|    checkbox       |    禁用状态下hover还会改变样式          |       When disabled, hover also changes the style        |      -          |

fix: checkbox disabled hover border color

---

packages/web-vue/components/table/hooks/use-span.ts
packages/web-vue/components/table/table-operation-td.tsx
packages/web-vue/components/table/table-td.tsx
packages/web-vue/components/table/table.tsx

|   table    |   修复 `2.25.0` 版本中扩展行传出 record 参数格式错误问题   |  Fix the problem of wrong format of outgoing record parameter in extended line in `2.25.0` version  |                |

fix(table): fix outgoing parameter format error

---

packages/web-vue/components/input-number/style/index.less
packages/web-vue/components/input/style/index.less
packages/web-vue/components/input/style/input.less
packages/web-vue/components/input/style/size.less

|  input-number  |   修复清除按钮显示位置问题  |  Fix the display position of the clear button    |                |

fix(input-number): fix clear btn style problem

---

packages/web-vue/components/_hooks/use-trigger.ts

|   common  |  修复部分组件 `popup-visible` 双向绑定状态异常的问题  |  Fixed the problem of abnormal two-way binding status of some components `popup-visible`   |                |

fix(popup): fix popupVisibleChange event problem

---

packages/web-vue/components/tabs/interface.ts
packages/web-vue/components/tabs/tab-pane.vue
packages/web-vue/components/tabs/tabs-nav.tsx
packages/web-vue/components/tabs/tabs.tsx

|   tabs  |   修复 #title 插槽在某些情况下不能更新的问题  |    Fixed #title slot not updating in some cases   |                |

fix(tabs): fix tabs title slot problem

---

packages/web-vue/components/grid/grid-row.vue
packages/web-vue/components/popconfirm/popconfirm.vue
packages/web-vue/components/popover/popover.vue
packages/web-vue/components/radio/radio.vue
packages/web-vue/components/space/TEMPLATE.md
packages/web-vue/components/space/space.tsx

|   space  |    修复 size 属性类型检测问题    |  Fix size attribute type detection problem   |                |
|   grid  |    修复 gutter 属性类型检测问题   |   Fix gutter attribute type detection problem   |                |

fix(type): fix some type problem

---

packages/web-vue/components/table/style/index.less
packages/web-vue/components/table/table.tsx

|   table  |   增加内部 table 类名，修复与 `descriptions` 组件一起使用的样式问题            |   Added internal table class names, fixed styling issues used with `descriptions` component   |                |

fix(table): fix use desc problem with table

---

packages/web-vue/components/cascader/style/index.less

|  cascader  |   修复搜索下拉菜单在空白时的宽度问题   |   Fixed the width of the search drop-down menu when it was blank    |                |

fix(cascader): fix search panel width problem

---

packages/web-vue/components/collapse/collapse-item.vue

|   collapse    |   修复 `showExpandIcon` 属性失效的问题   |    Fix `showExpandIcon` property invalid   |                |

fix(collapse): fix showExpandIcon invalid

---

packages/web-vue/components/grid/grid-row.vue
packages/web-vue/components/list/index.ts

fix: fix some type problem

---

packages/web-vue/components/list/list.tsx

当使用 item slot 时，无法控制 empty 的展示
|     list      |       支持 `empty` 插槽         |        support `empty` slot       |         -       |

feat(list): empty slot

---

packages/web-vue/components/checkbox/README.en-US.md
packages/web-vue/components/checkbox/README.zh-CN.md
packages/web-vue/components/checkbox/TEMPLATE.md
packages/web-vue/components/checkbox/__demo__/options.md
packages/web-vue/components/checkbox/checkbox-group.tsx
packages/web-vue/components/checkbox/index.ts
packages/web-vue/components/checkbox/interface.ts

|      checkbox     |    `checkbox-group` 支持 `options` 属性配置子元素           |       `checkbox-group` supports `options` attribute to configure child elements        |     -  |

feat(checkbox-group): support options prop children

---

packages/web-vue/components/checkbox/README.en-US.md
packages/web-vue/components/checkbox/README.zh-CN.md
packages/web-vue/components/checkbox/TEMPLATE.md
packages/web-vue/components/checkbox/__demo__/control.md
packages/web-vue/components/checkbox/__demo__/custom.md
packages/web-vue/components/checkbox/__demo__/disabled.md
packages/web-vue/components/checkbox/__demo__/layout.md

|     checkbox      |        演示案例       |       demo        |       -         |

docs: checkbox demo update

---

packages/web-vue/components/radio/README.en-US.md
packages/web-vue/components/radio/README.zh-CN.md
packages/web-vue/components/radio/TEMPLATE.md
packages/web-vue/components/radio/__demo__/control.md
packages/web-vue/components/radio/__demo__/custom.md
packages/web-vue/components/radio/__demo__/layout.md
packages/web-vue/components/radio/radio.vue

|     radio      |        演示案例       |       demo        |       -         |

docs(radio): radio demo update

---

packages/web-vue/components/modal/modal.vue

fix bug:  #1069 
|   modal   |  修复拖拽后开启全屏产生位置偏移的问题  |    Fix the problem of position offset when opening full screen after dragging    |    Close #1069             |

fix: fix model fullscreen dislocation position

---

packages/web-vue/components/message/index.ts
packages/web-vue/components/notification/index.ts

|  message   |  修复 clear 方法在多次调用时出现错误的问题          |    Fix the problem that the clear method has an error when called multiple times    |                |

fix(message): fix message clear problem

---

packages/web-vue/components/date-picker/pickers/quarter-picker.tsx
packages/web-vue/components/date-picker/pickers/week-picker.tsx

The component internally uses `Dayjs` to parse the value in string format, because the string parsing of `Dayjs` does not support the format of week `gggg-wo` and the format of quarter `YYYY-[Q]Q`, resulting in the use of `v-model` When the value is not parsed correctly.
|     date-picker      |     修复使用 `v-model` 绑定 `week-picker ` 和 `quarter-picker` 的时候值错误的问题        |        the value of `week-picker ` and `quarter-picker` is wrong when using `v-model`       |      close #1108           |

fix(date-picker): week and quarter has a wrong value

---

packages/web-vue/components/tree-select/hooks/use-selected-state.ts
packages/web-vue/components/tree/base-node.vue
packages/web-vue/components/tree/hooks/use-checked-state.ts
packages/web-vue/components/tree/tree.vue
packages/web-vue/components/tree/utils/index.ts

|      tree     |        修复当 key 为 number 的时候，expandAll 失败的问题       |      expandAll failed when the type of key is number         |                |

fix(tree): expandAll is invalid when the type of key is number

---

packages/web-vue/components/collapse/README.en-US.md
packages/web-vue/components/collapse/README.zh-CN.md
packages/web-vue/components/collapse/TEMPLATE.md
packages/web-vue/components/collapse/__demo__/destroy.md
packages/web-vue/components/collapse/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/collapse/collapse-item.vue
packages/web-vue/components/collapse/collapse.vue
packages/web-vue/components/collapse/context.ts
packages/web-vue/components/collapse/style/index.less

ARIA improvement  #191
|   New feature  |   collapse   |   增加 destroyOnHide 属性    |   Add destroyOnHide property   |    Close #1057             |

feat(collapse): add destroyOnHide prop

---

packages/web-vue/components/carousel/README.en-US.md
packages/web-vue/components/carousel/README.zh-CN.md
packages/web-vue/components/carousel/TEMPLATE.md
packages/web-vue/components/carousel/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/carousel/carousel-item.vue
packages/web-vue/components/carousel/carousel.tsx
packages/web-vue/components/carousel/context.ts
packages/web-vue/components/carousel/index.ts

ARIA improvement #191
|       |        |      |        |

enhance(carousel): ARIA improvement

---

packages/web-vue/components/divider/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/divider/divider.tsx

enhance(divider): ARIA improvement

---

packages/web-vue/components/list/__test__/__snapshots__/demo.test.ts.snap
packages/web-vue/components/list/list-item.tsx
packages/web-vue/components/list/list.tsx

enhance(list): ARIA improvement

---

packages/web-vue/components/button/button.vue
packages/web-vue/components/input/input-search.tsx
packages/web-vue/components/input/input.tsx

ARIA improvement #191
| Component | Component | Changelog(CN) | Changelog(EN) | Related issues |
|   New feature  |   input   |    增加 input-attrs 属性    |  Add input-attrs attribute   |    Close #1071            |
|   Enhancement  |   input   |    修改 blur 事件触发顺序到 change 之后    |  Modify the blur event trigger sequence to after change   |          |

feat(input): add inputAttrs prop

---

packages/web-vue/components/image/preview-action.tsx
packages/web-vue/components/trigger/trigger.tsx

|  trigger   |  在右键触发时，点击触发元素可以关闭下拉框  |   When the right button is triggered, click the trigger element to close the drop-down box   |    Close #1077             |
|  trigger   |  支持弹出组件嵌套使用  |   Support pop-up component nesting   |   Close #1091             |

enhance(trigger): support trigger nest

---

packages/web-vue/components/_components/input-label/style/input-label.less
packages/web-vue/components/select/utils.ts

|  Bug fix |   select   |  修复 options 属性中 `render`、`tagProps` 不生效的问题  |    Fix the problem that `render` and `tagProps` in options property do not take effect   |                |
|  Component style change |   select   |  修复开启搜索时，禁用状态下鼠标指针错误的问题  |    Fix the problem that the mouse pointer is wrong in the disabled state when the search is turned on   |                |

fix(select): fix options prop render & tagProps invalid problem

---

packages/web-vue/components/table/README.en-US.md
packages/web-vue/components/table/README.zh-CN.md
packages/web-vue/components/table/interface.ts

使用 VNodeChild 替代 Vnode。 Close #1079
|  table  |   使用 VNodeChild 替代接口中的 VNode，支持更广泛类型        |    Use VNodeChild instead of VNode in the interface to support a wider range of types   |     Close #1079     |

feat(table): enhance interface

---

packages/web-vue/components/modal/README.en-US.md
packages/web-vue/components/modal/README.zh-CN.md
packages/web-vue/components/modal/interface.ts
packages/web-vue/components/modal/modal.vue

|   modal  |    补全 ModalConfig 缺失的属性   |   Complete missing properties in ModalConfig   |   Close #1072             |

fix(modal): fix interface problem

---

packages/web-vue/components/pagination/pagination.tsx

|   pagination   |   修复 simple 模式下，size 失效的问题   |  Fix the problem that size is invalid in simple mode  |    Close #1083            |

fix(pagination): fix size problem on simple

---

packages/web-vue/components/table/style/index.less

|   table   |  修复存在固定列时，出现竖向滚动条的问题 |  Fixed the problem of vertical scroll bar when there are fixed columns  |                |

fix(table): fix fixed style problem

---

packages/web-vue/components/list/list.tsx
packages/web-vue/components/list/use-pagination.ts

|  list  |  修复分页属性失效的问题   |   Fix the problem that the pagination property is invalid  |     Close #1088            |

fix(list): fix pagination invalid problem

---

packages/web-vue/components/typography/README.en-US.md
packages/web-vue/components/typography/README.zh-CN.md
packages/web-vue/components/typography/base.tsx

|      typography     |      修复按下回车的时候触发两次 `editEnd` 的问题         |      fix the problem that event `edit-end` triggered twice when press enter         |        close #1110  #1103        |

fix(typography): event `edit-end` triggered twice when press enter

---

packages/web-vue/components/_utils/to-array.ts
packages/web-vue/components/tree-select/README.en-US.md
packages/web-vue/components/tree-select/README.zh-CN.md
packages/web-vue/components/tree-select/panel.tsx
packages/web-vue/components/tree-select/tree-select.vue
packages/web-vue/components/tree/README.en-US.md
packages/web-vue/components/tree/README.zh-CN.md
packages/web-vue/components/tree/base-node.vue
packages/web-vue/components/tree/context.ts
packages/web-vue/components/tree/hooks/use-tree-data.ts
packages/web-vue/components/tree/interface.ts
packages/web-vue/components/tree/tree.vue
packages/web-vue/components/tree/utils/tree-data.ts

|      tree     |       `checkable` 支持函数格式       |       `checkable` supports configuration via function        |                |
|      tree     |       `seleable` 支持函数格式       |       `selectable` supports configuration via function        |                |
|      tree     |       新增属性 `actionOnNodeClick`，可用于开启点击节点触发展开       |      Added property `actionOnNodeClick`, which can be used to enable the function: click on a node to trigger expansion        |                |
|      tree-select    |       新增属性 `seletable`，支持自定义可选节点       |     Added property `seletable` to support custom selectable nodes        |      close #1099           |
should be submitted to …

feat(tree): only leaf node can be selected

---

packages/web-vue/components/select/utils.ts

|   select   |   修复使用 options 属性时，分组选项不能选择的问题   |  Fixed an issue where grouping options could not be selected when using the options property  |      |

fix(select): fix group options problem

---

packages/web-vue/components/_components/virtual-list/interface.ts
packages/web-vue/components/avatar/avatar.vue
packages/web-vue/components/button/button.vue
packages/web-vue/components/checkbox/checkbox-group.tsx
packages/web-vue/components/checkbox/checkbox.tsx
packages/web-vue/components/collapse/collapse.vue
packages/web-vue/components/input-number/input-number.tsx
packages/web-vue/components/input/input-search.tsx
packages/web-vue/components/input/input.tsx
packages/web-vue/components/radio/radio-group.tsx
packages/web-vue/components/radio/radio.tsx

|   common  |   修复部分组件 ts 错误问题   |   Fix some component ts errors   |    Close #1131            |

fix: fix typescript problem
