packages/web-vue/components/input-number/input-number.tsx
- 系统：MacOS 11.4
- 浏览器：Google Chrome 95.0.4638.54（正式版本） (arm64)
二次封装动态渲染表单时，使用如下操作
```vue
<a-form-item
:field="column.prop"
:label="column.name"
v-bind="column"
>
<a-input
v-if="!column.type || column.type === 'text'"
v-model="form[column.prop]"
type="number"
/>
<a-input-number
v-if="column.type === 'number'"
v-model="form[column.prop]"
v-bind="column"
type="text"
/>
</a-form-item>
```
此时当column包含{type:'number'}，由于a-form-item将attrs传递给children
将会导致a-input-number出现双上下箭头
```ts
const value = ref(0)
```
```vue
<a-input-number v-model="value" />
```
- 将a-input-number中引用a-input的type指定为text，避免被attrs影响
- 初始时判断props.modeValue为undefined时才赋值_value为空字符串
|   input  |  修复 …
=> fix(input-number): fix render default arrow caused by form-item attrs contain type and not effect when modelValue is 0

.vscode/settings.json, packages/web-vue/components/image/README.en-US.md, packages/web-vue/components/image/README.zh-CN.md, packages/web-vue/components/image/image.vue
add a slot named error-icon to support custom error status icon
|image| 增加一个名为 `error-icon` 的 slot 用于支持定制错误状态的图标|Add a slot named error-icon to support custom error status icon| #51|
=> Add a slot named error-icon to support custom error status icon

packages/web-vue/components/slider/slider-button.vue
1. Release the drag event when right-click.
2. Prevent the default behavior of mousedown.
|       slider    |   修复点击右键没有释放拖拽事件的问题           |    Fixed the problem that the right click did not release the drag event           |        Close #73         |
=> fix: right-clicking does not release the drag event

packages/web-vue/components/popconfirm/popconfirm.vue
下列参数无效
参数名 | 描述 | 类型 | 默认值
-- | -- | -- | --
ok-loading | 确认按钮是否为加载中状态 | boolean | false
ok-button-props | 确认按钮的Props | object | -
cancel-button-props | 取消按钮的Props | object | -
增加buttonProps参数绑定到按钮上
|   popconfirm |  修复 `ok/cancel` 按钮参数丢失的问题  |   Fix the problem that the parameters of the `ok/cancel` button are lost   |                |
=> fix/feat(popconfirm): fix the problem of invalid button props

packages/web-vue/components/_components/virtual-list/hooks/use-render-children.tsx, packages/web-vue/components/_components/virtual-list/virtual-list.vue
Fixes #61 
In `packages/web-vue/components/_components/virtual-list/hooks/use-render-children.tsx`, VNode will be cached by index on render.
When virtual list data prop changes, the index of each virtual list item may change but the cache is not reset. And the wrong VNode from the cache will be used to render new item.
In #61 , when expand/collapse a tree node, the `data` prop passed to virtual list component changes. But the cached VNodes are used to render new tree nodes and it looks like the parent node cannot be collapsed.
Attention to node `0-0-0-5`, the next sibling node should be `0-0-0-6` if its parent node is expanded.
Pass `internalData` to `useRenderChildren` hook and reset `itemRenderCache` when `internalData` changes.
| Component | Changelog(CN) | Changelog(EN) | Related …
=> fix(virtual-list): reset itemRenderCache when internalData changes

packages/web-vue/components/tree/hooks/use-checked-state.ts
The variable `localCheckedKeys` should not be reset on the first time watchEffect be executed.
|     tree      |    修复设置  `default-checked-keys` 无效的问题         |     Fix the problem that the setting of `default-checked-keys` is invalid          |       -         |
=> fix(tree): the prop default-checked-key does not take effect

packages/web-vue/components/page-header/page-header.vue
Fix dividing will also be displayed when there is no subtitle
| page-header | 修复没有子标题时仍然显示分割线的问题  | Fix the problem that the dividing line is still displayed when there is no subtitle | Close #218  |
=> fix(page-header): fix dividing will also be displayed when there is no subtitle

packages/web-vue-storybook/stories/components/menu.vue, packages/web-vue/components/layout/__demo__/custom-icon.md, packages/web-vue/components/layout/__test__/__snapshots__/demo.test.ts.snap, packages/web-vue/components/menu/__demo__/sub-menu.md, packages/web-vue/components/menu/__test__/__snapshots__/demo.test.ts.snap, packages/web-vue/components/menu/base-menu.vue, packages/web-vue/components/menu/overflow-wrap.tsx
… are collapsed and then expanded
|    menu       |      横向的菜单项收起再展开的时候没有正常显示         |     Horizontal menu items are not displayed normally when they are collapsed and then expanded          |        Close #232         |
=> fix(menu):Horizontal menu items are not displayed normally when they are collapsed and then expanded

packages/web-vue/components/cascader/style/index.less, packages/web-vue/components/radio/style/index.less
remove radio & cascader selected font-weight
|  radio  |  去除 button 模式下选中加粗的效果  |  Remove the selected bold effect in button mode |  Close #21   |
|  cascader  |  去除选项选中加粗的效果  |  Remove the option to select the bold effect  |                |
=> fix: remove radio & cascader selected font-weight

packages/web-vue/components/tree-select/__demo__/basic.md, packages/web-vue/components/tree-select/__demo__/checkable.md, packages/web-vue/components/tree-select/__demo__/checked-strategy.md, packages/web-vue/components/tree-select/__demo__/control.md, packages/web-vue/components/tree-select/__demo__/field-names.md, packages/web-vue/components/tree-select/__demo__/label-in-value.md, packages/web-vue/components/tree-select/__demo__/load-more.md, packages/web-vue/components/tree-select/__demo__/multiple.md, packages/web-vue/components/tree-select/__demo__/popup-visible.md, packages/web-vue/components/tree-select/__demo__/search-remote.md, packages/web-vue/components/tree-select/__demo__/search.md, packages/web-vue/components/tree-select/__demo__/size.md, packages/web-vue/components/tree-select/__demo__/virtual.md, packages/web-vue/components/tree-select/hooks/use-filter-tree-node.ts, packages/web-vue/components/tree-select/tree-select.vue
fix the problem that filter is invalid when rename the key field
|     tree-select      |   修复设置 key 字段名的时候搜索失效的问题            |      fix the problem that search is invalid when rename the key field         |     Close #387           |
=> fix(tree-select): fix the problem that filter is invalid when rename the key field

packages/web-vue/components/input-tag/input-tag.tsx
fix mirror resize problem
|  input-tag  |  修复某些情况下内部 input 大小计算错误的问题  |  Fix the problem that the internal input size is calculated incorrectly in some cases  |                |
=> fix(input-tag): fix mirror resize problem

packages/web-vue/components/tabs/tabs-nav-ink.vue, packages/web-vue/components/tabs/tabs-nav.tsx
fix ink resize problem
|   tabs  |  修复标签栏宽度变化时，没有重新计算滚动的问题  | Fix the problem that scrolling is not recalculated when the width of the tab bar changes  |    Close #377   |
|   tabs  |  修复标签选项宽度变化时，指示器宽度不能跟随更新的问题  | Fix the problem that the indicator width cannot follow the update when the width of the label option changes  |                |
=> fix(tabs): fix ink resize problem

packages/web-vue/components/table/table.tsx
fix resize & selection problem
|  table  |   修复 x 轴 resize 问题   |    fix x-axis resize issue    |   Close #216     |
|  table  |   修复存在固定列时，展开行宽度设置错误的问题   |   Fix the problem that the width of the expanded row is incorrectly set when there are fixed columns    |   Close #506      |
|  table  |   修复存在子树时，复选框全选设置错误的问题   |   Fix the problem that the checkbox selection all is set incorrectly when there are subtrees   |   Close #495       |
=> fix(table): fix resize & selection problem

packages/web-vue/components/table/table-operation-td.tsx, packages/web-vue/components/table/table.tsx
button not trigger row-click
|  table  |   内部按钮不再触发 `row-click` 事件   |  Internal buttons no longer fire `row-click` events  |                |
=> perf(table): button not trigger row-click

packages/web-vue/components/cascader/cascader-search-panel.tsx, packages/web-vue/components/cascader/cascader.vue
fix check-strictly mode problem in search
|  cascader  |  修复在 `check-strictly` 模式下，搜索中不能选择的问题  |  Fixed an issue where the search could not be selected in `check-strictly` mode  |                |
=> fix(cascader): fix check-strictly mode problem in search

packages/web-vue/components/_utils/vue-utils.ts, packages/web-vue/components/list/list.tsx, packages/web-vue/components/space/space.tsx
|  list  |   默认渲染 spin 组件，防止切换状态时导致组件重新挂载   |   The spin component is rendered by default to prevent the component from remounting when switching states   |                |
|  list  |   支持渲染任何子元素   |   Supports rendering of any child element  |                |
=> perf(list): always render spin; support any child element

packages/web-vue/components/form/form.vue, packages/web-vue/components/form/style/index.less
|   form   |   `auto-label-width` 开启时不在允许标签换行，防止换行后计算错误   |  When `auto-label-width` is enabled, label wrapping is not allowed to prevent calculation errors after wrapping  |                |
=> perf(form): nowrap when auto-label-width

packages/web-vue-storybook/stories/components/virtual-list.vue, packages/web-vue/components/_components/virtual-list/hooks/use-item-height.ts, packages/web-vue/components/_components/virtual-list/virtual-list.vue
|    virtual-list       |     修复虚拟列表在项目高度偏差较大的时候出现底部空白的问题          |       Fixed the problem that the bottom blank of the virtual list appears when the item height deviation is large        |         close #758        |
=> fix(virtual-list): visibleCount is now calculated from the minItemheight

packages/web-vue/components/tree-select/hooks/use-selected-state.ts, packages/web-vue/components/tree-select/tree-select.vue
…ue is true
|    tree-select       |       当 label-in-value 为 true 的时候，事件 change 的入参错误        |       When the prop label-in-value is true, the actual parameter value of the event change is wrong        |     close #940            |
=> fix(tree-select): the event change has wrong params when label-in-value is true

packages/web-vue/components/modal/style/index.less
防止内容元素超出modal
在modal全屏模式下，内容高度超出了全屏的高度，导致下图情况: 
`arco-modal-body`样式添加`overflow: auto;`
|  modal  |   body 层增加 `overflow: auto`   |  Add `overflow: auto` to the body layer   |     |
=> fix(modal): add css style

packages/web-vue/components/_utils/types.ts, packages/web-vue/components/cascader/README.en-US.md, packages/web-vue/components/cascader/README.zh-CN.md, packages/web-vue/components/cascader/TEMPLATE.md, packages/web-vue/components/cascader/__demo__/expand.md, packages/web-vue/components/cascader/__demo__/fallback.md, packages/web-vue/components/cascader/__demo__/panel.md, packages/web-vue/components/cascader/__test__/__snapshots__/demo.test.ts.snap, packages/web-vue/components/cascader/base-cascader-panel.tsx, packages/web-vue/components/cascader/cascader-option.tsx, packages/web-vue/components/cascader/cascader-panel.vue, packages/web-vue/components/cascader/cascader-search-panel.tsx, packages/web-vue/components/cascader/cascader.vue, packages/web-vue/components/cascader/context.ts, packages/web-vue/components/cascader/hooks/use-selected-path.ts, packages/web-vue/components/cascader/interface.ts, packages/web-vue/components/cascader/utils.ts
|  New feature  |  cascader  |    选项 value 支持对象格式，增加 `value-key` 属性    |    Option value supports object format, add `value-key` attribute   |                |
|  New feature  |  cascader  |    增加 `fallback` 属性，可以自定义不存在选项的展示           |     Add the `fallback` attribute to customize the display of options that do not exist    |                |
|  New feature  |  cascader  |    增加 `expand-child` 属性，可以展开子菜单      |   Add the `expand-child` property to expand the submenu    |                |
|  Enhancement  |  cascader  |    优化子菜单展开逻辑和键盘事件      |   Optimize submenu expansion logic and keyboard events  |                |
|  Breaking change  | …
=> feat(cascader): add object value support

packages/web-vue/components/upload/upload-list-item.tsx
There will be trailing space after upload-list-item if show-remove-button is set to `false`.
[https://codesandbox.io/s/dank-water-91mrmm](https://codesandbox.io/s/dank-water-91mrmm)
A span with 12px left margin without the remove icon is left in the upload-list-item. The span rather than the icon should be omitted on show-remove-button is set to false.
|  upload         | 移除了 upload-list-item 末尾的多余空白              |        Remove trailing space of upload-list-item       |                |
=> fix(upload): Fix trailing space of upload-list-item.

packages/web-vue/components/tree/tree.vue
修复 `default-expand-selected` 在某些场景没起作用的问题
已取消默认展开父节点 (`default-expand-all=false`) ，并设置了默认展开已选中节点 (`default-expand-selected=true`) 和选中节点 (`v-model:selected-keys`)时 ，没有自动展开选中的节点。
问题重现：https://codesandbox.io/s/eager-hill-jlh8kv?file=/src/App.vue
|   tree   |   修复设置 defaultExpandSelected 失效的问题   |    Fix the problem of setting defaultExpandSelected invalid   |         |
=> fix(tree): default-expand-selected does not work well with selected-keys

packages/web-vue/components/carousel/style/index.less
close #1900
修改 `packages/web-vue/components/carousel/style/index.less` 的内容，添加 `visibility: hidden` 至 `not-item-current`
```less
> *:not(.@{carousel-prefix-cls}-item-current) {
display: none;
visibility: hidden;
}
```
| Component | Changelog(CN)                                        | Changelog(EN)                                                | Related issues |
| --------- | ---------------------------------------------------- | ------------------------------------------------------------ | -------------- |
| Carousel  | 修复 `Carousel` 透明背景图片无法遮罩上一张图片的问题 | Fix the problem that the transparent background image of `Carousel` cannot cover the previous image | #1900          |
原因是切换下一张图片后，上一张图片有以下样式：
```less
&-slide {
> …
```
=> fix(carousel): transparent background images should be masked

packages/web-vue/components/switch/style/index.less, packages/web-vue/components/switch/switch.vue
|   Switch  |  修复类型为`line`时自定义颜色样式错误的问题  | Fix the problem that the custom color style is wrong when the type is `line` |  Close #2039   |
=> fix(switch): custom color style erro when type is line

packages/web-vue/components/select/select.tsx, packages/web-vue/components/select/utils.ts
|     select      |         不允许自动创建空字符串条目。含有空字符串的下拉选项，清空时将值设置为 `undefined`      |     Automatic creation of empty string entries is not allowed. Dropdown option with empty string, set value to `undefined` when empty   |   Close #2254        |
解决的思路
1. 修改 `input-label` ，空字符串的情况下显示 `placeholder`
2. 当不存在空字符串的条目时，不允许自动创建空字符串条目
采用了第二种方式
另外当含有空字符串下拉选项时，清空的时候应该将 `_value.value = undefined`且支持 `_value.value` 为 `undefined`
=> fix(select):  不允许自动创建空字符串条目。含有空字符串的下拉选项，清空时将值设置为undefined

packages/web-vue/components/date-picker/range-picker.vue
range-picker 文件下补全了对于exchange-time属性的判断逻辑
时间会错乱的问题
[1850](https://github.com/arco-design/arco-design-vue/issues/1850)
|  date-picker  |   修复 exchange-time 在选择时失效的问题    |    Fix the problem that exchange-time fails when selecting   | Close #1850  |
=> fix: 修复exchange-time在select下没生效的问题

packages/web-vue/components/date-picker/style/index.less
Panel-only DatePicker and RangePicker are rendered with unexpected box-shadow.
Change class name to `.@{prefix}-picker-container-panel-only` and `.@{prefix}-picker-range-container-panel-only` to match classes used in components.
|  date-picker         |  修复只使用面板情况下的样式问题             | fix styling problem with panel-only pickers              |                |
=> fix(date-picker): fix class names

packages/web-vue/components/mention/README.en-US.md, packages/web-vue/components/mention/README.zh-CN.md, packages/web-vue/components/mention/mention.tsx
|    mention  |    search 事件增加 `prefix` 属性           |     Add `prefix` attribute to search event     |    Close #2354            |
=> feat(mention): search event add a prefix param

packages/web-vue/components/divider/style/index.less
竖向时无法跟随周围的高度变化。
[复现地址](https://codesandbox.io/s/laughing-sara-q3254h?file=/src/App.vue)
调整为最小高度1em，其他自动跟随外层高度撑开
其实原本这个问题可以使用者直接通过style解决，就看这个特性是否变为组件默认。
|    divider       |     修复竖向自适应高度         |    fix  adaptive height issue with divider         |                |
=> fix: adaptive height issue with divider

packages/web-vue/components/input-number/README.en-US.md, packages/web-vue/components/input-number/README.zh-CN.md, packages/web-vue/components/input-number/TEMPLATE.md, packages/web-vue/components/input-number/__demo__/step-icon.md, packages/web-vue/components/input-number/input-number.tsx
#2559 
增加图标 `plus` 和 `minus` 插槽用于自定义操作按钮图标.
``` ts
增加：upIcon | up | plus
减少：downIcon | down | minus
命名选择为与Arco 图标相同意义描述的命名保持统一
```
|     input-number      |     增加数值操作自定义图标插槽       |      add slots for input-number box value manipulation icons         |      Close #2559        |
=> feat: add slots for input-number box value manipulation icons

packages/web-vue/components/typography/style/index.less
typography组件对连续单词、数字出现省略失效问题。
https://codesandbox.io/s/long-hooks-8r9q9j?file=/src/App.vue
默认给`typography`加上单词拆分overflow-wrap。[overflow-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) （感觉使用anywhere可以不破坏单词结构的情况下尽可能多地显示文本内容时还尊重语义关联。）
同时参考React版本的默认效果：[Arco React版](https://github.com/arco-design/arco-design/blob/ddfe708fbbe633cb77458796a4159ef7aeb89de1/components/Typography/style/index.less#L10)
经测试增加后不会影响以前的版本效果。
|    typography       |    增强对连续长单词的省略支持     |      enhanced typography styles for handling long words          |    |
=> fix(typography): enhanced typography styles for handling long words

packages/arco-vue-docs/docs/start.en-US.md, packages/arco-vue-docs/docs/start.zh-CN.md, packages/web-vue/components/statistic/style/index.less, packages/web-vue/components/statistic/style/token.less, packages/web-vue/components/table/TEMPLATE.md
|   statistic  |  修复 `value-style` 在数字内容时不能修改字体大小的问题  |   Fix the problem that `value-style` cannot modify the font size in digital content   |   Close #2584   |
=> fix(statistic): fix value style problem

packages/web-vue/components/table/hooks/use-drag.ts, packages/web-vue/components/table/table.tsx, packages/web-vue/components/table/utils.ts
树形表格展开后拖拽功能基本处于不可用的状态，此 PR 解决树形表格拖拽问题。
|  table  | 修复树形表格拖拽问题 | fix drag issue in tree table |                |
=> fix(table): draggable tree table

packages/web-vue/components/timeline/README.en-US.md, packages/web-vue/components/timeline/README.zh-CN.md, packages/web-vue/components/timeline/TEMPLATE.md, packages/web-vue/components/timeline/__demo__/custom.md, packages/web-vue/components/timeline/item.vue
close #2590 
| timeline | 添加自定义标签插槽 | add label slot | Close #2590  |
=> feat(timeline): add label slot

.gitattributes, .prettierrc.js, packages/arco-changelog/.prettierrc.js, packages/arco-vue-docs/.prettierrc.js, packages/arco-vue-scripts/.prettierrc.js, packages/vite-plugin-arco-vue-docs/.prettierrc.js, packages/web-vue-storybook/.prettierrc.js, packages/web-vue/.prettierrc.js
This PR addresses an issue reported by the IDE regarding an `␍` error caused by ESLint and Prettier. The problem primarily stems from formatting discrepancies due to newline characters.
The formatting issue was resolved by adjusting the code formatting to eliminate newline-related formatting problems. Additionally, Prettier configurations were updated to ensure consistent code style.
The change was tested by running the test suite using `npm run test`. No new unit tests were required for this coding style change.
| Coding Style | 修复了导致"␍"错误的格式问题 | Fixed formatting issue causing `␍` error | None |
No further information to provide.
=> style: fix IDE-reported ESLint Error: Remove ␍ Error

packages/web-vue/components/select/__demo__/basic.md, packages/web-vue/components/select/interface.ts, packages/web-vue/components/select/option.vue, packages/web-vue/components/select/select.tsx, packages/web-vue/components/select/utils.ts
|      select     |         支持`boolean` 类型      |        support boolean type       |        Close #2457       |
=> feat(select): support boolean type

packages/web-vue/components/form/form-item.vue, packages/web-vue/components/form/form.vue, packages/web-vue/components/form/utils.ts
表单项上的id未经处理导致嵌套时报错
#2703
#2702
增加函数getFormElementId统一生成，将field中的特殊字符过滤替换。
|      form     |    修复field为数组对象时滚动报错问题      |    scroll-to-first-error throws error in nested form items           | Close #2703 , Close #2702     |
=> fix(form): scroll-to-first-error error in nested form items

packages/web-vue/components/auto-complete/README.en-US.md, packages/web-vue/components/auto-complete/README.zh-CN.md, packages/web-vue/components/auto-complete/__demo__/scroll.md, packages/web-vue/components/auto-complete/auto-complete.tsx
解决分页需求问题
参加select增加事件
| auto-complete  | 增加下拉菜单滚动事件   |   add dropdown scroll event    |   Close #2594   |
=> feat(auto-complete): add dropdown scroll event

packages/web-vue/components/transfer/README.en-US.md, packages/web-vue/components/transfer/README.zh-CN.md, packages/web-vue/components/transfer/transfer.vue
无法自定义操作图标
|    transfer       |     增加操作图标插槽         |       add an action icon slot        |                |
=> feat(transfer): add an action icon slot

packages/web-vue/components/trigger/README.en-US.md, packages/web-vue/components/trigger/README.zh-CN.md, packages/web-vue/components/trigger/trigger.tsx
Issues #2678
PR #2679 
如果开启了`scrollToClose`则滚动时记录下初始位置当滚动距离达到阈值时触发关闭。
|    trigger       |  增加滚动关闭阈值    |       add scroll to close distance        |  Close #2678 , Close #2679    |
=> feat(trigger): add scroll to close distance

packages/web-vue/components/input-tag/input-tag.tsx
|   input-tag   |   修复 `read-only` 下仍然能被删除的问题   |    Fix the problem that the file can still be deleted under `read-only`  |                |
=> fix(input-tag): fix readonly problem

packages/web-vue/components/_utils/date.ts
**问题：日期选择器中当传入的值与format不一致的时候会出现Invalid Date 导致组件无法正常运作**。
由于范围选择器就算不设置 `format` 但开启 `showTime` 时内部会默认给`YYYY-MM-DD HH:mm:ss` 所以表现尤为明显
**原因：**
追溯到全局组件通用`date.ts`函数文件中 
dayjs扩展的 `customParseFormat` 插件使用条件如它文档第一句也就是传入的字符串格式需要和 `format` 尽可能一致（特性bug👀）
官网表现如图：
https://day.js.org/docs/zh-CN/parse/string-format
添加了有效日期校验 不满足时返回正常对象，进行输出兜底以保证组件正常运作。
|   date-picker    |    修复日期与format不一致导致出现无效日期     |       fix invalid date due to mismatch between date and format        |                |
=> fix(date-picker): fix invalid date due to mismatch between date and format

packages/arco-vue-docs/components/aside-nav/style.less, packages/arco-vue-docs/locale/en-us.js, packages/arco-vue-docs/locale/zh-cn.js, packages/arco-vue-docs/router.ts, packages/web-vue/components/arco-vue.ts, packages/web-vue/components/components.ts, packages/web-vue/components/index.less, packages/web-vue/components/index.ts, packages/web-vue/components/verification-code/README.en-US.md, packages/web-vue/components/verification-code/README.zh-CN.md, packages/web-vue/components/verification-code/TEMPLATE.md, packages/web-vue/components/verification-code/__demo__/basic.md, packages/web-vue/components/verification-code/__demo__/form.md, packages/web-vue/components/verification-code/__demo__/formatter.md, packages/web-vue/components/verification-code/__demo__/masked.md, packages/web-vue/components/verification-code/__demo__/separator.md, packages/web-vue/components/verification-code/__demo__/status.md, packages/web-vue/components/verification-code/__test__/__snapshots__/demo.test.ts.snap, packages/web-vue/components/verification-code/__test__/demo.test.ts, packages/web-vue/components/verification-code/index.ts, packages/web-vue/components/verification-code/style/index.less, packages/web-vue/components/verification-code/style/index.ts, packages/web-vue/components/verification-code/style/token.less, packages/web-vue/components/verification-code/verification-code.tsx
[验证码输入框 VerificationCode](https://arco.design/react/components/verification-code)
https://github.com/arco-design/arco-design-vue/assets/48879481/62541059-c250-4c6d-ad45-17710217499f
|    VerificationCode       |     新增验证码输入组件          |   add verification-code  component       |                |
=> feat(verification-code): add verification-code component

packages/web-vue/components/watermark/hooks/use-theme.ts, packages/web-vue/components/watermark/watermark.tsx
#2785 
水印组件跟随主题变化
因为组件库相对固定的主题选择器[body](https://github.com/arco-design/arco-design-vue/blob/f5408019ac5ad9dfb29159649956aeba5010ce36/packages/web-vue/components/style/theme/global.less#L3C1-L3C1)
通过观察器 `useMutationObserver` 来观察body上主题的变化来控制水印。并关闭了不必要的观察配置以最佳性能运作。
https://github.com/arco-design/arco-design-vue/assets/48879481/c70f70c6-f410-45e8-85ea-316077c6a2f9
|    watermark       |       水印字体色跟随主题变化        |    watermark font color  follows the theme         |    Close  #2785           |
=> feat(watermark): fontColor follows the theme

packages/web-vue/components/input/__test__/__snapshots__/demo.test.ts.snap, packages/web-vue/components/input/style/group.less, packages/web-vue/components/input/style/input.less
- https://github.com/arco-design/arco-design-vue/issues/1737
- 另外，亦参考了这个 issue：https://github.com/arco-design/arco-design-vue/issues/1758
修改了 input 组件的部分 `z-index` 和 `border-right-color` 属性
- 由于暂时未能在 acro-design-vue 使用线性主题，通过本地修改一些 vars 验证了提交的效果
- 更新了 input 测试用例
| input | 修复 input-group 相邻组件样式叠加时的问题 | Fix overlapping styles of neighboring components in input-group | Close #1737 , Close #1758 |
如果之后本地能引入线性主题复现问题，可能会进一步修改
=> fix(input): fix overlapping styles of neighboring components in input-group

packages/web-vue/components/avatar/avatar-group.tsx
当省略的头像数量大于最大显示数时，z-index会成为负数导致无法正常显示。
|  avatar-group         |   修复头像组气泡中部分头像不显示问题      |      fix partial avatars not displaying in the avatar group popover         |     #2745         | 
=> fix(avatar-group): fix partial avatars not displaying in the avatar group popover

packages/web-vue/components/image/README.en-US.md, packages/web-vue/components/image/README.zh-CN.md, packages/web-vue/components/image/interface.ts, packages/web-vue/components/image/preview-group.vue, packages/web-vue/components/image/preview.vue, packages/web-vue/components/input/README.en-US.md, packages/web-vue/components/input/input-password.vue
#2850
[#336](https://github.com/arco-design/arco-design-pro-vue/issues/336)
1. 更正拼写错误
2. 修复 `ImagePreviewProps` 类型定义问题。
3. 修复 `popupContainer` 类型定义缺失
打包后通过更改软连接测试 无异常。
|    image       |    修复错误的类型定义和文档说明       |   adjust incorrect type definitions and documentation    |    Close  #2850           |
|    image-preview       |    修正单词拼写错误     |    fix spelling mistakes   |      Close #2744        |
|    input-password       |    修正文档单词拼写错误       |   fix spelling mistakes    |   Close #2744       |
=> fix(image): adjust incorrect type definitions and documentation

packages/web-vue/components/input-number/input-number.tsx
数字输入框change事件触发逻辑修复
#2904 
最小复现(不聚集输入框直接点击清空按钮)：https://codesandbox.io/p/sandbox/frosty-wing-nhcm6s
1. `handleChange` 增加对input change事件类型的区分 如果是Clear就不执行。
2.  修复 modelEvent 为input 时 值变化 change 事件没触发问题
|   input-number        |  修复 change 事件触发逻辑           |     Fix change event triggering mechanism          |    #2904       |
=> fix(input-number): fix change event triggering mechanism

packages/web-vue/components/input-number/input-number.tsx
在 PR #2915 的变更时影响到了 model-event 为 `change` 时更新 modelValue 的时机（双向绑定失效）。
|   input-number        |   修复双向绑定失效         |      fix v-model not working          |  Closes #2959, Closes #2965, Closes #2981, Closes #2983     |
=> fix(input-number): fix v-model not working

packages/web-vue/components/_utils/date.ts, packages/web-vue/components/date-picker/__demo__/week.md, packages/web-vue/components/date-picker/__test__/__snapshots__/demo.test.ts.snap, packages/web-vue/components/date-picker/panels/week/index.vue
https://github.com/arco-design/arco-design-vue/issues/2896
Locale methods in Dayjs sometimes does not change the way dates respond to `weekStart` customizations. Therefore we rewrite the methods
- `startOfWeek` that returns the start day of week and 
- `isSameWeek` that compares the week numbers of two dates, 
calculating week numbers that changes with `weekStart`.
Dayjs 中的 locale 方法有时不会改变日期对自定义 `weekStart` 的响应方式。因此，重写了
- 返回一周开始日期的 `startOfWeek` 方法和 
- 比较两个日期的周数的 `isSameWeek` 方法 
以计算随 `weekStart` 变化的周数。
- Please see the updated WeekPicker demos and switch locale to English to see the correct behavior.
- 请查看更新后的 WeekPicker demo，并将语言切换为英语，以查看正确的行为。
| Component | Changelog(CN) | Changelog(EN) | Related issues | Type |
| --------- | ------------- | ------------- | -------------- | ---- |
| …
=> fix(date-picker): refactor date utility functions and week picker to correctly show selected week

packages/web-vue/components/transfer/transfer-view.vue, packages/web-vue/components/transfer/transfer.vue
**transfer** 组件开启`disabled` 属性不生效。只有针对单条数据项 `disabled` 有用。
|     transfer      |  修复 disabled 属性不生效问题   |  fix disabled props not working     |    Closes #2993       |
=> fix(transfer): fix disabled props not working

packages/web-vue/components/modal/style/index.less
`modal` 组件在默认的 `fade-modal` 遮罩层动画下，淡入渐进效果不生效。在 #3000 提出该问题但非 `v-if` / `v-show` 逻辑导致。
https://github.com/arco-design/arco-design-vue/assets/48879481/d9fb6972-50d4-40b8-9634-023fa11e1d50
修正拼写错误导致动画缺失
修复效果：
https://github.com/arco-design/arco-design-vue/assets/48879481/ed52d0b8-ec99-41ec-8332-39a23fb6ca64
|     modal      |   修复遮罩层 fade-modal 过渡动画在进入时不生效问题            |     fix fade-modal transition effect works on enter state          |    Closes #3000, Closes #2836     |
=> fix(modal): fix fade-modal transition effect works on enter state

packages/web-vue/components/input-number/input-number.tsx, packages/web-vue/components/input-number/style/index.less
开启 `suffix` 插槽或者 `append` 时会出现步进按钮重叠。
问题描述 #2999 
相关 PR #3003
原本的样式代码中有相关的实现但有缺陷未生效。
针对 vue 版实现修改最终与React [demo](https://codesandbox.io/p/sandbox/frosty-smoke-wmvvm3) 效果一致。
未hover 时：
hover 时：
https://github.com/arco-design/arco-design-vue/assets/48879481/547cf1de-a50a-482f-88e1-5c7a4f62022d
snapshots没变化
|  input-number  |   修复步进按钮与 suffix/append 的样式重叠     |   fix overlap between step button and suffix/append   |   Closes #2999             |
=> fix(input-number): fix overlap between step button and suffix/append

packages/web-vue/components/empty/empty.tsx
`empty` 组件在全局配置 `ConfigProvider` 设置了自定义空状态后会出现继承警告问题
> [!WARNING]
> [Vue warn]: Extraneous non-props attributes (**xxxx**) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.
当使用 `configCtx.slots.empty` 自定义空状态时无法确定是否是单个根节点
https://github.com/arco-design/arco-design-vue/blob/faf3ce8cdb10bdda25b5217d6c13c0d7ce2e95c7/packages/web-vue/components/empty/empty.tsx#L41-L47
直接添加一个层包裹可以解决但层级结构变了 怕影响大
```jsx
return <div>{configCtx.slots.empty({ component: 'empty' })}</div>
``` 
该 PR 采用手动选择性继承，影响范围与之前一致
|    empty       |    修复属性自动继承的错误           |   fix automatically inherited warn   |    Closes #3034 …
=> fix(empty): fix automatically inherited warn

packages/web-vue/components/color-picker/color-picker.tsx
双向绑定失效
modelValue更新后未及时更新组件内部相关变量
|    color-picker       |     修复双向绑定不生效问题        |      fix v-model not working         |  Closes #3029   |
=> fix(color-picker): fix v-model not working

packages/web-vue/components/tree/style/index.less
**修改前**
tree组件的子节点前面存在一个缩进块，这是个空白的行内元素，内部会产生"幽灵空白节点"，导致树整体的scrollHeight大于clientHeight，最终在treeSelect的下拉中本不该产生滑动条的情况下产生了滑动条
**修改后**
修改行内元素的vertical-align，使scrollHeight计算正确
|      tree     |      修复scrollHeight计算异常问题         |       fix scrollHeight calculation exception problem        |                |
=> style(tree): fix scrollheight calculation of inline-block element

packages/web-vue/components/cascader/cascader.vue, packages/web-vue/components/date-picker/picker.vue, packages/web-vue/components/date-picker/range-picker.vue, packages/web-vue/components/dropdown/dropdown-button.vue, packages/web-vue/components/image/preview-group.vue, packages/web-vue/components/popconfirm/popconfirm.vue, packages/web-vue/components/popover/popover.vue, packages/web-vue/components/tooltip/tooltip.vue, packages/web-vue/components/tree-select/interface.ts, packages/web-vue/components/tree-select/tree-select.vue
使用了 `trigger ` 的组件很多，但它们的 `popupContainer`  的类型定义不统一。
与 trigger 的 `popupContainer` 定义一致
```vue
popupContainer: {
type: [String, Object] as PropType<string | HTMLElement>,
},
```
|          |     修正 `popupContainer` 的类型定义         |    correct the type definition for popupContainer           |                |
方便 CR 没有 docgen
=> refactor: correct the type definition for popupContainer

packages/web-vue/components/time-picker/README.en-US.md, packages/web-vue/components/time-picker/README.zh-CN.md, packages/web-vue/components/time-picker/time-picker.vue
`readonly ` 不生效，只读模式点击输入框依然可以进行修改。
| fix |  time-picker  |  修复只读模式仍可编辑问题 |  Fix issue with read-only mode still being editable |  Closed #3151  |
| docs |  time-picker  |  补充 `placeholder` 类型定义 |  Added `placeholder` type definition |    |
=> fix(time-picker): fix issue with read-only mode still being editable

packages/web-vue/components/input/input.tsx
在只读状态下开启 `allow-clear` 依然会显示清空按钮可清空输入框内容
|  input   |  修复只读状态下显示清空输入框按钮  | fix display of allow-clear input button in read-only state |                |
=> fix(input): fix display of allow-clear input button in read-only state

packages/web-vue/components/tree/expand-transition.vue
**修改树节点折叠动画不生效问题**
**修改前**
树的展开折叠动画，只有展开动画生效，折叠动画失效
把动画时间调到了2s，方便查看效果：
https://github.com/user-attachments/assets/2db6c1c8-89a8-4ba4-b47f-9c409e74e27c
**修改后**
展开和折叠动画都生效，效果如下：
https://github.com/user-attachments/assets/64061a11-68cd-4d4f-8b73-9780da20e451
**产生原因**
树产生动画的节点，无论展开折叠都是节点从无到有的过程，所以在before-enter回调中，获取到的scrollHeight都是0，这样折叠动画就是高度从0到0，所以动画失效
**解决方案**
不在before-enter中获取初始高度，统一改到enter中获取初始高度，强制浏览器回流后获取最终高度，使动画生效
|      tree     |      修复树折叠动画不生效问题      |       fix tree node folding animation        |                |
=> fix: fix tree node folding animation

.github/workflows/issue-duplicate.yml, .github/workflows/issue-labeled.yml, .github/workflows/issue-manager.yml, .github/workflows/issue-remove-inactive.yml
增加一些工作流来处理 issues，完善一些标签机制，进一步加快 issue 的反馈和处理效率。
=> ci: add automatic management for issues

packages/web-vue/components/textarea/README.en-US.md, packages/web-vue/components/textarea/README.zh-CN.md, packages/web-vue/components/textarea/textarea.vue
textarea 组件缺少透传的方案，当我想要定制 textarea 的 enterKeyHint 的时候，发现无法做到，只能使用原生的 textarea 实现
增加 textareaAttrs 以便于传入 enterKeyHint 等原生属性，应该能解决该问题
| textarea | 支持textarea的textareaAttrs属性 | Support textareaAttrs attribute for textarea |                |
=> feat(textarea): add props textareaAttrs for textarea

.github/workflows/issue-labeled.yml, .github/workflows/issue-manager.yml
=> ci: adjust ci run conditions and minor details

packages/web-vue/components/components.ts
https://github.com/vuejs/language-tools/issues/4503
https://github.com/vuejs/language-tools/pull/4492/files#diff-1d432278152c845126fa9e323391375cf8fa8806a2cad5c1da6282dae4019947L15
https://github.com/vuejs/language-tools/wiki/Global-Component-Types
|           |  更新 `GlobalComponents ` 声明           |  update GlobalComponents declarations             |                |
=> fix(types): update GlobalComponents declarations

packages/web-vue/components/button/README.en-US.md, packages/web-vue/components/button/README.zh-CN.md, packages/web-vue/components/button/button.vue, packages/web-vue/components/button/interface.ts
由于没有在组件内部显式控制`autofocus`属性，虽然`autofocus`属性能正常工作，但是会给devtool的数据追踪带来一定的迷惑性。通过`<a-button :autofocus="true" />`、`<a-button :autofocus="false" />`这种方式使用时，devtool能够在`attr`中追踪到`autofocus`属性为`true`或者`false`，当通过`<a-button autofocus>`这种方式使用时，`autofocus`属性通过透传依然能够传递到组件上，但是此时会被devtool在`attr`中识别为`autofocus: undefined`，从而给数据的追踪带来迷惑性。
通过在组件内部显式声明该属性，能够解决该问题。
|       button    |      支持button的autofocus属性         |       Support autofocus attribute for button        |                |
=> feat(button): support autofocus property

packages/web-vue/components/drawer/drawer.vue, packages/web-vue/components/modal/modal.vue, packages/web-vue/components/popconfirm/popconfirm.vue
在之前的实现中，onBeforeOk 抛出的错误会被捕获但未重新抛出，导致调用方无法感知错误没有正常传播，可能造成业务逻辑异常
|      Modal  |   修复执行 onBeforeOk  时错误未传播的问题 | fix re-throw error in onBeforeOk for proper error handling  |                |
|     Drawer  |   修复执行 onBeforeOk  时错误未传播的问题 | fix re-throw error in onBeforeOk for proper error handling  |                |
|    Popconfirm  |   修复执行 onBeforeOk  时错误未传播的问题 | fix re-throw error in onBeforeOk for proper error handling  |                |
=> fix: re-throw error in onBeforeOk for proper error handling

packages/web-vue/components/input/input.tsx
#3347 
虽然 issue 中提到的是 inputNumber 组件，但实际上这个错误发生在 input 组件中。
可以查看 demo：https://codesandbox.io/p/sandbox/floral-framework-jjvymj?file=%2Fsrc%2FApp.vue%3A23%2C1
复现流程：默认值是 123，输入一个 4，按回车键触发 change 事件，现在 input 显示 1234，也可以看到控制台输出，等三秒定时器将输入内容设置为 789，这时候再修改为 1234，按回车，不会触发 change 事件。（注意这个过程不要让输入框失去焦点）
原逻辑是在 input 组件聚焦及触发 change 事件时更新 preValue，现使用 watch 第二个参数 oldValue 进行更新。
|    input     |     修复 input 内 preValue 计算错误问题     |    Fix the preValue calculation error in the input component      |      #3347           |
=> fix(input): 修复 input 内 preValue 计算错误问题(#3347)

.gitignore, package.json, packages/web-vue-storybook/package.json, pnpm-lock.yaml
storybook 无法启动，原因是版本 ^6.3 被包管理器提升到 6.5，6.5 默认使用 webpack 5，而 6.3 默认使用 webpack 4，因为某些不兼容的变更无法启动。
没有调查具体原因，因为项目的依赖问题最好集中解决。
storybook 锁定版本 6.3
- 终端执行 `pnpm run storybook` 命令
- storybook 成功启动并自动打开浏览器，跳转到预览界面
- 终端输出
```shell
info @storybook/vue3 v6.3.0
info
info => Loading presets
info => Loading custom babel config as JS
info => Loading 1 config file in "D:\**\packages\web-vue-storybook\.storybook"
info => Loading 9 other files in "D:\**\packages\web-vue-storybook\.storybook"
info => Adding stories defined in "D:\**\packages\web-vue-storybook\.storybook\main.js"
info => Using prebuilt manager
info => Using implicit CSS loaders
info => Using default Webpack4 setup
│   Storybook 6.3.0 started                       │
│   39 s for preview                              │
│ …
```
=> chore: fix storybook crash

packages/web-vue/components/popover/popover.vue, packages/web-vue/components/popover/style/index.less
修复popover组件的title属性以及slot为空时出现的4px下变局
判断有无 title 属性和 title slot，如果均没有则隐藏整个 title div
| popover | 修复没有 title 为空时边距问题 | Fixed an issue where there was no space time margin for title |                |
=> fix(popover): Fixed extra 4px margin that appears when title is empty
